### ISSUE TITLE
Also working with single end?

### ISSUE THREAD

**Issue by PopGenHamburg** [linzhi2013/MitoZ#1]
Hello, I just discovered the preprint on Biorxiv and came over here to check your programm. I was wondering whether it would work with single end data? If not, is there a way to trick it into doing it anyway? I know it sounds like a strange question, but our sequencing run failed half through (long story) and we could recover only one side of the reads.

**Comment by linzhi2013** [comment]
I'm closing the issue now. If you have other issues, please open new issues. Thank you!
