### ISSUE TITLE
How to extract partial fastq data from large fastq files for MitoZ?

### ISSUE THREAD

**Issue by Grelot** [linzhi2013/MitoZ#10]
Hi,
it's not really an issue related to the program.

I would like to test your program MitoZ.
It seems to work well but i can't find raw.1.fq.gz and raw.2.fq.gz files.
I would like to first test your program with the same data you used.
Can you provide me these data ?

**Comment by linzhi2013** [comment]
> Hi,
> it's not really an issue related to the program.
> 
> I would like to test your program MitoZ.
> It seems to work well but i can't find raw.1.fq.gz and raw.2.fq.gz files.
> I would like to first test your program with the same data you used.
> Can you provide me these data ?

Hi Grelot,

the `raw.1.fq.gz` and `raw.2.fq.gz` are just arbitrary names of your input fastq files.

In our paper, the raw fastq files are very large (3-5G) for each sample, thus it is unconvenient to upload to the internet.  During the development of MitoZ, we used such data for testing (and thus a bit time consuming for one run)

cheers,
guanliang

**Comment by Grelot** [comment]
Hi Guanliang,

Thank you for your answer.
I wanted to use whole genome sequencing results as an input, but the size is very large (30G) the raw fastq files you used let me think that MitoZ is designed for an other type of data as input. Am i right ?

**Comment by linzhi2013** [comment]
> Hi Guanliang,
> 
> Thank you for your answer.
> I wanted to use whole genome sequencing results as an input, but the size is very large (30G) the raw fastq files you used let me think that MitoZ is designed for an other type of data as input. Am i right ?

Hi Grelot,

I do not quite understand what you said about 'whole genome sequencing results'. Is the fastq files you have?  Fastq files from whole genome sequencing are indeed quite large in size.

If you have very large fastq files, instead of the 3-5G we recommended for mitochondrial genome assembly, and if you are using pervious versions of MitoZ, I would suggest that you extract part of your data by yourself before running MitoZ.

However, yesterday I uploaded a versioin 2.4-alpha, it has following updates:

1. add '--fq_size' option, default value is 5 Gbp.
2. For the visualization result, will also copy the circos.dep and
   circos.karyotypes.txt files to result directory.
3. the `tmp` directory now also has its prefix, as such, we can run multiple
  samples in the same directory.
4. the circos results files now also have their prefix.
5. add script same_gene_to_same_file.py, to dispath the same genes of
   different samples into same files.

Now MitoZ will only read in no more than 5G data from your input fastq files by default (via the `--fq_size` option).  Maybe this is what you want ?

Cheers,
Guanliang

**Comment by Grelot** [comment]
You understood well what i mean by 'whole genome sequencing results'. They are my fastq files from a whole genome sequencing that i want to used as  raw.1.fq.gz and raw.2.fq.gz

It's the first time, i try MitoZ, i'm looking for a tool able to assemble an individual mitogenome from the 'whole genome sequencing data' of an individual

I do not quite understand what you said about 'I would suggest that you extract part of your data by yourself before running MitoZ'. Do you mean they're a way to extract mitochondrial reads from my raw fastq files before to run MitoZ ?

I'm a bit confused about the fq size limitation option. Is it Giga base pairs or Giga octet ? My first thought will be that the input fq file is truncated to a fq file of 5 Go ?

**Comment by linzhi2013** [comment]
> You understood well what i mean by 'whole genome sequencing results'. They are my fastq files from a whole genome sequencing that i want to use as raw.1.fq.gz and raw.2.fq.gz
> 
> It's the first time, i try MitoZ, i'm looking for a tool able to assemble an individual mitogenome from the 'whole genome sequencing data' of an individual
> 
> I do not quite understand what you said about 'I would suggest that you extract part of your data by yourself before running MitoZ'. Do you mean they're a way to extract mitochondrial reads from my raw fastq files before to run MitoZ ?
> 
> I'm a bit confused about the fq size limitation option. Is it Giga base pairs or Giga octet ? My first thought will be that the input fq file is truncated to a fq file of 5 Go ?

In short, in previous versions of MitoZ, we did not provide tools to extract part of fastq files.

In previous versions of MitoZ, there is not such a `--fq_size` option, as such, MitoZ will read in all your input fastq files into memory, which can lead to a very high memory usage (and the run time can be very long). 

But now the version 2.4-alpha can extract the data for you automatically (by default 5 G bp). So users do not need to be afraid their fastq files are too large for MitoZ.

Sorry for the confusion. `3-5G` means  Giga base pairs, not the file size.

**Comment by Grelot** [comment]
OK thanks a lot, i start to understand. Is there a link or a resource where i can see the method you use to extract 5 Gbp (or the limit defined with `--fq_size`) from a large fastq file ?

**Comment by linzhi2013** [comment]
> OK thanks a lot, i start to understand. Is there a link or a resource where i can see the method you use to extract 5 Gbp (or the limit defined with `--fq_size`) from a large fastq file ?

Hi Grelot,

`--fq_size` is an option in MitoZ (version 2.4-alpha, https://github.com/linzhi2013/MitoZ/tree/master/version_2.4-alpha)

when you run `python3 MitoZ.py all -h`, you should see the option.


Or if you'd like to extract part of fastq data by yourself, you can refer to `https://github.com/linzhi2013/extractfq`. Sorry I have forgot to write it down that I had such a script.

**Comment by Grelot** [comment]
I will explore that. Thanks a lot again !

**Comment by linzhi2013** [comment]
Please feel free to open new issues when necessary.

**Comment by linzhi2013** [comment]
Now (MitoZ 3.2) can use the `--data_size_for_mt_assembly` option to extract partial data for use, see `$ mitoz filter -h` or `$ mitoz all  -h`
