### ISSUE TITLE
A lot of missing genes in the annotation,  in addition，they are not found during the assembly

### ISSUE THREAD

**Issue by kjg945** [linzhi2013/MitoZ#101]
Hi,

I was trying to use the all2 module to assemble and search for an insect mitogenome. 
The input data came from resequencing, the  script extractfq was used to extract about 2Gbps of the data out of the total file.
This is the command I used:
python3 version_2.4-alpha/release_MitoZ_v2.4-alpha/MitoZ.py all2 --genetic_code 5 --clade Arthropoda --outprefix test --thread_number 16 --fastq1 clean_1.fq.gz --fastq2 clean-2.fq.gz --fastq_read_length 150 --insert_size 301 --run_mode 2 --filter_taxa_method 1 --requiring_taxa 'Arthropoda'
I didn't got any error messages, but I meet some problems, 
first, the mitogenome was no circularity. 
second, there was many minssing genes, included  ND2, s-rRNA, tRNA-Asn, tRNA-Cys, tRNA-Gln, tRNA-His, tRNA-Ile,
tRNA-Ser,tRNA-Tyr ,and tRNA-Val. The summary.txt file told me that the missing genes might be foud from the'*.high_abundance*' and '*.low_abundance*' files, but I cnould not find missing genes in those files.

This is the summarry.txt:

And the work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted:

Do you know what causes this result？Please help me, thank you.

best wishes

Jingge Kuang

**Comment by linzhi2013** [comment]
>您可以尝试一下multi-kmer模式。线粒体组装断裂成不同的部分的原因主要是两个：
>（1）存在Repeat，并且Repeat unit过长，kmer（或reads）无法跨越整个repeat unit；
>（2）断开的位置处的测序深度过低，其原因通常是二代建库测序过程中的偏差导致，属于平台的固有缺陷，由于这些位置中的kmer存在较低丰度，组装软件会认为这种连接不可靠从而断开。

>通过增加Kmer的大小，也许可以跨越一些小的repeat；通过减小Kmer的大小，可以提高在DBG图中那些原来kmer丰度较低的位置的kmer丰度，从而避免组装断开。


from my response to a question asked via email.

**Comment by linzhi2013** [comment]
you can also run `mitoAssemble` manually, so you can different all different Kmers as you want, then do `findmitoscaf`, `annotate`, respectively.

>您可以直接把K91组装出来的结果用来跑 annotate 子命令。这样通过注释就可以进一步确认该序列是不是线粒体序列（即37个基因是否可以完整注释出来）

from my response to a question asked via email.

**Comment by linzhi2013** [comment]
**About mt-reads in silico enrichment**

>也许可以把个体A的reads比对到近缘个体的mitogenome上，然后把相关reads筛选出来之后，用MitoZ进行组装。这样，你就可以使用尽可能多的个体A的reads了，避免当数据量过大的时候MitoZ一直运行不停止。

>但如果个体A本身的数据量就比较少的话，会导致没法“富集”到足够的线粒体reads，最终可能也难以组装出其线粒体。


Finally,

> 把前后个体A组装出来的contigs与NT库比对，看看是不是存在外源污染。
> 或者使用其它方法对个体A的所有reads进行taxonomy assignment，看看物种组成分布。


from my response to a question asked via email.

**Comment by kjg945** [comment]
好的，我再去跑，非常感谢老师




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linzhi2013/MitoZ"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月11日(星期一) 晚上7:01
收件人:&nbsp;"linzhi2013/MitoZ"<MitoZ@noreply.github.com&gt;;
抄送:&nbsp;"匡经舸"<471060224@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [linzhi2013/MitoZ] A lot of missing genes in the annotation,  in addition，they are not found during the assembly (#101)





  
您可以尝试一下multi-kmer模式。线粒体组装断裂成不同的部分的原因主要是两个：
 （1）存在Repeat，并且Repeat unit过长，kmer（或reads）无法跨越整个repeat unit；
 （2）断开的位置处的测序深度过低，其原因通常是二代建库测序过程中的偏差导致，属于平台的固有缺陷，由于这些位置中的kmer存在较低丰度，组装软件会认为这种连接不可靠从而断开。
   
通过增加Kmer的大小，也许可以跨越一些小的repeat；通过减小Kmer的大小，可以提高在DBG图中那些原来kmer丰度较低的位置的kmer丰度，从而避免组装断开。
  
from my response to a question asked via email.

**Comment by kjg945** [comment]
Dear all,
Can MitoZ extract&nbsp; mitochondrial genome from the whole genome Oxford Nanopore?&nbsp;If so, how to enter the command?


Thanks in advance,
Jingge






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "linzhi2013/MitoZ"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月11日(星期一) 晚上7:06
收件人:&nbsp;"linzhi2013/MitoZ"<MitoZ@noreply.github.com&gt;;
抄送:&nbsp;"匡经舸"<471060224@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [linzhi2013/MitoZ] A lot of missing genes in the annotation,  in addition，they are not found during the assembly (#101)





 
About mt-reads in silico enrichment
  
也许可以把个体A的reads比对到近缘个体的mitogenome上，然后把相关reads筛选出来之后，用MitoZ进行组装。这样，你就可以使用尽可能多的个体A的reads了，避免当数据量过大的时候MitoZ一直运行不停止。
   
但如果个体A本身的数据量就比较少的话，会导致没法“富集”到足够的线粒体reads，最终可能也难以组装出其线粒体。
  
Finally,
  
把前后个体A组装出来的contigs与NT库比对，看看是不是存在外源污染。
 或者使用其它方法对个体A的所有reads进行taxonomy assignment，看看物种组成分布。
  
from my response to a question asked via email.

**Comment by linzhi2013** [comment]
What did you mean  "Can MitoZ extract&nbsp; mitochondrial genome from the whole genome Oxford Nanopore?&nbsp;If so, how to enter the command?" ? 

The sentence was messed up. You can use the "Preview" function before post.

Anyway,
If you already have one mitogenome sequence and want to annotate the mitogenome, you can use the "annotate" command.

If you meant to "assemble" mitogenome sequence from ONT data, the answer is NO.

If you meant to use the "findmitoscaf" command to "extract" mitogenome sequences from ONT CCS/HiFi data (in FASTA format) (Ultra long reads have high error rate, not recommend to use for this purpose), the answer is Yes and NO:
(1) "Yes" means MitoZ can get some intermediate result files,  which contain candidate mitogenome sequences. If you are familiar with MitoZ's result files, you can use these files as a starting point.
(2) "NO" means that the ONT data don't have "abundance" information on their sequence title, so you won't get a final result file.


This is not related to the original question anymore, I'm going to close this issue. You can open new issues when necessary.

![image](https://user-images.githubusercontent.com/6203542/104310823-a734fe00-54d4-11eb-96c9-c21ed9f06fa9.png)
