### ISSUE TITLE
issues Arthropoda not find

### ISSUE THREAD

**Issue by ycuenot** [linzhi2013/MitoZ#109]
Hello,

I tried to use Mitoz to assemble and annotate Mitochondrial of fish species. I always got the same error message in the slurm of the cluster (See below). Do you have an idea? Why Arthropoda that I am not using this clade?
command lines options:
all --genetic_code auto --clade Chordata --outprefix SU18-649 --thread_number 8 --fastq1 SU18-649_ACTAAGAT-CCGCGGTT-BHWLW2DRXX_L001_R1.fastq.gz --fastq2 SU18-649_ACTAAGAT-CCGCGGTT-BHWLW2DRXX_L001_R2.fastq.gz --fastq_quality_shift --fastq_read_length 150 --fastq3 clean.1.fq.gz --fastq4 clean.2.fq.gz --duplication --adapter_mismatch 3 --adapter_length 15 --keep_region full_length_read --Ns_number 10 --low_quality 55,20 --insert_size 652 --run_mode 2 --filter_taxa_method 3 --min_abundance 10 --requiring_relax 0 --species_name Parotocinclus cf. britski

Base required: 5,000,000,000
Base got: 1,758,186,900
can not find taxid for Arthropoda
can not find taxid for ['Arthropoda'], maybe it's a misspelling.
 Please use other taxanomy name.

Thank you,
Yves

**Comment by linzhi2013** [comment]
Did you try this: https://github.com/linzhi2013/MitoZ/raw/master/how_to_search_similar_issues.png 

Don't all the related issues and answers found work for you?

**Comment by ycuenot** [comment]
Thank you. I checked already the others issues and not find an answer. Can you help me to find an issue that can help me or a direct answer? Last year, I used a lot and never get this problem. 

I use the program from a cluster. Do I have to check directly with the people of the cluster?
Thank you.
Yves

January 18, 2021 2:14:00 PM CET Guanliang MENG <notifications@github.com> wrote:

Did you try this: https://github.com/linzhi2013/MitoZ/raw/master/how_to_search_similar_issues.png
Don't all the related issues and answers found work for you?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.[{"@context": "http://schema.org","@type": "EmailMessage","potentialAction": {"@type": "ViewAction","target": "https://github.com/linzhi2013/MitoZ/issues/109#issuecomment-762242865","url": "https://github.com/linzhi2013/MitoZ/issues/109#issuecomment-762242865","name": "View Issue"},"description": "View this Issue on GitHub","publisher": {"@type": "Organization","name": "GitHub","url": "https://github.com"}}]

Yves Cuenot - Lab technician
Murienne group - DEEP team - EDB laboratory
4R1 building - Office: 140
Paul Sabatier University
118 route de Narbonne
F-31062 Toulouse cedex 9
Phone: +335.61.55.86.78

**Comment by linzhi2013** [comment]
Did you try this: https://github.com/linzhi2013/MitoZ/issues/73#issuecomment-667853168

> 
> Have you already verified if your taxonomy database is valid?
> 
> Like:
> ```python
> >>> from ete3 import NCBITaxa
> >>> a = NCBITaxa()
> >>> a.get_name_translator(["Arthropoda"])
> {'Arthropoda': [6656]}
> ```
>

**Comment by linzhi2013** [comment]
I'm closing this. you can reopen it if the method mentioned above doesn't work for you.

**Comment by ycuenot** [comment]
Thank you. It is work now.

January 21, 2021 5:20:03 PM CET Guanliang MENG <notifications@github.com> wrote:

I'm closing this. you can reopen it if the method mentioned above doesn't work for you.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.[{"@context": "http://schema.org","@type": "EmailMessage","potentialAction": {"@type": "ViewAction","target": "https://github.com/linzhi2013/MitoZ/issues/109#issuecomment-764763256","url": "https://github.com/linzhi2013/MitoZ/issues/109#issuecomment-764763256","name": "View Issue"},"description": "View this Issue on GitHub","publisher": {"@type": "Organization","name": "GitHub","url": "https://github.com"}}]

Yves Cuenot - Lab technician
Murienne group - DEEP team - EDB laboratory
4R1 building - Office: 140
Paul Sabatier University
118 route de Narbonne
F-31062 Toulouse cedex 9
Phone: +335.61.55.86.78
