### ISSUE TITLE
understanding visualization of the mitochondrial genome

### ISSUE THREAD

**Issue by Grelot** [linzhi2013/MitoZ#11]
Hi Linzhi,

MitoZ worked well and i got a visualization as output. I checked briefly your article but didn't find an explanation of the figure 4 Demonstration of mitogenome visualization using MitoZ.

https://www.biorxiv.org/content/10.1101/489955v1.full

Especially the stats inside the circle and also the color of each gene (red, blue, orange...)

Can you explain me the contents of this figure ?

**Comment by comery** [comment]
Hi Grelot,
Sorry that I have not explained it before.
There are three circles in this figure, where the innermost one shows the GC content, which is calculated based on a window-sliding method. For the middle circle, that reveals the depth distribution, with dark green for the outline. If the depth lower than the minimum value (default 20), it turns red, whereas if the depth larger than upper quartile, it turns dark green as same with the outline. And for the outermost circle, it obviously shows the gene features, orange for rRNA, red for tRNA, and blue for CDS. by the way, you can define the color of feature by yourself. 
Hope I it say clearly.

**Comment by Grelot** [comment]
Thanks a lot comery, it's clear !
