### ISSUE TITLE
[tbl2asn] This copy of tbl2asn is more than a year old. Please download the current version

### ISSUE THREAD

**Issue by QindongTang** [linzhi2013/MitoZ#113]
Hi I was trying to run multi-Kmer mode after all2 but had error as following:
`[tbl2asn] This copy of tbl2asn is more than a year old.  Please download the current version.
[tbl2asn] SeqID lcl|work71_C368266 is present on multiple Bioseqs in record
2021-03-05 16:53:56
/storage/home/tang/software/Miniconda3/ENTER/envs/mitozEnv/bin/python3 /storage/projects/Riparia/softwares/mitoz/release_MitoZ_v2.3/bin/common/genbank_gene_stat_v2.py kmer_mitoscaf.fa.gbf kmer.most_related_species.txt all2 > summary.txt

Traceback (most recent call last):
  File "/storage/projects/Riparia/softwares/mitoz/release_MitoZ_v2.3/bin/common/genbank_gene_stat_v2.py", line 238, in <module>
    main()
  File "/storage/projects/Riparia/softwares/mitoz/release_MitoZ_v2.3/bin/common/genbank_gene_stat_v2.py", line 202, in main
    seqid_len_topology_relatedSP = get_seq_topology_and_related_sp(gbfile=gbfile, closely_related_sp_file=closely_related_sp_file)
  File "/storage/projects/Riparia/softwares/mitoz/release_MitoZ_v2.3/bin/common/genbank_gene_stat_v2.py", line 173, in get_seq_topology_and_related_sp
    for rec in SeqIO.parse(gbfile, 'gb'):
  File "/storage/home/tang/software/Miniconda3/ENTER/envs/mitozEnv/lib/python3.6/site-packages/Bio/SeqIO/__init__.py", line 607, in parse
    return iterator_generator(handle)
  File "/storage/home/tang/software/Miniconda3/ENTER/envs/mitozEnv/lib/python3.6/site-packages/Bio/SeqIO/InsdcIO.py", line 93, in __init__
    super().__init__(source, mode="t", fmt="GenBank")
  File "/storage/home/tang/software/Miniconda3/ENTER/envs/mitozEnv/lib/python3.6/site-packages/Bio/SeqIO/Interfaces.py", line 47, in __init__
    self.stream = open(source, "r" + mode)
FileNotFoundError: [Errno 2] No such file or directory: 'kmer_mitoscaf.fa.gbf'
Error occured when running command:
/storage/home/tang/software/Miniconda3/ENTER/envs/mitozEnv/bin/python3 /storage/projects/Riparia/softwares/mitoz/release_MitoZ_v2.3/bin/common/genbank_gene_stat_v2.py kmer_mitoscaf.fa.gbf kmer.most_related_species.txt all2 > summary.txt`

my code as following:
>python3 /storage/projects/Riparia/softwares/mitoz/release_MitoZ_v2.3/MitoZ.py all2 --genetic_code 2 --clade Chordata --outprefix kmer \
--thread_number 12 \
--fastq1 /storage/projects/Riparia/mt_genome_assembly/Rdfyb6_zebra/Rdfyb6_zebra_unmapped_fq_clean.cleandata/clean.Rdfyb6_zebra_unmapped.R1.gz \
--fastq2 /storage/projects/Riparia/mt_genome_assembly/Rdfyb6_zebra/Rdfyb6_zebra_unmapped_fq_clean.cleandata/clean.Rdfyb6_zebra_unmapped.R2.gz \
--fastq_read_length 137 --insert_size 250 \
--run_mode 3 \
--filter_taxa_method 1 \
--requiring_taxa 'Chordata' \
--quick_mode_seq_file work71.hmmout.fa \
--quick_mode_fa_genes_file quick_mode_fa_genes.txt  \
--missing_PCGs ND4L ND5 ND6 tRNA-His tRNA-Leu tRNA-Ser \
--quick_mode_score_file work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted \
--quick_mode_prior_seq_file work71.hmmtblout.besthit.sim.filtered.fa

I couldn't find what caused the problem and which step generate the gbf file in the log file. Thanks for reply!

**Comment by linzhi2013** [comment]
Probably it was because `[tbl2asn] This copy of tbl2asn is more than a year old. Please download the current version.`.  This program is from NCBI, and I knew that if this message is printed out, then the program will NOT run and just exit.

You can enter the `mitozEnv` environment first, for example
```
$ source activate mitozEnv 
```

then update the `tbl2asn` program by:
```
$ conda update tbl2asn
```
