### ISSUE TITLE
Error: Can not find work71.scafSeq

### ISSUE THREAD

**Issue by Liuyixiao-1** [linzhi2013/MitoZ#115]
Dear Dr.Meng,
Hi, I have installed the MitoZ v2.4-alpha from source code  and I used the mitozEnv.yaml  to create the environment. However, when I tried to run the test(test.1.fq.gz, test.2.fq.gz) , an error occurred as below(Can not find work71.scafSeq) which is really confused  me. I want to know why the program didn't generate work71.scafSeq.
![image](https://user-images.githubusercontent.com/73471579/111948375-04bf7980-8b1a-11eb-9582-0353f5b04022.png)
PS: I tried the udocker version(v2.3) first but it not work. m.err showed that there was an error while extracting image layer.

**Comment by linzhi2013** [comment]
"Can not find work71.scafSeq" means the assembly step was not good.

Could you please show us the content of `test.assembly` directory with `ls -lshrt` command. thanks!

**Comment by Liuyixiao-1** [comment]
> "Can not find work71.scafSeq" means the assembly step was not good.
> 
> Could you please show us the content of `test.assembly` directory with `ls -lshrt` command. thanks!




> "Can not find work71.scafSeq" means the assembly step was not good.
> 
> Could you please show us the content of `test.assembly` directory with `ls -lshrt` command. thanks!

Here is the result：
![image](https://user-images.githubusercontent.com/73471579/112074093-6cc09f00-8bb0-11eb-9307-90818d6b3351.png)
P.S：Does MitoZ need SOAPdenovo2 to run？It seems that the command 'pregreaph' was not successfully executed.Thank you for your answer！

**Comment by linzhi2013** [comment]
1. check if the content of the file `work71.soaptrans.lib`, and then check the content of the two Fastq files. I am not sure if this was caused by the MitoZ version you used. (you may try v2.3 as recommended)

2. if the content of the two Fastq files are fine, then you can run the following command alone:
![image](https://user-images.githubusercontent.com/6203542/112130202-88d03a80-8bc8-11eb-9772-9e03552b3574.png)

and show us what will happen.

**Comment by Liuyixiao-1** [comment]
Thank you for your patient answer. I have installed the v2.3 again，but it still showed the same error.
Here is the result:
![image](https://user-images.githubusercontent.com/73471579/112131230-52181580-8c04-11eb-9a78-a8ef09c470f0.png)
work71.soaptrans.lib：
![image](https://user-images.githubusercontent.com/73471579/112130991-01082180-8c04-11eb-966b-d02466c085b9.png)
test.1.fq:
![image](https://user-images.githubusercontent.com/73471579/112131493-94415700-8c04-11eb-8013-2b98b275ee7e.png)
test.2.fq:
![image](https://user-images.githubusercontent.com/73471579/112131617-b044f880-8c04-11eb-8acf-ede2c97d7e57.png)
When I ran the command, nothing happened.
![image](https://user-images.githubusercontent.com/73471579/112132067-29dce680-8c05-11eb-9b01-20b226e6bcd1.png)

**Comment by linzhi2013** [comment]
That's weird. What about just run the `mitoAssemble` command without the parameters:
```
$ /path/to/mitoAssemble

```

**Comment by Liuyixiao-1** [comment]
Thank you for your help, the problem has been solved.We found that `mitoAssemble` didn't work properly due to a permission issue when using `tar` command. 
![image](https://user-images.githubusercontent.com/73471579/112247319-11b1a980-8c8f-11eb-9c33-29a5b0ba8213.png)

**Comment by linzhi2013** [comment]
Glad that you've figured it out!
