### ISSUE TITLE
The input FASTQ file could not be found

### ISSUE THREAD

**Issue by Guogers** [linzhi2013/MitoZ#117]
![image](https://user-images.githubusercontent.com/82870291/115361694-647d7300-a1f3-11eb-86dc-d68d8ed4fe2d.png)
Hi,
I have some problems when I run Mitoz.
As shown in the figure, I have entered the path to the FASTQ file (I have checked the path for correctness), but the prompt says that the file cannot be found.

**Comment by linzhi2013** [comment]
Hello,

You can try to use the command-line to parse parameter settings, not the configure file. 


Cheers
