### ISSUE TITLE
gc content line interpretation

### ISSUE THREAD

**Issue by paul-bio** [linzhi2013/MitoZ#118]
![image](https://user-images.githubusercontent.com/73869977/117754695-d0348800-b255-11eb-8c95-def4f03d0f32.png)

Hi. I have a problem when interpretating result.

In the picture i changed gc content from histogram to line.
I couldn't find what this red line indicate.
Can you tell?

Thanks.

**Comment by comery** [comment]
hi Paul,

This line presents that the GC content is 0.5, and each black line is 0.05. You can infer from the script "release_MitoZ_v2.4-alpha/bin/visualize/draw_circos_for_mitogenome_auto_depth.pl"

<img width="338" alt="issue_gc_content" src="https://user-images.githubusercontent.com/8231694/121644770-04ee6600-cac6-11eb-8b15-4a43947c5c68.png">


best wishes,
chentao

**Comment by linzhi2013** [comment]
> hi Paul,
> 
> This line presents that the GC content is 0.5, and each black line is 0.05. You can infer from the script "release_MitoZ_v2.4-alpha/bin/visualize/draw_circos_for_mitogenome_auto_depth.pl"
> 
> <img alt="issue_gc_content" width="338" src="https://user-images.githubusercontent.com/8231694/121644770-04ee6600-cac6-11eb-8b15-4a43947c5c68.png">
> 
> best wishes, chentao

this information is now integrated into Mitoz 3.0.

```
mitoz visualize -h
```

<img width="921" alt="image" src="https://user-images.githubusercontent.com/6203542/166426471-9724b0d8-7bb9-4512-a46a-4f5380720d62.png">
