### ISSUE TITLE
Singularity build - bad cleaning of /tmp/*

### ISSUE THREAD

**Issue by pmitev** [linzhi2013/MitoZ#119]
The Singularity build recipe contains deletes all files in `/tmp/*` on line 24 in https://github.com/linzhi2013/MitoZ/blob/master/version_2.3/Singularity.v2.3  

The physicals `/tmp` is mounted to the `/tmp` container and the `rm` happens as root - as result I better reboot the machine now.

**Comment by linzhi2013** [comment]
Hi pmitev, 

Sorry to hear about this. I did not have this problem...

I just checked the singularity, now they mount the following system (host) paths to the container:

https://sylabs.io/guides/3.1/user-guide/bind_paths_and_mounts.html
> $HOME , /sys:/sys , /proc:/proc, /tmp:/tmp, /var/tmp:/var/tmp, /etc/resolv.conf:/etc/resolv.conf, /etc/passwd:/etc/passwd, and $PWD

**Comment by pmitev** [comment]
... and since build is running with sudo $HOME is mounting /root ... ;-)
I survived (at least the computer is up and running after the reboot)

Cheers!
