### ISSUE TITLE
not creating 'mitoscaf.fa.gb' file

### ISSUE THREAD

**Issue by tcv34** [linzhi2013/MitoZ#12]
Hi,
Im encountering an error when running the MitoZ.py all command. The assembly and annotation run fine until about 2 hours in when I get the following error:

FileNotFoundError: [Errno 2] No such file or directory: '/home/jonas/anaconda3/envs/mitozEnv/release_MitoZ_v2.4-alpha/K_lyco_mito/**K_lyco_mitoscaf.fa.gbf**'
Error occured when running command:
/home/jonas/anaconda3/envs/mitozEnv/bin/python3 /home/jonas/anaconda3/envs/mitozEnv/release_MitoZ_v2.4-alpha/bin/common/genbank_gene_stat_v2.py /home/jonas/anaconda3/envs/mitozEnv/release_MitoZ_v2.4-alpha/K_lyco_mito/K_lyco_mitoscaf.fa.gbf /home/jonas/anaconda3/envs/mitozEnv/release_MitoZ_v2.4-alpha/K_lyco_mito/K_lyco.most_related_species.txt all > summary.txt

I cant find the .gbf file anywhere on my system and I can't find the command that makes it in any of the python scripts. As it makes all the files up to this point I'm thinking I can create the .gbf file manually with UGENE and place it in the appropriate directory. Does anyone know why that file isn't being created or have any suggestions for me? Thanks! I'm running on Ubuntu v18. The following is the input command for MitoZ:

python3 MitoZ.py all --genetic_code 5 --clade Arthropoda --outprefix ~/anaconda3/envs/mitozEnv/release_MitoZ_v2.4-alpha/K_lyco_mito/K_lyco --thread_number 30 --fastq1 ~/anaconda3/envs/mitozEnv/release_MitoZ_v2.4-alpha/K_lyco_mito/K_lycopersicella_1.1.fastq --fastq2 ~/anaconda3/envs/mitozEnv/release_MitoZ_v2.4-alpha/K_lyco_mito/K_lycopersicella_1.2.fastq --fastq_read_length 150 --insert_size 250  --run_mode 2 --filter_taxa_method 1 --requiring_taxa 'Arthropoda'

**Comment by linzhi2013** [comment]
> Hi,
> Im encountering an error when running the MitoZ.py all command. The assembly and annotation run fine until about 2 hours in when I get the following error:
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/home/jonas/anaconda3/envs/mitozEnv/release_MitoZ_v2.4-alpha/K_lyco_mito/**K_lyco_mitoscaf.fa.gbf**'
> Error occured when running command:
> /home/jonas/anaconda3/envs/mitozEnv/bin/python3 /home/jonas/anaconda3/envs/mitozEnv/release_MitoZ_v2.4-alpha/bin/common/genbank_gene_stat_v2.py /home/jonas/anaconda3/envs/mitozEnv/release_MitoZ_v2.4-alpha/K_lyco_mito/K_lyco_mitoscaf.fa.gbf /home/jonas/anaconda3/envs/mitozEnv/release_MitoZ_v2.4-alpha/K_lyco_mito/K_lyco.most_related_species.txt all > summary.txt
> 
> I cant find the .gbf file anywhere on my system and I can't find the command that makes it in any of the python scripts. As it makes all the files up to this point I'm thinking I can create the .gbf file manually with UGENE and place it in the appropriate directory. Does anyone know why that file isn't being created or have any suggestions for me? Thanks! I'm running on Ubuntu v18. The following is the input command for MitoZ:
> 
> python3 MitoZ.py all --genetic_code 5 --clade Arthropoda --outprefix ~/anaconda3/envs/mitozEnv/release_MitoZ_v2.4-alpha/K_lyco_mito/K_lyco --thread_number 30 --fastq1 ~/anaconda3/envs/mitozEnv/release_MitoZ_v2.4-alpha/K_lyco_mito/K_lycopersicella_1.1.fastq --fastq2 ~/anaconda3/envs/mitozEnv/release_MitoZ_v2.4-alpha/K_lyco_mito/K_lycopersicella_1.2.fastq --fastq_read_length 150 --insert_size 250 --run_mode 2 --filter_taxa_method 1 --requiring_taxa 'Arthropoda'

Hi tcv34,

Not sure what was wrong there. but your command looks wired:

 ``` --outprefix ~/anaconda3/envs/mitozEnv/release_MitoZ_v2.4-alpha/K_lyco_mito/K_lyco ```

The value of `--outprefix` should be a string, e.g `--outprefix test`, not a path.

**Comment by tcv34** [comment]
Thanks linzhi2013! That resolved the issue.
