### ISSUE TITLE
Killed Error - when running mitoAssemble all

### ISSUE THREAD

**Issue by JamesHowie14** [linzhi2013/MitoZ#122]
Hi, 

First I want to say thanks for this great software, which I have enjoyed using up till now with no issues.

I now have an issue I can’t resolve. 
It is related to #65 and #90, but is not resolved by either of these.

In short, I ran the following script:

```
singularity exec -B /home /home/jhowie/MitoZ.simg \
/app/anaconda/bin/python3 /app/release_MitoZ_v2.3/MitoZ.py all \
--genetic_code 5 \
--clade Arthropoda \
--insert_size 300 \
--thread_number 24 \
--fastq1 /home/jhowie/001_Analysis/003_MitoZ_Genomes/003_Individual/H27VJBCXX_2_5nf_1.fastq.gz \
--fastq2 /home/jhowie/001_Analysis/003_MitoZ_Genomes/003_Individual/H27VJBCXX_2_5nf_2.fastq.gz \
--outprefix Cacopsylla_melanoneura_Cmel1 \
--fastq_read_length 251 \
--run_mode 2 \
--filter_taxa_method 1 \
--requiring_taxa 'Arthropoda' \
--species_name Cacopsylla_melanoneura \
1>m.log 2>m.err
```

From this, I get the error:
```
Error: Killed
Error occured when running command:
/app/release_MitoZ_v2.3/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 24
```

MitoZ completes filtering but fails in mitoassemble.

At first I thought the reason could be memory as the fastq are quite large, about 7GB. However, I ran the code on similar sized files yesterday with no issue, and I have 125GB of RAM. 
In case of use, I decided to watch memory usage on Top, as the job errors after 10 minutes, so I could watch the whole time. Most the time is has MiM total = 128767, used = 80583, so 63%. Before the crash it jumps to 0 then 100% then dies.

A few things I checked:
I re-ran the command using all2 and using the clean fastq as input, but I get the same error.
I checked the fastq, they are not empty, either for the raw or clean ones; both look fine.
In issue #90 you mentioned to make sure files were in the right directory, and my fastq appear to be in the right place.
I also tried running with 12 threads instead of 24, but I obtained the same error, both from the raw and the clean fastq.
I checked the m.err, m.log, work71.soaptrans.lib; looks OK, but I've attached these in case you can see something I missed.

[work71.soaptrans.lib.txt](https://github.com/linzhi2013/MitoZ/files/6576046/work71.soaptrans.lib.txt)
[m.log](https://github.com/linzhi2013/MitoZ/files/6576047/m.log)
[m.err.txt](https://github.com/linzhi2013/MitoZ/files/6576048/m.err.txt)

What is even stranger is, I ran this code this morning on a sister dataset of the same size. That worked fine. The original code that worked is below. As you can see, it uses the dollar version of the notation, it used insert_size 680 and names Cmel4 in outprefix [both accidental hangovers from prior work, but as it worked I thought I show it below]. Given this, I tried to re-run the new code but deliberately setting insert_size to 680, but that still errors. Even stranger is that if I now re-run the exact code that worked before it now also produces the same error, even though it worked fine only yesterday.

```
fq1=/home/jhowie/001_Analysis/003_MitoZ_Genomes/003_Individual/H27VJBCXX_1_5nf_1.fastq.gz
fq2=/home/jhowie/001_Analysis/003_MitoZ_Genomes/003_Individual/H27VJBCXX_1_5nf_2.fastq.gz
outprefix=Cacopsylla_melanoneura_Cmel4

singularity exec -B /home /home/jhowie/MitoZ.simg \
/app/anaconda/bin/python3 /app/release_MitoZ_v2.3/MitoZ.py all \
--genetic_code 5 \
--clade Arthropoda \
--insert_size 680 \
--thread_number 24 \
--fastq1 $fq1 \
--fastq2 $fq2 \
--outprefix $outprefix \
--fastq_read_length 251 \
--run_mode 2 \
--filter_taxa_method 1 \
--requiring_taxa 'Arthropoda' \
--species_name Cacopsylla_melanoneura \
1>m.log 2>m.err
```

Again, it is kind of odd, because the above code did actually work before, but now all versions just make this error. 

Do you have any ideas what might be going on?
Any help very much appreciated!

Thanks,
James

**Comment by JamesHowie14** [comment]
Ah, sorry. I now found issue #16, and a couple of other earlier issues. I still don't know why the code worked on the files and now doesn't, but after using your file reduction tool it most of it runs, though I now get a new error:

makeblastdb -in work71.hmmtblout.besthit.sim.fa -dbtype nucl
run the tblastn shell file

I will try to resolve that and make a new issue if I fail. Cheers, James

**Comment by JamesHowie14** [comment]
Hi, final issue also resolved; feel free to close this issue ;) Cheers, JH

**Comment by linzhi2013** [comment]
Dear James,

sorry for my late reply. Good to know you figure it out！And thanks for posting so many details.

Cheers!
