### ISSUE TITLE
Plot Annotations of Additional Features in MitoZ visualize D-loop rep-origin

### ISSUE THREAD

**Issue by JamesHowie14** [linzhi2013/MitoZ#123]
Hi again! 

OK, I am not sure this really counts as an “issue”, but it would be of interest to me and could be cool for others too.

In short, I wonder if you could direct me how to access and edit the underlying code in the visualize module so it would pick out 2 additional feature classes and plot them on the circos plot in different colours to the CDS, rRNA, and tRNA.

The feature classes are: D-loop and rep-origin.

The reason I have these:
I assembled, annotated and visualised a genome in MitoZ. I noticed that a couple of tRNA genes were missed. So, I took the species.fasta, fed it into MITOS-2 and obtained a further more complete annotation, including the missed tRNA and also now including a D-loop [control region] and rep-origin [location of L strand replication initiation]. 

From this, I took the MitoZ .fasta, this new MITO-S .tbl, and the NCBI template and ran tbl2asn to obtain a new .gbf

Here is a snip from my .gbf so you can see what I mean
```
FEATURES             Location/Qualifiers
     source          1..14882
                     /organism="Cacaopsylla melanoneura"
                     /mol_type="genomic DNA"
     D-loop          69..305
                     /note="control region"
     rep_origin      346..381
                     /note="origin of L-strand replication"
     gene            495..1242
                     /gene="s-rRNA"
     rRNA            495..1242
                     /gene="s-rRNA"
                     /product="12S ribosomal RNA"
     gene            1244..1306
                     /gene="trnV(tac)"
     tRNA            1244..1306
                     /gene="trnV(tac)"
   
```

Now that I have these features I would like to plot them. 
I already did a basic try in MitoZ visualize module. It plots it all CDS, rRNA, tRNA perfectly, but misses the new classes.

If I want to force it, I can just change the class names to "gene" with either rRNA [or CDS or tRNA]. E.G.:

```
D-loop          69..305
                     /note="control region"
```
becomes:

```
gene          69..305
                     /gene="D-Loop"
rRNA          69..305
                     /gene="D-Loop"
```

That allows me to plot the circos plot with the D-loop annotated in the right place.
But then the colour is the same as CDS rRNA or tRNA [in this example the rRNA colour].

Hence, the question:

Is there a way to get MitoZ to plot additional categories for the circos plots, ideally in different colours?

For instance, I wondered if there is a way to “enter” the raw code of the visualise module in vim and edit a line somewhere to tell the module to look for "D-loop" and plot in colour x [blue] and rep_origin and plot in colour y [pink].

If you could direct me how to do that I would be very thankful! 

Thanks, 
James

**Comment by JamesHowie14** [comment]
Hi - OK, I think I made some progress. As far as I can tell, I think the edits must be inside the MitoZ_visualize.py and draw_circos_for_mitogenome_auto_depth.pl scripts.

I accessed these as follows:

```
singularity shell /home/jhowie/MitoZ.simg
cd /app/release_MitoZ_v2.3/bin/visualize
```

As far as I can tell the MitoZ_visualize.py [scriptA] is to make a configuration file for the draw_circos_for_mitogenome_auto_depth.pl script [scriptB].]

If I view scriptA I can see a section with:

```
# color setting
    color_group = parser.add_argument_group('Color setting')

    color_group.add_argument('--cds_color',
        metavar='<str>',
        default='141,211,199',
        help='PCG color [%(default)s]')

    color_group.add_argument('--trna_color',
        metavar='<str>',
        default='251,128,114',
        help='tRNA color [%(default)s]')

    color_group.add_argument('--rrna_color',
        metavar='<str>',
        default='253,192,134',
        help='rRNA color [%(default)s]')

    color_group.add_argument('--label_color',
        metavar='<str>',
        default='black',
        help="gene name label color [%(default)s]")

    color_group.add_argument('--locus_color',
        metavar='<str>',
        default='black',
        help="locus name's clolor showed on center of circle [%(default)s]")
```

I figure part of the edit would be to add something like:

```
color_group.add_argument('—controlRegion_color',
        metavar='<str>',
        default=‘blue’,
        help='controlRegion color [%(default)s]')
```

But I think you have to also edit the optional arguments for samtools also in similar manner.

Then I suppose one can enter scriptB and roll down to the line 

```
# get cds rRNA tRNA's location and strand information
```

After this comes a load of script which seems to do with the CDS, tRNA and rRNA visualisation; especially with extracting from the GenBank file.
That in itself means, I think, that one has to edit the GenBank file, or these scripts, to make additional entry types accessible to be plotted.

But as there seem to be several steps I’d still appreciate any help if there is an easier way to achieve and also to reduce the chance I try to edit and screw up the code ;) 

Thanks, 
James

**Comment by comery** [comment]
Hi James,

Thank you for opening this issue here and giving a good suggestion.  MitoZ was designed to annotate the typical gene features, such as coding genes, tRNA, and rRNA. Due to the NGS shotgun read is not powerful enough to solve the assembly of repeat region (i.e. D-loop), D-loop seems difficult to assemble well. However, since long-read sequencing is getting more popular, we think it will become easier, and we will update our codes to meet this need.

before we completely update MitoZ version, you can draw additional feature as you like by following two ways:

1, if you still keep the tmp folder where you run Mitoz, you can find the folder like "XXX.tmp/XXX.annotation/visualization", in this directory, you need to add the gene name text and color profile to two files, "circos.gene.text.txt" and "circos.features.txt".

add D-loop region to "circos.gene.text.txt":
```text
mt1	69	305	D-loop
mt1	78864	80284	l-rRNA
mt1	80324	81180	ND1
mt1	83821	84032	ND4L
mt1	84039	85356	ND4
mt1	85391	85458	trnH(gug)
```

and add color profile to "circos.features.txt", here the color for D-loop is set as "67,162,202"
```text
mt1	69	69	fill_color=black,r0=0.965r,r1=1r
mt1	305	305	fill_color=black,r0=0.965r,r1=1r
mt1	69	305	fill_color=67,162,202,r0=0.965r,r1=1r
mt1	78864	78864	fill_color=black,r0=0.965r,r1=1r
mt1	80284	80284	fill_color=black,r0=0.965r,r1=1r
mt1	78864	80284	fill_color=253,192,134,r0=0.965r,r1=1r
mt1	80324	80324	fill_color=black,r0=0.965r,r1=1r
mt1	81180	81180	fill_color=black,r0=0.965r,r1=1r
```

then, you need to go to "XXX.tmp/XXX.annotation/", and just run circos
```shell
circos -conf visualization/circos.conf
```
all done!

2, you can use a PERL script to draw circos image separately. I have updated my scripts to accept D-loop primary tag in the GenBank file.

```
# get script form https://github.com/comery/Data-Visulization/tree/master/mito2circos/auto_depth
# this is an example
perl draw_circos_for_mitogenome_auto_depth.pl -gb ../data/SRR7174336.mitoscaf.fa.gbf -conf mitogenome.auto_depth.conf
```

best wishes,
Chentao

**Comment by JamesHowie14** [comment]
Hi Chentao, 

Thanks so much for your fast and helpful response, its very kind of you
and sincerely appreciated!  
I must apologize for my late reply. 

I was sick for quite a few days and only saw the emails on Friday.

I have since tried out both methods before replying, so I can include
any confusion in my reply ;)

#

For Method 1 [edit files and run in ciros]:

This worked out well! Thanks! It took me a few tries as I made a typo,
but works well now.
I’m very happy about that :)

#

For Method 2 [use updated perl script and config file]:

It is not so important because Method 1 works, but I was unable to get
Method 2 to work.
I would love to be able to get this method to work also, so I have tried
to explain what I've tried below in case you have any thoughts on what I
might be doing wrong. 

What did I try:

I moved the perl script and config file to my home directory.
I ran code based on your example using unedited input files as a test:


```
cd
/home/jhowie/001_Analysis/003_MitoZ_Genomes/003_Run2_Indi/tmp/Cacopsylla_melanoneura_Cmel_01.annotation

singularity shell /home/jhowie/MitoZ.simg

perl /home/jhowie/auto_depth/draw_circos_for_mitogenome_auto_depth.pl
-gb Cacopsylla_melanoneura_Cmel_01_mitoscaf.fa.gbf -conf
/home/jhowie/auto_depth/mitogenome.auto_depth.conf

```

It gives the error:

```
fastq_1 is bad file! at
/home/jhowie/auto_depth/draw_circos_for_mitogenome_auto_depth.pl line
119.
```

I think the error relates to line 119 of the perl script. But I am not
sure how to resolve it. 

I didn’t think I needed to specify a fastq_1 for this script. 
Nonetheless, just in case, I tried:

```
perl /home/jhowie/auto_depth/draw_circos_for_mitogenome_auto_depth.pl \
-gb Cacopsylla_melanoneura_Cmel_01_mitoscaf.fa.gbf \
-conf /home/jhowie/auto_depth/mitogenome.auto_depth.conf \
-fastq_1
/home/jhowie/001_Analysis/003_MitoZ_Genomes/003_Run2_Indi/cleanReduced.1.fq.gz
\
-fastq_2
/home/jhowie/001_Analysis/003_MitoZ_Genomes/003_Run2_Indi/cleanReduced.2.fq.gz
```

This recovered the same error. [fastq_1 is bad file! at
/home/jhowie/auto_depth/draw_circos_for_mitogenome_auto_depth.pl line
119.]



Finally, copied the files to my working directory and ran the script
from there:


```
cd
/home/jhowie/001_Analysis/003_MitoZ_Genomes/003_Run2_Indi/tmp/Cacopsylla_melanoneura_Cmel_01.annotation
cp /home/jhowie/auto_depth/mitogenome.auto_depth.conf .
cp /home/jhowie/auto_depth/draw_circos_for_mitogenome_auto_depth.pl .


singularity shell /home/jhowie/MitoZ.simg
perl draw_circos_for_mitogenome_auto_depth.pl -gb
Cacopsylla_melanoneura_Cmel_01_mitoscaf.fa.gbf -conf
mitogenome.auto_depth.conf
```

But I got the same error again.



#

Do you have any idea why this might be?
 I can’t think of anything else except *maybe* going into MitoZ and 
switching the old modules for your new modules and running it through 
the MitoZ package. 


But as directly running the perl script works for you I assume I've done
something wrong, so I wondered if you had any idea what that might be or
how to fix it? 

In case of use, the circos version in the container = circos | v 0.69-6
| 31 July 2017 | Perl 5.026002

#

Again thanks *so much* for your help, and sorry again about taking a
while to reply.

Best wishes, 
James 

P.S.

Its really cool that you are updating MitoZ to facilitate long-reads. I
will have long reads soon so I’d be very interested to try out the new
version once it is ready.
Do you know when you plan to finish/release the long-read version, so I
can keep my eye out ;)


P.P.S. 


Hehe, yeah, I searched around a bit and found your GitHub repository,
which is cool and which I was pleased to find it :) 




>>> comery ***@***.***> 06/10/21 3:55 PM >>>

 Hi James,
 Thank you for opening this issue here and giving a good suggestion. 
MitoZ was designed to annotate the typical gene features, such as coding
genes, tRNA, and rRNA. Due to the NGS shotgun read is not powerful
egetting more popular, we think it will become easier, and we will update
our codes to meet this need.
 before we completely update MitoZ version, you can draw additional
feature as you like by following two ways:
 1, if you still keep the tmp folder where you run Mitoz, you can find
the folder like "XXX.tmp/XXX.annotation/visualization", in this
directory, you need to add the gene name text and color profile to two
files, "circos.gene.text.txt" and "circos.features.txt".
 add D-loop region to "circos.gene.text.txt":

mt169305D-loopmt17886480284l-rRNAmt18032481180ND1mt18382184032ND4Lmt18403985356ND4mt18539185458trnH(gug)and
add color profile to "circos.features.txt", here the color for D-loop is
set as "67,162,202"
mt16969fill_color=black,r0=0.965r,r1=1rmt1305305fill_color=black,r0=0.965r,r1=1rmt169305fill_color=67,162,202,r0=0.965r,r1=1rmt17886478864fill_color=black,r0=0.965r,r1=1rmt18028480284fill_color=black,r0=0.965r,r1=1rmt17886480284fill_color=253,192,134,r0=0.965r,r1=1rmt18032480324fill_color=black,r0=0.965r,r1=1rmt18118081180fill_color=black,r0=0.965r,r1=1rthen,
you need to go to "XXX.tmp/XXX.annotation/", and just run circos
circos -conf visualization/circos.conf
all done!
2, you can use a PERL script to draw circos image separately. I have
updated my scripts to accept D-loop primary tag in the GenBank file.
# get script form
https://github.com/comery/Data-Visulization/tree/master/mito2circos/auto_depth#
this is an exampleperl draw_circos_for_mitogenome_auto_depth.pl -gb
../data/SRR7174336.mitoscaf.fa.gbf -conf mitogenome.auto_depth.conf best
wishes,
 Chentao

**Comment by comery** [comment]
Hi James,

I am afraid that you made a simple mistake. 

The script "draw_circos_for_mitogenome_auto_depth.pl " doesn't have the parameters of "-fastq_1" and "-fastq_2". It can only accept a "Genbank file" specified by "-gb" and a configure file specified by "-conf". Then the "fastq information" can be included in the configure file. You can run "perl draw_circos_for_mitogenome_auto_depth.pl" without parameters to check out its help information.

it looks like:
![image](https://user-images.githubusercontent.com/8231694/123747900-19b06380-d8e6-11eb-8fd2-db85830212e1.png)

and the configure file looks like:
![image](https://user-images.githubusercontent.com/8231694/123747989-38aef580-d8e6-11eb-92c0-331a18c71a0a.png)


Moreover, here is the logic to determine how to use depth information, if you set "depth_file = xxx" and "run_map = yes"  in the same time, it will directly use the existing depth file; otherwise, if you set the "run_map = yes", it will retrieve the fastq file path from "fq = xxx_1.fq, xxx_2.fq", and then run bwa mapping to generate depth file.

**Comment by JamesHowie14** [comment]
Hi Chentao, 


Ah OK thanks, yeah I figured the -fastq_1 input didn't really make sense
but just tried it too in case. 

Nice, I'll have a play around with editing the configuration file and
see if I can run it ;)

Thanks for the tips :)

Cheers, 

James





>>> comery ***@***.***> 06/29/21 8:43 AM >>>

 Hi James,
 I am afraid that you made a simple mistake.
 The script "draw_circos_for_mitogenome_auto_depth.pl " doesn't have the
parameters of "-fastq_1" and "-fastq_2". It can only accept a "Genbank
file" specified by "-gb" and a configure file specified by "-conf". Then
the "fastq information" can be included in the configure file. You can
run "perl draw_circos_for_mitogenome_auto_depth.pl" without parameters
to check out its help information.
 it looks like:
 
 and the configure file looks like:
 
 Moreover, here is the logic to determine how to use depth information,
if you set "depth_file = xxx" and "run_map = yes"  in the same time, it
will directly use the existing depth file; otherwise, if you set the
"run_map = yes", it will retrieve the fastq file path from "fq =
xxx_1.fq, xxx_2.fq", and then run bwa mapping to generate depth file.

**Comment by comery** [comment]
Great!
