### ISSUE TITLE
Filter command does not run to completion

### ISSUE THREAD

**Issue by fluttercork** [linzhi2013/MitoZ#124]
Hi,

First off, thanks for a great and helpful resource! Nice work ...

I'm running the filter module on some of my raw data and it crashes before coming to completion with the error message:

/bin/sh: 1: cannot create /Users/xxx/mitozTest/Synchaeta.result/README.txt: Directory nonexistent
Error occured when running command:
/app/anaconda/bin/python3 /app/release_MitoZ_v2.3/bin/common/get_result-dir_file_intro.py /Users/xxx/mitozTest/Synchaeta.result > /Users/xxx/mitozTest/Synchaeta.result/README.txt

The basecall is:

docker run -v $PWD:$PWD -w $PWD  --rm guanliangmeng/mitoz:2.3 \
python3 /app/release_MitoZ_v2.3/MitoZ.py filter \

with all the input and output files being set properly. It doesn't matter if I run it via a shell script, directly from the command line, or with or without sudo. The result is the same.

The problem is minor insofar as I can grab the cleaned files from /tmp/Synchaeta.cleandata (so the program can create directories), but thought that you might want to chase it down anyway (or let me know what I'm doing wrong!).

Cheers,

Olaf

---

I am running mitoZ 2.3 on macOS 11.4 via Docker 20.10.6 on an older MacBook Pro (i.e., no M1 chip). I was also able to replicate the test results so the installation seems to be working.

**Comment by linzhi2013** [comment]
Dear Olaf,

You can check if there cleaned data files in the `tmp` directory. if there, then every thing is fine.

**Comment by fluttercork** [comment]
As I said, they are there so everything's good, but just thought you would like to know about it to patch it up for version 2.4.
