### ISSUE TITLE
Crash during assemble command

### ISSUE THREAD

**Issue by fluttercork** [linzhi2013/MitoZ#125]
Hi,

I'm running the all2 module on some of my cleaned data and it crashes within seconds with the error message:

Killed
Error occured when running command:
/app/release_MitoZ_v2.3/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 4

The basecall is:

docker run -v $PWD:$PWD -w $PWD  --rm guanliangmeng/mitoz:2.3 \
python3 /app/release_MitoZ_v2.3/MitoZ.py all2 \

with all the input and output files that I can see being set properly. (I modified docker.all2.sh appropriately, which runs to completion.) It doesn't matter if I run it via a shell script, directly from the command line, or with or without sudo. The result is the same.

Unfortunately, the error message is too vague to start anything with it and the log file just contains the command.

Thanks,

Olaf

---

I am running mitoZ 2.3 on macOS 11.4 via Docker 20.10.6 on an older MacBook Pro (i.e., no M1 chip). I was also able to replicate the test results so the installation seems to be working.

**Comment by Prunoideae** [comment]
Looks like an error caused from system resource shortage, could you post some parameters of your working computer, like CPU model, RAM and disk space?

**Comment by fluttercork** [comment]
Thanks for the quick reply ...

The MacBook Pro has 2.8 GHz Quad-Core Intel Core i7 with 16 GB 1600 MHz DDR3 and about 1 TB free disk space.

I also explicitly specified 4 threads.

**Comment by Prunoideae** [comment]
Sometimes the modified SOAPdenovo of MitoZ can take up to 100G RAM to assemble the data, maybe the assembler just ran out of memory.

**Comment by fluttercork** [comment]
Thanks. That does indeed appear to have been the problem. I ran the analysis on a cluster with udocker and 48 GB of RAM and it ran to completion.

If possible, it might be useful to trap this error and provide more feedback to the user, if only to save yourself more comments like this!

Thanks again!

**Comment by linzhi2013** [comment]
Usually, 50G RAM is required. mitoAssemle needs enough RAM to store kmers
