### ISSUE TITLE
a problem of running all module

### ISSUE THREAD

**Issue by user1-10** [linzhi2013/MitoZ#126]
Error occured when running command:
/home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 12
**I do not know the reason of my problem, the all module has been performed. I have tried several times to run this raw data, and this problem always occured.I will appreciate if if can help me to solve this problem. **### My input code is in the following**:** 
nohup python3 MitoZ.py all --genetic_code 5 --clade Chordata --outprefix ZZZ \
--thread_number 12 \
--fastq1 /home/uftp/YC/HS38/HS38_R1.fq.gz \
--fastq2/home/uftp/YC/HS38/HS38_R2.fq.gz \
--fastq_read_length 150 \
--insert_size 250  \
--run_mode 2 \
--filter_taxa_method 1 \
--requiring_taxa 'Chordata' &

**### and the nohup.txt oftThe process of executing  program is here:**
2021-06-23 10:28:15
/home/uftp/miniconda3/bin/python3 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/common/extractfq.py -fq1 /home/uftp/YC/HS38/HS38_R1.fq.gz -fq2 /home/uftp/YC/HS38/HS38_R2.fq.gz -outfq1 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/ZZZ.tmp/ZZZ.partial_fastq/partial.1.fq.gz -outfq2 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/ZZZ.tmp/ZZZ.partial_fastq/partial.2.fq.gz -size_required 5 -gz  -cache_num 1500000 

Base required: 5,000,000,000
Base got: 5,000,000,100
2021-06-23 12:46:15
perl /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/filter/raw_reads_filter_v0.5.pl -1 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/ZZZ.tmp/ZZZ.partial_fastq/partial.1.fq.gz -2 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/ZZZ.tmp/ZZZ.partial_fastq/partial.2.fq.gz -3 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/ZZZ.tmp/ZZZ.cleandata/clean.1.fq.gz -4 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/ZZZ.tmp/ZZZ.cleandata/clean.2.fq.gz -m 3 -l 15 -n 10 -q 55,20 -z 

input files:
	/home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/ZZZ.tmp/ZZZ.partial_fastq/partial.1.fq.gz
	/home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/ZZZ.tmp/ZZZ.partial_fastq/partial.2.fq.gz
output files:
	/home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/ZZZ.tmp/ZZZ.cleandata/clean.1.fq.gz
	/home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/ZZZ.tmp/ZZZ.cleandata/clean.2.fq.gz
filter parameters:
	k, keep only bases between BEG and END for each read: full length read
	n, the maximun N allowed in single end reads: 10
	q, the maixmum percentage of low quality (ASCII code's integer) bases allowed in single end reads: 55,20
	d, Filtering duplications: False

#raw_read_bases	duplication	is_adapter	too_many_Ns	is_low_quality	clean_read_bases	clean_read_length
5000000100	NA	0	17379000	538498800	4444122300	150
2021-06-23 13:14:45
/home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 12

mitoAssemble is based on SoapTrans v1.03 and modified to fit mitogenome assembly by BGI-ENVers

pregraph -s work71.soaptrans.lib -K 71 -p 12 -o work71 
In work71.soaptrans.lib, 1 libs, max seq len 150, max name len 256

12 thread created
read from file:
 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/ZZZ.tmp/ZZZ.cleandata/clean.1.fq.gz
read from file:
 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/ZZZ.tmp/ZZZ.cleandata/clean.2.fq.gz
Killed
/home/uftp/miniconda3/lib/python3.8/site-packages/ete3-3.1.2-py3.7.egg/ete3/evol/parser/codemlparser.py:221: SyntaxWarning: "is" with a literal. Did you mean "=="?
/home/uftp/miniconda3/lib/python3.8/site-packages/ete3-3.1.2-py3.7.egg/ete3/evol/parser/codemlparser.py:221: SyntaxWarning: "is" with a literal. Did you mean "=="?
Error occured when running command:
/home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 12

**Comment by linzhi2013** [comment]
Hello, Python 3.8 doesn't work for MitoZ. Please check https://github.com/linzhi2013/MitoZ/issues/86 .

since the error occurred in this step:
```
Error occured when running command:
/home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 12
```

You should check if the `work71.soaptrans.lib ` file is correct, if the fastq files are OK. If the fastq files are OK, then this could also be caused by not enough RAM in your server. (I noticed there is a `Killed` message in your output)

**Comment by user1-10** [comment]
> Hello, Python 3.8 doesn't work for MitoZ. Please check #86 .
> 
> since the error occurred in this step:
> 
> ```
> Error occured when running command:
> /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 12
> ```
> 
> You should check if the `work71.soaptrans.lib ` file is correct, if the fastq files are OK. If the fastq files are OK, then this could also be caused by not enough RAM in your server. (I noticed there is a `Killed` message in your output)

**Comment by user1-10** [comment]
Dear Meng,
    I have re-examined my problem, and RAM of our server is enough. And I noticed other issue have the same problem:#122  #16. I will change a server to run again.

**Comment by user1-10** [comment]
I have run the test file. and the running process was OK.
2021-06-22 17:51:08
/home/uftp/miniconda3/bin/python3 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/common/extractfq.py -fq1 /home/uftp/mitogenome-software/MitoZ/test/test.1.fq.gz -fq2 /home/uftp/mitogenome-software/MitoZ/test/test.2.fq.gz -outfq1 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/test.tmp/test.partial_fastq/partial.1.fq.gz -outfq2 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/test.tmp/test.partial_fastq/partial.2.fq.gz -size_required 5 -gz  -cache_num 1500000 

Base required: 5,000,000,000
Base got: 3,061,250
2021-06-22 17:51:12
/home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 8


mitoAssemble is based on SoapTrans v1.03 and modified to fit mitogenome assembly by BGI-ENVers

pregraph -s work71.soaptrans.lib -K 71 -p 8 -o work71 
In work71.soaptrans.lib, 1 libs, max seq len 150, max name len 256

8 thread created
read from file:
 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/test.tmp/test.partial_fastq/partial.1.fq.gz
read from file:
 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/test.tmp/test.partial_fastq/partial.2.fq.gz
time spent on hash reads: 0s, 24490 reads processed
[LIB] 0, avg_ins 250, reverse 0 
379406 nodes allocated, 1346950 kmer in reads, 1346950 kmer processed
362549 linear nodes
time spent on marking linear nodes 0s
time spent on pre-graph construction: 1s

deLowKmer 0, deLowEdge 1
Start to remove kmer of out frequency kmers < 0.100000
2901 kmers off
8 thread created
0 linear nodes
time spent on cut kmer: 0s

Start to remove tips of single frequency kmers short than 142
8241 tips off
8 thread created
324 linear nodes
Start to remove tips which don't contribute the most links
kmer set 0 done
kmer set 1 done
kmer set 2 done
kmer set 3 done
kmer set 4 done
kmer set 5 done
kmer set 6 done
kmer set 7 done
714 tips off
8 thread created
0 linear nodes
time spent on cutTipe: 0s

210 (105) edges 12 extra nodes
time spent on making edges: 1s

In file: work71.soaptrans.lib, max seq len 150, max name len 256

8 thread created
read from file:
 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/test.tmp/test.partial_fastq/partial.1.fq.gz
read from file:
 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/test.tmp/test.partial_fastq/partial.2.fq.gz
24490 reads processed
time 0,0,0,0,0,0,0
0 markers outputed
done mapping reads, 7883 reads deleted, 85 arcs created
[LIB] 0, avg_ins 250, reverse 0 
time spent on mapping reads: 0s

303 vertex outputed
overall time for lightgraph: 0m

contig -g work71 -M 3 
there're 303 kmers in vertex file
there're 210 edge in edge file
done sort
input 210 edges
124 pre-arcs loaded
start to pinch bubbles, cutoff 0.100000, MAX NODE NUM 30, MAX DIFF 10
69 startingPoints, 36 dheap nodes
0 pairs found, 0 pairs of paths compared, 0 pairs merged
sequenc compare failure: 0 0 0 0
DFibHeap: 3 Nodes allocated
a linear concatenation lap, 3 concatenated
a linear concatenation lap, 0 concatenated
204 edges in graph
time spent on bubblePinch: 0s

Start to remove the low coverage edge < 2
20 edges removed

strict 0, cutLen 142
a cutTipsInGraph lap, 70 tips cut
a cutTipsInGraph lap, 0 tips cut
4 dead arcs removed
a linear concatenation lap, 5 concatenated
a linear concatenation lap, 0 concatenated
16 edges in graph
there're 210 edges
after compacting 16 edges left

delete unlike arc :4
1 time to delete light arcs 
0 loops removed in Graph
Start to remove light arc using the rate 0.050000 and 0.020000
delete light arc :0/0

0 short contig(<48) removed 
a linear concatenation lap, 2 concatenated
a linear concatenation lap, 0 concatenated
12 edges in graph
there're 16 edges
after compacting 12 edges left

6 ctgs longer than 100, sum up 19655bp, with average length 3275
the longest is 18419bp, contig N50 is 18419 bp,contig N90 is 18419 bp
6 contigs longer than 72 output
time elapsed: 0m

map -s work71.soaptrans.lib -g work71 -p 8 -K 71 -f 
K = 71
contig len cutoff: 73

there're 6 contigs in file: work71, max seq len 18419, min seq len 133, max name len 10
time spent on parse contigs file 0s
8 thread created
time spent on hash reads: 0s
19233 nodes allocated, 19235 kmer in reads, 19235 kmer processed
time spent on De bruijn graph construction: 1s

In file: work71.soaptrans.lib, max seq len 150, max name len 256

8 thread created
12 edges in graph
read from file:
 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/test.tmp/test.partial_fastq/partial.1.fq.gz
read from file:
 /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/test.tmp/test.partial_fastq/partial.2.fq.gz
current insert size 250, map_len 32
Output 4596 out of 24490 (18.8)% reads in gaps
18307 out of 24490 (74.8)% reads mapped to contigs
1 pe insert size, the largest boundary is 24490

[LIB] 0, avg_ins 250, reverse 0 
time spent on mapping reads: 1s

overall time for alignment: 0m

scaff -g work71 -F -p 8 
there're 1 grads, 24490 reads, max read len 150
K = 71
there're 12 edge in edge file
0 arcs loaded
input 6 contigs
done loading updated edges
time spent on loading edges 0s

**Comment by user1-10** [comment]
> Hello, Python 3.8 doesn't work for MitoZ. Please check #86 .
> 
> since the error occurred in this step:
> 
> ```
> Error occured when running command:
> /home/uftp/mitogenome-software/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 12
> ```
> 
> You should check if the `work71.soaptrans.lib ` file is correct, if the fastq files are OK. If the fastq files are OK, then this could also be caused by not enough RAM in your server. (I noticed there is a `Killed` message in your output)
Dear Meng,
I have download the docker version. and the same problem has occuered again. The m.err is in the following:
Killed
Error occured when running command:
/app/release_MitoZ_v2.3/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 4

RAM of my server is enough, and I used command top to observe.  The memory is ok.
I will appreacited it if you can help me to solve it.

**Comment by linzhi2013** [comment]
Hello,

How much RAM does your server have?

Try:
Within the MitoZ docker container, go to the "tmp.assembly" directory, and run the command below:

```
/app/release_MitoZ_v2.3/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 4   1>s.log 2>s.err
 ```
and then show us the `s.log` and `s.err` files. thanks!

**Comment by user1-10** [comment]
> 
> 
> Hello,
> 
> How much RAM does your server have?
> 
> Try:
> Within the MitoZ docker container, go to the "tmp.assembly" directory, and run the command below:
> 
> ```
> /app/release_MitoZ_v2.3/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 4   1>s.log 2>s.err
> ```
> 
> and then show us the `s.log` and `s.err`, `work71.soaptrans.lib` files. thanks!
> 
> For the two fastq files (`q1` and `q2`) in the `work71.soaptrans.lib ` file, please also show us a few Fastq records, I would like to make sure the filtered fastq files have no problem.
> 
> The filter module of `all` command is quite slow, you can try to filter the raw data with other programs and then run `all2` command of MitoZ directly.

Thanks for your help! 
I have buy a new server account, and the problem has been solved.
The problem of Kill may be is the memory of the old server and RAM.

**Comment by linzhi2013** [comment]
Good to know that!
