### ISSUE TITLE
The clean reads to map mitochondrial genome

### ISSUE THREAD

**Issue by orient100** [linzhi2013/MitoZ#13]
hi,
Thanks to the author for providing mitoz, which is very convenient. But for the rigor of the article, I need to verify the accuracy of mitochondrial genome assembled with mitoz and the issue about presence of pseudogenes, so can you tell me how to get file that only include clean reads?Or which file is in the generated file. To facilitate me to see the map results through the visualization software.

**Comment by linzhi2013** [comment]
> hi,
> Thanks to the author for providing mitoz, which is very convenient. But for the rigor of the article, I need to verify the accuracy of mitochondrial genome assembled with mitoz and the issue about presence of pseudogenes, so can you tell me how to get file that only include clean reads?Or which file is in the generated file. To facilitate me to see the map results through the visualization software.

Hi Orient100,

the clean data (e.g. `ZZZ.cleandata`) is in 

```
example
    ├── tmp
    │   ├── ZZZ.annotation
    │   ├── ZZZ.assembly
    │   └── ZZZ.cleandata
```

if you can MitoZ with the `all` command.


cheers

**Comment by orient100** [comment]
Thank you very much.
