### ISSUE TITLE
Duplicate sequences in file hmmtblout.besthit.sim.fa 

### ISSUE THREAD

**Issue by dinhe878** [linzhi2013/MitoZ#130]
Hi, I have been trying to run 2.4_alpha following "conda recipe". So I execute:

`python3 ../MitoZ-master/version_2.4-alpha/release_MitoZ_v2.4-alpha/MitoZ.py all2 --config mitoz_all2_config_GAGA-0001.txt
`
The run went ok until the annotation steps:

> makeblastdb -in work71.hmmtblout.besthit.sim.fa -dbtype nucl
> run the tblastn shell file
> Run solar to conjoin HSPs and filter bad HSPs and redundance.
> preparing genewise input directories and files
> name scaffold1 is not uniq at /home/projects/ku_00039/people/dinghe/working_dr/mito_genome_assembly/MitoZ-master/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 5.
> 

> Error occured when running command:
> /home/people/dinghe/ku_00039/people/dinghe/conda/.conda/envs/mitozEnv/bin/python3 /home/projects/ku_00039/people/dinghe/working_dr/mito_genome_assembly/MitoZ-master/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/findmitoscaf/filter_taxonomy_by_CDS_annotation.py -fa work71.hmmtblout.besthit.sim.fa -MTsoft /home/projects/ku_00039/people/dinghe/working_dr/mito_genome_assembly/MitoZ-master/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl -db /home/projects/ku_00039/people/dinghe/working_dr/mito_genome_assembly/MitoZ-master/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/profiles/MT_database/Animal_CDS_protein.fa -thread 16 -genetic_code 5 -requiring_taxa 'Arthropoda' -relax 0 -WISECONFIGDIR /home/projects/ku_00039/people/dinghe/working_dr/mito_genome_assembly/MitoZ-master/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/annotate/wisecfg -outf work71.hmmtblout.besthit.sim.filtered.fa
> 

Then the following steps just fall apart, I'm guessing lacking previous supposedly generated file(s). So I checked the file "work71.hmmtblout.besthit.sim.fa" and found there are two identical sequences:

> >scaffold1 Locus_1_0 54.5 COMPLEX
> TAAATATAGTCCTTTCGTACAAATACTTACCCATTTAATTATAGATAGAAACCGATCTGGCTCACGCCGATCTAAACTCAAATCATGTAAGATTTTAAAA
> GTCGAACAGACTTAAATATTAAACTTCTACACCTAATTTTTATCTTAATTCAACATCGAGGTCGCAATCATCCTTATCTATACGATCTTTCTAAGAATAT
> TACGCTGTTATCCCTAAGGTAATTATTTCTTTCTTAATTTTAAATAAATCATTCATCAACTAATCTTCCTCTACTAATTAATATCATGTTTCCAATTAAA
> NNNNNNNNNNNNNNNNNNNNNNATTCCCACAGGTATTAAAATTTTTAGATGAATTTCTACTGTCCATGGCATAAAAGTTAACTATAACCCTCCTCCCATT
> CTATGATGATCAATAGGATTTATTTTTCTATTTTCAATGGGAAGATTTACAGGAACTTTGAAATTCTTCTATTGATATTATTCTCCATGATTACTACGTA
> GT
> >scaffold1 Locus_1_0 54.5 COMPLEX
> TAAATATAGTCCTTTCGTACAAATACTTACCCATTTAATTATAGATAGAAACCGATCTGGCTCACGCCGATCTAAACTCAAATCATGTAAGATTTTAAAA
> GTCGAACAGACTTAAATATTAAACTTCTACACCTAATTTTTATCTTAATTCAACATCGAGGTCGCAATCATCCTTATCTATACGATCTTTCTAAGAATAT
> TACGCTGTTATCCCTAAGGTAATTATTTCTTTCTTAATTTTAAATAAATCATTCATCAACTAATCTTCCTCTACTAATTAATATCATGTTTCCAATTAAA
> NNNNNNNNNNNNNNNNNNNNNNATTCCCACAGGTATTAAAATTTTTAGATGAATTTCTACTGTCCATGGCATAAAAGTTAACTATAACCCTCCTCCCATT
> CTATGATGATCAATAGGATTTATTTTTCTATTTTCAATGGGAAGATTTACAGGAACTTTGAAATTCTTCTATTGATATTATTCTCCATGATTACTACGTA
> GT
> 

I am not sure where went wrong. Any help is much appreciated!

Also, I found a bunch of duplicated sequences in the Animal_CDS_protein.fa that also interrupted the run complaining "name gi_XXXXXXX is not uniq....". Those errors disappeared after cleaning up those duplicated sequences but leads to the current (above) errors.

**Comment by linzhi2013** [comment]
the solution can be found in https://github.com/linzhi2013/MitoZ/issues/149
