### ISSUE TITLE
Annotation results are affected by numbers of threads 

### ISSUE THREAD

**Issue by dinhe878** [linzhi2013/MitoZ#131]
Hi,

Not sure how to report this but I've observed a pattern of using annotate function, in that the resulting annotation is affected by the number of threads used. The more threads are used seems to result less gene were annotated. I didn't test this pattern thoroughly but saw relevant issue posted here. Currently I only use one thread for all my annotation and so far it works much better.

If there's some strange behavior in the annotation processes due to parallelization, I wonder if it's possible to disable only the annotation steps in all/all2 pipeline so other unaffected (from parallelization) processes can still take advantage of multi-threading speedup without sacrificing the annotation performance.

Just a thought. /Ding

**Comment by linzhi2013** [comment]
Hi Ding,

That sounds weird to me. Could you please provide us with more information? For example, 
1. Which version of MitoZ are you using? How did you install it?
2. What are the configuration of your server? E.g. Windows, CentOS, RAM.
3. How did you do the analysis? For example, to perform gene annotation with the `annotate` command alone or use the `all` / `all2` commands?
4. Is your mitogenome circular or fragmented? 
5. What genes are affected, e.g. PCGs, rRNA, or tRNA?

For now, my guess is similar to this https://github.com/linzhi2013/MitoZ/issues/131.
