### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jingxuan1005** [linzhi2013/MitoZ#132]
Hi, I am getting this error for my run using MitoZ recently. This is the nohup. out. The program will automatically exit after running for an hour. 
perl /home/jingxuan/release_MitoZ_v2.4-alpha/bin/filter/raw_reads_filter_v0.5.pl -1 /home/jingxuan/release_MitoZ_v2.4-alpha/C131.tmp/C131.partial_fastq/partial.1.fq.gz -2 /home/jingxuan/release_MitoZ_v2.4-alpha/C131.tmp/C131.partial_fastq/partial.2.fq.gz -3 /home/jingxuan/release_MitoZ_v2.4-alpha/C131.tmp/C131.cleandata/clean.1.fq.gz -4 /home/jingxuan/release_MitoZ_v2.4-alpha/C131.tmp/C131.cleandata/clean.2.fq.gz -m 3 -l 15 -n 10 -q 55,20 -z 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x83cd35]

goroutine 1 [running]:
github.com/ActiveState/cli/internal/locale.T(0x14b0a58, 0x15, 0x0, 0x0, 0x0, 0x1650400, 0x8)
	/home/runner/work/cli/cli/internal/locale/locale.go:119 +0x55
github.com/ActiveState/cli/internal/language.init()
	/home/runner/work/cli/cli/internal/language/language.go:69 +0x47
Error occured when running command:
perl /home/jingxuan/release_MitoZ_v2.4-alpha/bin/filter/raw_reads_filter_v0.5.pl -1 /home/jingxuan/release_MitoZ_v2.4-alpha/C131.tmp/C131.partial_fastq/partial.1.fq.gz -2 /home/jingxuan/release_MitoZ_v2.4-alpha/C131.tmp/C131.partial_fastq/partial.2.fq.gz -3 /home/jingxuan/release_MitoZ_v2.4-alpha/C131.tmp/C131.cleandata/clean.1.fq.gz -4 /home/jingxuan/release_MitoZ_v2.4-alpha/C131.tmp/C131.cleandata/clean.2.fq.gz -m 3 -l 15 -n 10 -q 55,20 -z

**Comment by linzhi2013** [comment]
Not sure if it was caused by the platform or RAM limit.

MitoZ v2.3 is preferred.

Maybe you need to rebuild your mitozEnv.

If you're running MitoZ on WSL, please beware that it would probably not work.
