### ISSUE TITLE
An problem of annonation

### ISSUE THREAD

**Issue by user1-10** [linzhi2013/MitoZ#133]
Hi!
I have a problem about the annonation. The error was listed as follows:
makeblastdb -in /lustre/home/acct-ioozds/ioozds/yc/data/test_mitoscaf.fa -dbtype nucl
run the tblastn shell file
Run solar to conjoin HSPs and filter bad HSPs and redundance.
preparing genewise input directories and files
name gi_NC_009093_ATP6_Galendromus_occidentalis_222_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/MitoZ_v2.3/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 1163.
name gi_NC_009093_ATP8_Galendromus_occidentalis_53_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/MitoZ_v2.3/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 4737.
name gi_NC_009093_COX1_Galendromus_occidentalis_517_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/MitoZ_v2.3/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 7701.
name gi_NC_009093_COX2_Galendromus_occidentalis_221_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/MitoZ_v2.3/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 10455.
name gi_NC_009093_COX3_Galendromus_occidentalis_275_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/MitoZ_v2.3/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 14025.
name gi_NC_009093_CYTB_Galendromus_occidentalis_357_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/MitoZ_v2.3/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 17589.
name gi_NC_009093_ND1_Galendromus_occidentalis_270_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/MitoZ_v2.3/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 21171.
name gi_NC_009093_ND4_Galendromus_occidentalis_437_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/MitoZ_v2.3/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 31847.
name gi_NC_009093_ND4L_Galendromus_occidentalis_89_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/MitoZ_v2.3/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 35423.
name gi_NC_009093_ND5_Galendromus_occidentalis_560_aa is not uniq at /lustre/home/acct-ioozds/ioozds/yc/MitoZ_v2.3/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 38985.
run the genewise shell file
running genewise
convert result to gff3 format
cat: ./test_mitoscaf.fa.genewise/*/*.genewise: No such file or directory
_**Traceback (most recent call last):**_
  File "/lustre/home/acct-ioozds/ioozds/yc/MitoZ_v2.3/bin/annotate/prepare_CDSposition.py", line 47, in <module>
    fh_in = open(in_f, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/lustre/home/acct-ioozds/ioozds/yc/data/test_mitoscaf.fa.solar.genewise.gff.cds.position.cds'
Error occured when running command:
/lustre/opt/cascadelake/linux-centos7-x86_64/gcc-4.8.5/miniconda3-4.8.2-5yczksexambgeule63z3smwiwrbokjtu/bin/python3 /lustre/home/acct-ioozds/ioozds/yc/MitoZ_v2.3/bin/annotate/prepare_CDSposition.py /lustre/home/acct-ioozds/ioozds/yc/data/test_mitoscaf.fa.solar.genewise.gff.cds.position.cds /lustre/home/acct-ioozds/ioozds/yc/data/test.cds.position

**Comment by linzhi2013** [comment]
You may need to have a look what is inside the file `/lustre/home/acct-ioozds/ioozds/yc/data/test_mitoscaf.fa`.

This file is the assembled mitogenome. If it is empty, or very short, then no PCGs found.

**Comment by user1-10** [comment]
Dear Meng,
I have checked the length of mitogeome. It is 16687 bp, and is a fish mitochondrial genome.
I have tried other mitochondrial genome, and same error present again.

**Comment by linzhi2013** [comment]
I see. 

Did you run your installed MitoZ using the test data? Maybe your MitoZ installation had some problems. 

If that's the case, and If you still can't fix the problem, then you may try the Docker version MitoZ v2.3.

Cheers
