### ISSUE TITLE
Hi, dear author, is it possible to extract the mitochondrial genome using Rad-seq dataset in MitoZ with or without reference methods? 

### ISSUE THREAD

**Issue by Maotingru** [linzhi2013/MitoZ#136]
Hi, dear author, is it possible to extract the mitochondrial genome using Rad-seq dataset in MitoZ with or without reference methods?  What command or parameter setting should I use if I can use a reference mitochondrial genome to improve accuracy? I have not been able to find this setting... I am looking forward to your answer!

**Comment by linzhi2013** [comment]
Dear Maotingru,

MitoZ was not designed for RAD-sequencing data, however, you can try to use the `all` or `all2` command to assemble mitogenomes with MitoZ. I'm not sure how fragmented is when DNA has been processed with RAD-experiment. If the mtDNA is not affected much by RAD-experiment (e.g. some (or most of) mtDNA regions have gone away after RAD treatment), there is still a chance to assemble the mitogenome.

Cheers
Guanliang

**Comment by comery** [comment]
Hi Maotingru,
 As Guanling mentioned, MitoZ was not designed to deal with RAD-seq data. What I can come up with to do so are two suggestions:

a) Actually, RAD-seq has no substantial differences with whole-genome sequencing, only except lower genome coverage and fragmented distribution. So if you want to use assemble mitochondrial genome using RAD-seq data, you may need to increase input reads to cover this problem;
b) using a reference to guide assembly is also a good idea, you can map your RAD-seq reads to the reference using bwa, and then call consensus sequence using samtools. Here is a tutorial for this analysis. [read more](https://samtools.github.io/bcftools/howtos/consensus-sequence.html)

After that, you can use MitoZ to annotate your assembly.

best wishes,
Chentao
