### ISSUE TITLE
[nhmmer] running err

### ISSUE THREAD

**Issue by mengnanwang96** [linzhi2013/MitoZ#138]
Error occured when running command:
nhmmer -o work71.hmmout --tblout work71.hmmtblout --cpu 4 /home/ocean/Software/MitoZ/version_2.3/release_MitoZ_v2.3/bin/profiles/CDS_HMM/Arthropoda_CDS.hmm /home/ocean/Software/MitoZ/version_2.3/release_MitoZ_v2.3/tmp/test.assembly/work71.scafSeq

so how should i do to solve it.thanks

**Comment by callumjethomas** [comment]
I am getting an error at the same point. Did you ever work out how to solve this or what is causing it?
