### ISSUE TITLE
The situation that reads map mitogenome 

### ISSUE THREAD

**Issue by orient100** [linzhi2013/MitoZ#14]
![1560481192(1)](https://user-images.githubusercontent.com/49135826/59480578-b33d8180-8e93-11e9-9a3f-4aef8613d3ed.jpg)
From the visualization results, I found that some reads is't  mitochondrial reads but I think they may be pseudogenes. Can you provide some methods to remove these reads or do you think this situation will not have a  bad effects?

**Comment by linzhi2013** [comment]
> ![1560481192(1)](https://user-images.githubusercontent.com/49135826/59480578-b33d8180-8e93-11e9-9a3f-4aef8613d3ed.jpg)
> From the visualization results, I found that some reads is't mitochondrial reads but I think they may be pseudogenes. Can you provide some methods to remove these reads or do you think this situation will not have a bad effects?

Hi orient100,

How did you get the above results?  Did you map the reads in the directory `tmp.ZZZ.cleandata` to the  mitochondrial sequences with mapper such as BWA?

If you just want to remove those reads from the alignment results, you can set  stricter parameters when running BWA.
