### ISSUE TITLE
Error occured when running assemble

### ISSUE THREAD

**Issue by dinhe878** [linzhi2013/MitoZ#140]
Hi,

I was trying to assemble mitochondrial genome from short-read paired-end data. An error occurred when:

> /services/tools/mitoz/2.3/release_MitoZ_v2.3/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 40
> 
> 
> mitoAssemble is based on SoapTrans v1.03 and modified to fit mitogenome assembly by BGI-ENVers
> 
> pregraph -s work71.soaptrans.lib -K 71 -p 40 -o work71
> In work71.soaptrans.lib, 1 libs, max seq len 100, max name len 256
> 
> 40 thread created
> read from file:
>  /home/projects/ku_00039/people/dinghe/data/GAGA/stLFR/GAGA-0331.1.clean.fq.gz
> read from file:
>  /home/projects/ku_00039/people/dinghe/data/GAGA/stLFR/GAGA-0331.2.clean.fq.gz
> --- 100000000th reads
> --- 200000000th reads
> --- 300000000th reads
> Error occured when running command:
> /services/tools/mitoz/2.3/release_MitoZ_v2.3/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 40

I am not sure if the memory would be an issue, and I didn't find any option to limit the required memory capacity in the program description. I try to run it on a server node (40 cores) with ~ 180 Gb ram. The read count of each direction of my data is 325632420 (so times 2 for total pair-end).

I couldn't find other information about the error, so I have no clue what might cause this error...

Any suggestion? Thanks!

**Comment by linzhi2013** [comment]
you should try to use lower thread numbers, say 12. 40 seems too big to work for the program.

**Comment by dinhe878** [comment]
> you should try to use lower thread numbers, say 12. 40 seems too big to work for the program.

Thanks @linzhi2013 it solved my issue!
