### ISSUE TITLE
try different k-mer sizes for run_mode 2

### ISSUE THREAD

**Issue by mmatschiner** [linzhi2013/MitoZ#141]
Hi,
Thanks for developing MitoZ. I ran it in Singularity with the test dataset and that worked fine. But I'm having issues with my own data, which is relatively bad quality (DNA from samples that were in formaldehyde) and a read length that varies but is largely between 60 and 80 bp. It is also single-read only data. I was wondering if I could try k-mer sizes other than 71 for in run_mode 2? Or would you have other advice how to tweak MitoZ for this kind of data?
Thanks a lot!
Michael

**Comment by linzhi2013** [comment]
Yes, you can try to run the MitoAssembler directly with any kmers you want to try.

and then use the findmitoscaf and annotate module to search for and annnotate mitogenomes.

**Comment by mmatschiner** [comment]
Thanks for the quick reply. I tried running mitoAssemble alone in this way:
```
singularity exec -B ${current_dir} MitoZ.simg \
    /app/release_MitoZ_v2.3/bin/assemble/mitoAssemble all  -K 51 -o work51 -s work51.soaptrans.lib -p 4

```but then the file `work51.soaptrans.lib` could not be found. When I tried the same with `-w work71.soaptrans.lib`, that file also can't be found.
Do you have a suggestion of how mitoAssemble alone can be run in Singularity?

**Comment by linzhi2013** [comment]
yes, you can use the `work71.soaptrans.lib` file directly. the key parameter is ` -K 51 ` only.

**Comment by mmatschiner** [comment]
Good to know, thanks!

**Comment by linzhi2013** [comment]
In the MitoZ 3.0, now there is an `--kmers` option, you can set many different kmers at the same time.
