### ISSUE TITLE
Problem: program_begin_clock = time.clock() AttributeError: module 'time' has no attribute 'clock'

### ISSUE THREAD

**Issue by trashbelintani** [linzhi2013/MitoZ#143]
(ete) tiagob@uv2000:/guest/triatominae/tiagob/mitosmitos/MitoZ/version_2.3/release_MitoZ_v2.3> python3 MitoZ.py all --genetic_code 5 --clade Arthropoda --outprefix mspinolai \
> --thread_number 12 \
> --fastq1 /guest/triatominae/tiagob/trimagem/m_s/m1/r1.fq \
> --fastq2 /guest/triatominae/tiagob/trimagem/m_s/m1/r2.fq \
> --fastq_read_length 150 \
> --insert_size 250  \
> --run_mode 2 \
> --filter_taxa_method 1 \
> --requiring_taxa 'Arthropoda'
/labev/tiagob/ana3/envs/ete/lib/python3.9/site-packages/ete3-3.1.2-py3.7.egg/ete3/evol/parser/codemlparser.py:221: SyntaxWarning: "is" with a literal. Did you mean "=="?
/labev/tiagob/ana3/envs/ete/lib/python3.9/site-packages/ete3-3.1.2-py3.7.egg/ete3/evol/parser/codemlparser.py:221: SyntaxWarning: "is" with a literal. Did you mean "=="?
Traceback (most recent call last):
  File "/guest/triatominae/tiagob/mitosmitos/MitoZ/version_2.3/release_MitoZ_v2.3/MitoZ.py", line 1942, in <module>
    program_begin_clock = time.clock()
AttributeError: module 'time' has no attribute 'clock'

**Comment by linzhi2013** [comment]
Seems caused by the problems of the mitozEnv. Please make sure that you can run the test data before go to your real data.

**Comment by trashbelintani** [comment]
Solved, I changed the lines, as follows:

if args.command == "all":
	os.chdir(work_dir_tmp)
	program_begin_clock = time.time()
	program_begin_wall = time.time()



Thanks
