### ISSUE TITLE
Fail to install MitoZ 3.2 

### ISSUE THREAD

**Issue by Qinanio** [linzhi2013/MitoZ#145]
Hi Guanliang,

I have used the docker image of MitoZ 2.3 and 2.4 to assemble mitogenome, which works well. 
But I'm having some problems of installing the new version 3.2. 

I followed the manual from https://github.com/linzhi2013/MitoZ/releases/, entered
`$ mamba create -n mitozEnv -c bioconda mitoz=3.2`
output an error message like this:
```
_Encountered problems while solving.
Problem: nothing provides xorg-libxext needed by ete3-3.1.1-py27_0_
```

Then I tried 
`$ mamba env create -n mitozEnv  -f mitozEnv.yaml`
 error message:
`SpecNotFound: Invalid name, try the format: user/package`

How could I solve this problem and install MitoZ 3.2 successfully? 

Best regards!
Yuan

**Comment by linzhi2013** [comment]
Hey Yuan, 

You can try:

```bash
$ conda clean -a -y
```

and then rerun 
```bash
$ mamba create -n mitozEnv -c bioconda mitoz=3.2
```

Now I do not prepare Docker or Singularity images, since they ask for money to use their build service.

Please let me know if the advice works for you or not.

Cheers
Guanliang

**Comment by linzhi2013** [comment]
Hey Yuan,

Thanks for your message.

I have no idea about the problem you met actually. I just tried installing MitoZ using the same command on a Linux and Mac OS (even though MitoZ does not fully support Mac OS for now), and the command worked well.

Maybe you can install a new Conda at a totally different place, and use this new Conda to install MitoZ following the same instruction.

Cheers

**Comment by Qinanio** [comment]
Hey Guanliang,
Thank you for your reply! 
I had another problem while annotating genes on N-chain (eg. ND4, ND5 and ND1). 
![Snipaste_2022-05-19_11-17-49](https://user-images.githubusercontent.com/7923472/169258531-5fa5c5a0-9466-45e3-a66e-761953c51ad8.jpg)
I extrated gene length from summary.txt and put them in a Excel table. 
Some genes on N-chain were longer than the previously published results.
eg.
```
     gene            complement(11538..12561)
                     /gene="ND1"
     CDS             complement(11538..12561)
                     /gene="ND1"
                     /codon_start=1
                     /transl_table=5
                     /product="NADH dehydrogenase subunit 1"
                     /translation="MDLIMPLVGSLLLIICVLVGVAFLTLLERKVLGYIQIRKGPNKV
                     GFMGIPQPFCDAIKLFTKEQTYPVLSNYVSYYFSPIFSLFLSLIVWLVMPYFTNLYSF
                     NLGLIFFLCCTSLGVYTVMIAGWSSNSNYALLGGLRAVAQTISYEVSLALTLLSFVFL
                     ISGYDLLIFYIYQNYMWFIIITFPLGLSWFASCLAETNRTPFDFAEGESELVSGFNVE
                     YSSGGFALIFLAEYASILFMSMLFSVIFLGCDMMSFMFFIKLTFLSFLFIWVRGTLPR
                     FRYDKLMYLAWKSFLPLALNYLIFFLSLKILLPSLF*WNIFSKVNSKILFLSYVFKTY
                     AIQAHWL"
     gene            11540..11606
                     /gene="trnS(uga)"
     tRNA            11540..11606
                     /gene="trnS(uga)"
                     /product="tRNA-Ser"
```
The location of ND1(11538-12561) covered the full length of trnS(11540-11606), which reversed the positions of this two genes. (should be CYTB - trnS - ND1 - trnL)
Meanwhile, there was a redundant sequence in the result: 
`*WNIFSKVNSKILFLSYVFKTYAIQAHWL`
It is very weird, and may be based on a mistranslation of trna. This type of result occured many times.

I have used Geneious to re-annotate the same sequence, which gave me a more accurate result without gene-overlapping.

So which of my steps went wrong? 
`sudo docker run -v $PWD:/project --rm guanliangmeng/mitoz:2.3 /app/release_MitoZ_v2.3/MitoZ.py annotate  --genetic_code 5 --clade Arthropoda --outprefix test --thread_number 20 --fastafile test.fasta`

**Comment by linzhi2013** [comment]
Please keep the same thread dealing only with ONE question. Thanks!
