### ISSUE TITLE
annotation problem and overlapping genes

### ISSUE THREAD

**Issue by linzhi2013** [linzhi2013/MitoZ#146]
Hey Guanliang,
Thank you for your reply! 
I had another problem while annotating genes on N-chain (eg. ND4, ND5 and ND1). 
![Snipaste_2022-05-19_11-17-49](https://user-images.githubusercontent.com/7923472/169258531-5fa5c5a0-9466-45e3-a66e-761953c51ad8.jpg)
I extrated gene length from summary.txt and put them in a Excel table. 
Some genes on N-chain were longer than the previously published results.
eg.
```
     gene            complement(11538..12561)
                     /gene="ND1"
     CDS             complement(11538..12561)
                     /gene="ND1"
                     /codon_start=1
                     /transl_table=5
                     /product="NADH dehydrogenase subunit 1"
                     /translation="MDLIMPLVGSLLLIICVLVGVAFLTLLERKVLGYIQIRKGPNKV
                     GFMGIPQPFCDAIKLFTKEQTYPVLSNYVSYYFSPIFSLFLSLIVWLVMPYFTNLYSF
                     NLGLIFFLCCTSLGVYTVMIAGWSSNSNYALLGGLRAVAQTISYEVSLALTLLSFVFL
                     ISGYDLLIFYIYQNYMWFIIITFPLGLSWFASCLAETNRTPFDFAEGESELVSGFNVE
                     YSSGGFALIFLAEYASILFMSMLFSVIFLGCDMMSFMFFIKLTFLSFLFIWVRGTLPR
                     FRYDKLMYLAWKSFLPLALNYLIFFLSLKILLPSLF*WNIFSKVNSKILFLSYVFKTY
                     AIQAHWL"
     gene            11540..11606
                     /gene="trnS(uga)"
     tRNA            11540..11606
                     /gene="trnS(uga)"
                     /product="tRNA-Ser"
```
The location of ND1(11538-12561) covered the full length of trnS(11540-11606), which reversed the positions of this two genes. (should be CYTB - trnS - ND1 - trnL)
Meanwhile, there was a redundant sequence in the result: 
`*WNIFSKVNSKILFLSYVFKTYAIQAHWL`
It is very weird, and may be based on a mistranslation of trna. This type of result occured many times.

I have used Geneious to re-annotate the same sequence, which gave me a more accurate result without gene-overlapping.

So which of my steps went wrong? 
`sudo docker run -v $PWD:/project --rm guanliangmeng/mitoz:2.3 /app/release_MitoZ_v2.3/MitoZ.py annotate  --genetic_code 5 --clade Arthropoda --outprefix test --thread_number 20 --fastafile test.fasta`

_Originally posted by @Qinanio in https://github.com/linzhi2013/MitoZ/issues/145#issuecomment-1131473016_

**Comment by Qinanio** [comment]
Sorry, my bad : (
Similar problem was observed on the annotation results of 16S rRNA

**Comment by linzhi2013** [comment]
The annotation is tRNA genes is performed by MiTFi. You may want to check it for more details.

Regarding the "ND" genes, there is an internal stop codon in your sequences, which could be due to a lack of close relatives of such genes in MitoZ's database, or there are some bugs in MitoZ, which made MitoZ fail to find the "stop codon" (which is the internal stop codon here) in your cases, and thus MitoZ then tried to find the stop codon or "T/TA" by 3' extension.

Have a look at the sequence, make sure this is not due to assembly error or Ns in your sequences. check the alignments with public genes (NT and protein level).  also, check if it is a contaminant, by blasting the sequences to the NCBI NT database.


then, if it is an annotation error, could you please send one of the mitochondrial genomes  (a published one is also fine) to me? I would like to check it. Thank you!

Cheers
Guanliang

**Comment by Qinanio** [comment]
I would like to send you a copy of the annotated results, including a comparison with Geneious result, but I couldn't find your contact information...

**Comment by linzhi2013** [comment]
> I would like to send you a copy of the annotated results, including a comparison with Geneious result, but I couldn't find your contact information...

linzhi2012\<mitoz\>gmail\<mitoz\>com.

replace <mitoz> with “@” and ".", respectively.

**Comment by Qinanio** [comment]
I have sent you a mail, looking forward to reply!

**Comment by linzhi2013** [comment]
Dear Yuan,

Thanks for your email. The "N-genes" problem is due to the lack of more closely related protein sequences in MitoZ's database.

I checked only the ND1 gene here.

Have a look at below (ND1 genes only):

<img width="1410" alt="image" src="https://user-images.githubusercontent.com/6203542/169997102-9826cfb5-4a6c-4276-b368-1489d4e1020b.png">

The top one is a ND1 gene from NCBI (by blasting your sample mitogenome to NCBI, and got the most closely related species)

The second one is the ND1 gene from you.

The third is the intermediate file when I re-run the annotation using your `test.fasta` file with MitoZ 3.2.

The fourth is the ND1 gene in MitoZ's annotation database that your sample ND1 matched.

The bottom one is the ND1 gene result of your sample after I added a new ND1 gene (i.e., the top one here) to MitoZ's annotation database and annotated with MitoZ 3.2.


The reason we got "the second, the third" ND1 gene result is that, in current MitoZ's database, we have this sequence: `MitZ annotation DB gi NC 027290 ND1 Bactrocera tau 339 aa`, which is longer than other ND1 genes for your samples.


Solution:

1. Download the protein sequences of some more closely related species:
<img width="1067" alt="image" src="https://user-images.githubusercontent.com/6203542/169999796-26bf9d3f-68d9-49a7-a684-be9dbff397a5.png">

2. Add these new protein sequences into the annotation database file: `mitoz/profiles/MT_database/Arthropoda_CDS_protein.fa`
<img width="924" alt="image" src="https://user-images.githubusercontent.com/6203542/170000003-8898353d-17bd-45f6-a9f2-6b903c8457b1.png">

**The header line format must follow this style.**

3. re-annoate your mitogenome.

**Comment by Qinanio** [comment]
Thank you very much for your prompt response!

I use the conda version of Mitoz 3.2 (this time I installed it successfully but I dont know why), and find out 5 "MT_database" files. Which one should I put "Arthropoda_CDS_protein.fa" in?

```
/anaconda3/lib/python3.9/site-packages/mitoz-3.2-py3.9.egg/mitoz/profiles/MT_database
/anaconda3/pkgs/mitoz-3.2-pypl5321hdfd78af_0/site-packages/mitoz/profiles/MT_database
/anaconda3/envs/ete3/lib/python3.6/site-packages/mitoz/profiles/MT_database
/anaconda3/envs/ete3/lib/python3.6/site-packages/mitoz-3.2-py3.6.egg/mitoz/profiles/MT_database
/anaconda3/envs/mitozEnv/lib/python3.7/site-packages/mitoz/profiles/MT_database

```

**Comment by linzhi2013** [comment]
Please check https://github.com/linzhi2013/MitoZ/wiki/Extending-MitoZ's-database
