### ISSUE TITLE
singularity for MitoZ v3.2

### ISSUE THREAD

**Issue by AlesBucek** [linzhi2013/MitoZ#147]
Hi!
I've been using previous MitoZ version via singularity which I got as follows:
`singularity pull  --name MitoZ.simg shub://linzhi2013/MitoZ:v2.3`

Is there a singularity image available for MitoZ v3.2? I'm running MitoZ on an HPC cluster where docker is not available. 

(my primary motivation for upgrade is that I would like to specify my custom protein database for annotation using argument "--profiles_dir" but that argument seems not to be supported in v2.3)

Thanks! 
Ales

**Comment by linzhi2013** [comment]
Hey Ales,

Thanks for your feedback!

Unfortunately, currently, I don't have the appropriate computer resources and privilege to build a Singularity or Docker image, and the Singularity and Docker they now no longer provide free building-image service. I will try to figure out how to do it later.

Yes, MitoZ 2.3 doesn't have the `--profiles_dir` option. But you are able to log in to the Singularity container and modify the database files if you want, and then run MitoZ within the container.

Cheers

**Comment by linzhi2013** [comment]
I am building a singularity image now, it seems to work. Let me find a place to put it so users can download it.

**Comment by linzhi2013** [comment]
See https://github.com/linzhi2013/MitoZ/wiki/Installation.

**Comment by AlesBucek** [comment]
Thanks for the quick response! I managed to download and run the singularity image without problems.
