### ISSUE TITLE
biopython not found

### ISSUE THREAD

**Issue by MjelleLab** [linzhi2013/MitoZ#15]
$ python3 MitoZ.py
package biopython not found! Please install it!

I have installed using miniconda and exported to path:
export PATH=~/miniconda2/pkgs/biopython-1.70-np112py27_1:$PATH

**Comment by linzhi2013** [comment]
> $ python3 MitoZ.py
> package biopython not found! Please install it!
> 
> I have installed using miniconda and exported to path:
> export PATH=~/miniconda2/pkgs/biopython-1.70-np112py27_1:$PATH

Hi !

Could you please tell me how did you install MitoZ? Did you follow the instruction on https://github.com/linzhi2013/MitoZ/blob/master/version_2.4-alpha/INSTALL.md ?

If you installed MitoZ from source, it is very critical that make sure you are in the mitozEnv environment when you run MitoZ.


cheers

**Comment by biocoreexpert** [comment]
From source yes. 

I tried to set the environment:


 conda create  -n mitozEnv libgd=2.2.4 python=3.6.0 biopython=1.69 ete3=3.0.0b35 perl-list-moreutils perl-params-validate perl-clone circos=0.69 perl-bioperl 
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

**Comment by biocoreexpert** [comment]
I am getting this:


robinm@havpryd:~$ conda create  -n mitozEnv libgd=2.2.4 python=3.6.0 biopython=1.69 ete3=3.0.0b35 perl-list-moreutils perl-params-validate perl-clone circos=0.69 perl-bioperl blast=2.2.31  hmmer=3.1b2  bwa=0.7.12 samtools=1.3.1 infernal=1.1.1 tbl2asn openjdk
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - biopython=1.69 -> reportlab -> pillow[version='>=2.4.0'] -> tk[version='>=8.6.9,<8.7.0a0']
  - blast=2.2.31 -> boost=1.60 -> python=3.5 -> tk[version='>=8.6.8,<8.7.0a0']
  - ete3=3.0.0b35 -> lxml -> python[version='>=3.6,<3.7.0a0'] -> tk[version='>=8.6.9,<8.7.0a0']
  - python=3.6.0 -> tk=8.5

**Comment by linzhi2013** [comment]
Hi,

I am not sure what's wrong there. but I have two advice,

1. try clean you conda cache files firstly with `conda clean -a` command.

2. conda/bioconda has upgraded to gcc7 (see https://github.com/conda/conda/issues/8413 for more details), and MitoZ was tested with the old version channels. 
try to use the old channels:
```
conda config --remove channels bioconda
conda config --remove channels conda-forge
# and remove other channles you have set
conda config --add channels bioconda/label/cf201901
conda config --add channels conda-forge/label/cf201901

```

Or, you may just use the Docker image or Singularity images.

**Comment by biocoreexpert** [comment]
I tried docker, but I dont have sudo rights. Also, singularity did not work
with conda it seems. Do you think it is possible without sudo?
Thanks.


fre. 28. jun. 2019, 17:29 skrev Guanliang MENG <notifications@github.com>:

**Comment by linzhi2013** [comment]
> with conda it seems. Do you think it is possible without sudo?

1. To install Docker or Singularity, you need sudo rights.
2. To run docker images, you need sudo rights, or you belong to the Docker group.
3. To run Singularity images, you do not need sudo rights, a normal user is enough.

**Comment by ashotmarg2004** [comment]
> Hi,
> 
> I am not sure what's wrong there. but I have two advice,
> 
> 1. try clean you conda cache files firstly with `conda clean -a` command.
> 2. conda/bioconda has upgraded to gcc7 (see [conda/conda#8413](https://github.com/conda/conda/issues/8413) for more details), and MitoZ was tested with the old version channels.
>    try to use the old channels:
> 
> ```
> conda config --remove channels bioconda
> conda config --remove channels conda-forge
> # and remove other channles you have set
> conda config --add channels bioconda/label/cf201901
> conda config --add channels conda-forge/label/cf201901
> ```
> 
> Then create the conda environment angain:
> 
> `conda create -n mitozEnv libgd=2.2.4 python=3.6.0 biopython=1.69 ete3=3.0.0b35 perl-list-moreutils perl-params-validate perl-clone circos=0.69 perl-bioperl blast=2.2.31 hmmer=3.1b2 bwa=0.7.12 samtools=1.3.1 infernal=1.1.1 tbl2asn openjdk `
> Or, you may just use the Docker image or Singularity images.

Thanks a lot, recently I couldn't get the mitoz environment to work after successfully using it a year ago... Now, using the old channels did the trick for me!

**Comment by Robvh-git** [comment]
> 2. conda/bioconda has upgraded to gcc7 (see [conda/conda#8413](https://github.com/conda/conda/issues/8413) for more details), and MitoZ was tested with the old version channels.
>    try to use the old channels:
> 
> ```
> conda config --remove channels bioconda
> conda config --remove channels conda-forge
> # and remove other channles you have set
> conda config --add channels bioconda/label/cf201901
> conda config --add channels conda-forge/label/cf201901
> ```

I could not setup the MitoZ environment, but using these old channels did the trick for me. Thanks.
