### ISSUE TITLE
Assembling using spades requires >=v3.15.4

### ISSUE THREAD

**Issue by charlesfoster** [linzhi2013/MitoZ#151]
Hi,

Thanks for the tool. I tried assembling with `--assembler spades`, but it errored out with:

`AttributeError: module 'collections' has no attribute 'Hashable'`

This problem has been fixed by spades in v3.15.4: https://github.com/ablab/spades/issues/873. I installed v3.15.4 and no longer had the error.

Might be worth updating the conda yaml file to reflect this. Otherwise the instructions can be changed to:

`mamba env create -n mitoz mitoz==3.4 spades==3.15.4`

Thanks.

**Comment by linzhi2013** [comment]
Hi Charlesfoster,

Thanks for your message!

I have updated the https://github.com/linzhi2013/MitoZ/releases/download/3.4/mitozEnv.yml file.

And I will try to rebuild the Conda version for MitoZ 3.4 (so there will be no need to change on the user end).

Cheers
Guanliang

**Comment by linzhi2013** [comment]
Rebuilding finished. 

Feel free to raise other questions when necessary!

Have a nice weekend!

Guanliang
