### ISSUE TITLE
sqn metadata

### ISSUE THREAD

**Issue by dleopold** [linzhi2013/MitoZ#153]
Is there a way to provide metadata for Mitoz to incorporate when generating the genbank submission files? By default it appears to use your information and I am having trouble figuring out how to change it.

**Comment by linzhi2013** [comment]
Thanks for the question! 
I didn't realize this need before. 

You can find the `/share/pool/guanliang/soft/mitoz3.4/lib/python3.8/site-packages/mitoz/annotate/script/template.sbt` file and replace it with your own template file.

You can go to https://www.ncbi.nlm.nih.gov/genbank/tbl2asn2/#Template  to generate your own template file.

In the new release, I will expose this option to the users.

Best

**Comment by linzhi2013** [comment]
See https://github.com/linzhi2013/MitoZ/releases/tag/3.5-beta.
