### ISSUE TITLE
summary file incomplete

### ISSUE THREAD

**Issue by dleopold** [linzhi2013/MitoZ#154]
I am working on switching over to mitoz 3.4, but have run into an issue where the summary.txt file is not properly generated. This error is similar to one I was getting with v2.3, fixed in issue #24 . Is this bug possibly still present in 3.4? or might something else be causing this? Here is the relevant error produced when running the annotate module:

```
2022-07-10 20:50:09,437 - mitoz.utility.utility - INFO - 
/app/anaconda/bin/python3.9 /app/anaconda/lib/python3.9/site-packages/mitoz/annotate/script/genbank_gene_stat_v2.py /project/tmp_reorder_mitoz_in.fasta_mitoscaf.fa/reorder_mitoz_in.fasta_mitoscaf.fa.gbf /project/tmp_reorder_mitoz_in.fasta_mitoscaf.fa/reorder_mitoz_in.fasta_mitoscaf.fa.most_related_species.txt annotate > summary.txt
Traceback (most recent call last):
  File "/app/anaconda/lib/python3.9/site-packages/mitoz/annotate/script/genbank_gene_stat_v2.py", line 238, in <module>
    main()
  File "/app/anaconda/lib/python3.9/site-packages/mitoz/annotate/script/genbank_gene_stat_v2.py", line 215, in main
    gene_infor, gene_freq = gene_stat(gbfile)
  File "/app/anaconda/lib/python3.9/site-packages/mitoz/annotate/script/genbank_gene_stat_v2.py", line 97, in gene_stat
    print(ass_num, "Warning: NO gene or product tag! this gene is not output!\n")
NameError: name 'ass_num' is not defined

2022-07-10 20:50:09,645 - mitoz.utility.utility - ERROR - 
Error occured when running command:
/app/anaconda/bin/python3.9 /app/anaconda/lib/python3.9/site-packages/mitoz/annotate/script/genbank_gene_stat_v2.py /project/tmp_reorder_mitoz_in.fasta_mitoscaf.fa/reorder_mitoz_in.fasta_mitoscaf.fa.gbf /project/tmp_reorder_mitoz_in.fasta_mitoscaf.fa/reorder_mitoz_in.fasta_mitoscaf.fa.most_related_species.txt annotate > summary.txt
```

For reference, here is the command i used:

`docker run -v /home/rstudio/working:/project --rm guanliangmeng/mitoz:3.4 mitoz annotate --genetic_code 2 --clade Chordata --outprefix reorder --thread_number 16 --fastafile mitoz_in.fasta`

It should not be an issue with the assembly I am annotating because I know this example is a fully circularized, standard mitogenome. For reference, here is the header of the assembly:

```
╭─rstudio@ip-172-31-22-121 /mnt/efs/SI_mitogenomes_2  
╰─➤  head ~/working/mitoz_in.fasta 
>Seq1 topology=circular
ACACAGTTATTATTGGCTCATAAATAAACAAGGCAATCGCCACCCATTAAACCTTAAATTTTGAACCTACATTATAGACA
AAAGGGCTTTACGTGTAGATAGCAAAGCCTGGTTTTGCGGAAGACTTAAGCTCTTTACACAAGGGTTCAAATCCCTTTCT
TCACTGTGCCAGTCTACCTTATTACCAACATTATTATTTCCCTAACCACCATTGTTCCCGTCCTTTTAGCCGTTGCCTTT
TTAACACTTATTGAACGAAAAGTATTAGGATATATACAACTTCGAAAAGGCCCCAATATTGTAGGGCCTTACGGCCTCCT
CCAGCCCATCGCCGATGGAGTTAAACTCTTTATTAAGGAGCCTATTCGCCCCTCCTCATCTTCTCCGATCCTTTTCCTCT
TTGCTCCCACCCTCGCCCTTACTATTGCTCTCACCCTGTGAGCCCCTATCCCTATGCCTTTTCCCATTGCAGACCTGAAC
TTAGGAGTTCTTTTCATCCTTGCCCTCTCTAGCCTCGCAGTTTATTCCATTCTTGGCTCAGGCTGAGCATCCAATTCCAA
ATATGCCCTAATTGGGGCCTTACGGGCTGTAGCCCAGACTATTTCTTATGAAGTCAGCCTAGGCCTAATTCTTCTTTGCA
TCGTTATTTTCTCCGGCGGCTTCACCTTACAAGTCTTTAACGTTACACAGGAAGCCATCTGACTAATTATCCCAGCATGA
```

**Comment by linzhi2013** [comment]
Dear @[dleopold](https://github.com/dleopold),

Thanks for reporting the issue! When I tested the 'annotate' module, I didn't get into the same problem. 

Do you mind providing me with an example so I can test the problem tomorrow? You can send me the mitogenome to linzhi2012<MitoZ>gmail<MitoZ>com. Please replace the '<MitoZ'> with '@' and '.', respectively. Thanks!

Cheers
Guanliang

**Comment by linzhi2013** [comment]
Or maybe you can try the solution at https://github.com/linzhi2013/MitoZ/issues/24 first. I don't remember if I have updated this file (could be not...)

**Comment by linzhi2013** [comment]
> Or maybe you can try the solution at #24 first. I don't remember if I have updated this file (could be not...)

Just checked it, and it is that I forgot to update this script. You can replace `/app/anaconda/lib/python3.9/site-packages/mitoz/annotate/script/genbank_gene_stat_v2.py ` with the script in https://github.com/linzhi2013/MitoZ/issues/24#issuecomment-572884734 and the problem should  be gone.

**Comment by dleopold** [comment]
Yup, that works. This bug seems to only affect some of my assemblies. Would you mind briefly explaining what triggers this?

**Comment by linzhi2013** [comment]
See https://github.com/linzhi2013/MitoZ/releases/tag/3.5-beta-1
