### ISSUE TITLE
"Segmentation fault (core dumped)" after (trying to) install

### ISSUE THREAD

**Issue by eugeniosss** [linzhi2013/MitoZ#155]
Hello,
I am trying to install MitoZ, since I am doing it in a cluster where I do not have any root privileges and neither Docker or Singularity are available, I am trying to do so with Conda. I follow the instructions supported and I think I am able to install Mitoz, however when I try to run it, for instance, "mitoz -h", the following error pops up: "Segmentation fault (core dumped)". The OS of this cluster is Red Hat, does anybody have any idea of what I should do?

**Comment by linzhi2013** [comment]
this error can happen if you do not have enough RAM during an assembly. However, it seems not to be your case.

I would recommend you to try this method first: https://github.com/linzhi2013/MitoZ/wiki/Installation#3-conda-pack 

Cheers
