### ISSUE TITLE
MitoZ annotate error?

### ISSUE THREAD

**Issue by sunnyEV** [linzhi2013/MitoZ#156]
**CMD -**
mitoz annotate --fastafiles ../flye_scaffold.fasta --outprefix flyetest --genetic_code 2 --clade Chordata --thread_number 10 > get.log

2022-08-06 18:42:18,302 - mitoz.utility.utility - INFO - 
annotate.main() got args:
Namespace(debug=False, workdir='./', outprefix='flyetest', thread_number='10', fastafiles=['../flye_scaffold.fasta'], fq1='', fq2='', profiles_dir='/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/profiles', species_name='Test sp.', genetic_code='2', clade='Chordata', mitoz_module_used='annotate', func=<function main at 0x7fa44025ee50>, logger=<Logger mitoz.utility.utility (DEBUG)>)

2022-08-06 18:42:18,302 - mitoz.utility.utility - INFO - 
annotate.main() got updated args:
Namespace(debug=False, workdir='./', outprefix='flyetest', thread_number='10', fastafiles=['../flye_scaffold.fasta'], fq1='', fq2='', profiles_dir='/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/profiles', species_name='Test sp.', genetic_code='2', clade='Chordata', mitoz_module_used='annotate', func=<function main at 0x7fa44025ee50>, logger=<Logger mitoz.utility.utility (DEBUG)>)

2022-08-06 18:42:18,303 - mitoz.utility.utility - INFO - 
annotate.main() will be working in:/home/sunn/data/softwares/mitoz-3.4

2022-08-06 18:42:18,303 - mitoz.utility.utility - INFO - 
annotate.main() chdir:/home/sunn/data/softwares/mitoz-3.4

2022-08-06 18:42:18,303 - mitoz.utility.utility - INFO - 
annotate.main() MT_annotation_BGI_pro_db:/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/profiles/MT_database/Chordata_CDS_protein.fa

2022-08-06 18:42:18,303 - mitoz.utility.utility - INFO - 
annotate.main() defined_gene_length_f:/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/profiles/CDS_HMM/Chordata_CDS_length_list

2022-08-06 18:42:18,303 - mitoz.utility.utility - INFO - 
annotate.main() s_rRNA_CM:/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/profiles/rRNA_CM/v1.1_12snew.cm

2022-08-06 18:42:18,303 - mitoz.utility.utility - INFO - 
annotate.main() l_rRNA_CM:/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/profiles/rRNA_CM/v1.1_16snew.cm

2022-08-06 18:42:18,303 - mitoz.utility.utility - INFO - 
Start to check if the sequence ids are too long (which will not work with BioPython) later.

2022-08-06 18:42:18,303 - mitoz.utility.utility - WARNING - 
Error: file /home/sunn/data/softwares/flye_scaffold.fasta the sequence id '>contig_13864_rotated' is too long! Please rename it! But REMEMBER to keep 'topology=linear' or 'topology=circular' at the header line!!

2022-08-06 18:42:18,303 - mitoz.utility.utility - CRITICAL - 
Some sequence ids are too long! Please rename them first!
But REMEMBER to keep 'topology=linear' or 'topology=circular' at the header line!!

2022-08-06 18:42:18,303 - mitoz.utility.utility - INFO - 
Starting to annotate /home/sunn/data/softwares/flye_scaffold.fasta

2022-08-06 18:42:18,303 - mitoz.utility.utility - INFO - 
result_wdir for /home/sunn/data/softwares/flye_scaffold.fasta: /home/sunn/data/softwares/mitoz-3.4/flyetest.flye_scaffold.fasta.result

2022-08-06 18:42:18,303 - mitoz.utility.utility - INFO - 
working in /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa

2022-08-06 18:42:18,303 - mitoz.utility.utility - INFO - 
annotation_infile: /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa

2022-08-06 18:42:18,307 - mitoz.utility.utility - WARNING - 
Can NOT find topology information for contig_13864_rotated. Now I assume it is topology=linear!!!

2022-08-06 18:42:18,307 - mitoz.utility.utility - CRITICAL - 
Error: the sequence id contig_13864_rotated is too long! Please rename it!

2022-08-06 18:42:18,307 - mitoz.utility.utility - INFO - 
cds_annotation() chdir to /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa

2022-08-06 18:42:18,307 - mitoz.utility.utility - INFO - 
export WISECONFIGDIR=/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/wisecfg
perl /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl -i /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa -d /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/profiles/MT_database/Chordata_CDS_protein.fa -o ./ -g 2 -cpu 10

makeblastdb -in /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa -dbtype nucl
BLAST options error: File /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa is empty
run the tblastn shell file
BLAST Database error: No alias or index file found for nucleotide database [/home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa] in search path [/home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa::]
Run solar to conjoin HSPs and filter bad HSPs and redundance.
preparing genewise input directories and files
name gi_NC_KM273123_COX3_Drepane_punctata_261_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 36059.
name gi_NC_KP164983_COX3_Drepane_longimana_261_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 40505.
name gi_NC_010292_CYTB_Heteronotia_binoei_379_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 51239.
name gi_NC_019615_ND5_Hoplobatrachus_rugulosus_611_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 97575.
name gi_NC_027267_ND6_Phalacrocorax_carbo_173_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 105007.
name gi_NC_018340_ND6_Champsocephalus_gunnari_174_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 106795.
name gi_NC_025925_ND6_Ixobrychus_sinensis_173_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 107345.
name gi_NC_025924_ND6_Ixobrychus_eurhythmus_173_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 107349.
name gi_NC_025923_ND6_Botaurus_stellaris_173_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 107353.
name gi_NC_025922_ND6_Butorides_striata_173_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 107357.
name gi_NC_025921_ND6_Ardeola_bacchus_173_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 107361.
name gi_NC_025920_ND6_Egretta_sacra_173_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 107365.
name gi_NC_015087_ND6_Penelopides_panini_173_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 107997.
name gi_NC_015085_ND6_Aceros_waldeni_173_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 108001.
name gi_NC_029147_ND6_Turdus_philomelos_171_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 109401.
name gi_NC_029140_ND6_Notiomystis_cincta_172_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 109415.
name gi_NC_026190_ND6_Phoebastria_albatrus_175_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 109921.
name gi_NC_026189_ND6_Phoebastria_immutabilis_175_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 109925.
name gi_NC_026188_ND6_Phoebastria_nigripes_175_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 109929.
name gi_NC_010292_ND6_Heteronotia_binoei_173_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 111929.
name gi_NC_007172.2_ND6_Thalassarche_melanophrys_175_aa is not uniq at /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 112085.
run the genewise shell file
running genewise
convert result to gff3 format
cat: './flyetest_flye_scaffold.fasta_mitoscaf.fa.genewise/*/*.genewise': No such file or directory

2022-08-06 18:42:30,693 - mitoz.utility.utility - INFO - 
rm -rf *.nhr *.nin *.nsq formatdb.log *.tblastn.shell *.length *.blast *.blast.filter *.shell *.blast.solar *.blast.solar.filter *.blast.solar.filter.table *.blast.solar.filter.table.nonredundance *.blast.solar.filter.nr *.genewise *.solar.genewise.gff *.solar.genewise.gff.cds

2022-08-06 18:42:30,707 - mitoz.utility.utility - INFO - 
/home/sunn/anaconda3/bin/python /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/prepare_CDSposition.py flyetest_flye_scaffold.fasta_mitoscaf.fa.solar.genewise.gff.cds.position.cds flyetest_flye_scaffold.fasta_mitoscaf.fa.cds.position
Traceback (most recent call last):
  File "/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/prepare_CDSposition.py", line 47, in <module>
    fh_in = open(in_f, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'flyetest_flye_scaffold.fasta_mitoscaf.fa.solar.genewise.gff.cds.position.cds'

2022-08-06 18:42:30,748 - mitoz.utility.utility - ERROR - 
Error occured when running command:
/home/sunn/anaconda3/bin/python /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/prepare_CDSposition.py flyetest_flye_scaffold.fasta_mitoscaf.fa.solar.genewise.gff.cds.position.cds flyetest_flye_scaffold.fasta_mitoscaf.fa.cds.position

2022-08-06 18:42:30,749 - mitoz.utility.utility - INFO - 
/home/sunn/anaconda3/bin/python /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/pick_most_related_sp_from_position_cds.py flyetest_flye_scaffold.fasta_mitoscaf.fa.solar.genewise.gff.cds.position.cds /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa.most_related_species.txt 
Traceback (most recent call last):
  File "/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/pick_most_related_sp_from_position_cds.py", line 183, in <module>
    main()
  File "/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/pick_most_related_sp_from_position_cds.py", line 169, in main
    cds_taxa_file = get_lineage_for_cds(cdspos=cds_pos_file)
  File "/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/pick_most_related_sp_from_position_cds.py", line 124, in get_lineage_for_cds
    with open(cdspos, 'r') as fh, open(cdspos_taxa_log, 'w') as fh_taxalog:
FileNotFoundError: [Errno 2] No such file or directory: 'flyetest_flye_scaffold.fasta_mitoscaf.fa.solar.genewise.gff.cds.position.cds'

2022-08-06 18:42:31,127 - mitoz.utility.utility - ERROR - 
Error occured when running command:
/home/sunn/anaconda3/bin/python /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/pick_most_related_sp_from_position_cds.py flyetest_flye_scaffold.fasta_mitoscaf.fa.solar.genewise.gff.cds.position.cds /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa.most_related_species.txt 

2022-08-06 18:42:31,128 - mitoz.utility.utility - INFO - 
sort -k1,1 -k6,6n flyetest_flye_scaffold.fasta_mitoscaf.fa.cds.position >flyetest_flye_scaffold.fasta_mitoscaf.fa.cds.position.sorted
sort: cannot read: flyetest_flye_scaffold.fasta_mitoscaf.fa.cds.position: No such file or directory

2022-08-06 18:42:31,141 - mitoz.utility.utility - ERROR - 
Error occured when running command:
sort -k1,1 -k6,6n flyetest_flye_scaffold.fasta_mitoscaf.fa.cds.position >flyetest_flye_scaffold.fasta_mitoscaf.fa.cds.position.sorted

2022-08-06 18:42:31,141 - mitoz.utility.utility - INFO - 
/home/sunn/anaconda3/bin/python /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/revise_CDS_pos_v6.py /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa flyetest_flye_scaffold.fasta_mitoscaf.fa.cds.position.sorted 2 flyetest_flye_scaffold.fasta_mitoscaf.fa.cds.position.sorted.revised

2022-08-06 18:42:31,334 - mitoz.utility.utility - INFO - 
/home/sunn/anaconda3/bin/python /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/filter_cds_by_annotated-len.py flyetest_flye_scaffold.fasta_mitoscaf.fa.cds.position.sorted.revised flyetest_flye_scaffold.fasta_mitoscaf.fa.cds.position.sorted.revised.filtered 0.8 

2022-08-06 18:42:31,380 - mitoz.utility.utility - INFO - 
/home/sunn/anaconda3/bin/python /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/cds_ft_v2.py flyetest_flye_scaffold.fasta_mitoscaf.fa.cds.position.sorted.revised.filtered 2 flyetest_flye_scaffold.fasta_mitoscaf.fa.cds.ft

2022-08-06 18:42:31,424 - mitoz.utility.utility - INFO - 
cds_annotation() chdir back to /home/sunn/data/softwares/mitoz-3.4

2022-08-06 18:42:31,424 - mitoz.utility.utility - INFO - 
cds_annotation() return:
mt_file_cdsft: flyetest_flye_scaffold.fasta_mitoscaf.fa.cds.ft
annt_most_related_sp_file: /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa.most_related_species.txt

2022-08-06 18:42:31,424 - mitoz.utility.utility - INFO - 
tRNA_annotation() chdir to /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa

2022-08-06 18:42:31,424 - mitoz.utility.utility - INFO - 
## remove previous tRNA result file (if any)
rm -rf /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa.trna

2022-08-06 18:42:31,438 - mitoz.utility.utility - INFO - 
/home/sunn/anaconda3/bin/python /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/tRNA_ft_mitfi.py /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa.trna /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa.trna.ft
Traceback (most recent call last):
  File "/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/tRNA_ft_mitfi.py", line 43, in <module>
    fh_in = open(in_f, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa.trna'

2022-08-06 18:42:31,482 - mitoz.utility.utility - ERROR - 
Error occured when running command:
/home/sunn/anaconda3/bin/python /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/script/tRNA_ft_mitfi.py /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa.trna /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa.trna.ft

2022-08-06 18:42:31,482 - mitoz.utility.utility - INFO - 
tRNA_annotation() chdir back to /home/sunn/data/softwares/mitoz-3.4

2022-08-06 18:42:31,483 - mitoz.utility.utility - INFO - 
rRNA_annotation() chdir to /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa

2022-08-06 18:42:31,483 - mitoz.utility.utility - INFO - 
cmsearch -g --tblout flyetest_flye_scaffold.fasta_mitoscaf.fa.s-rRNA.tbl --cpu 10 /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/profiles/rRNA_CM/v1.1_12snew.cm /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa >flyetest_flye_scaffold.fasta_mitoscaf.fa.s-rRNA.out
Sequence file /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_m

2022-08-06 18:42:31,500 - mitoz.utility.utility - ERROR - 
Error occured when running command:
cmsearch -g --tblout flyetest_flye_scaffold.fasta_mitoscaf.fa.s-rRNA.tbl --cpu 10 /home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/profiles/rRNA_CM/v1.1_12snew.cm /home/sunn/data/softwares/mitoz-3.4/tmp_flyetest_flye_scaffold.fasta_mitoscaf.fa/flyetest_flye_scaffold.fasta_mitoscaf.fa >flyetest_flye_scaffold.fasta_mitoscaf.fa.s-rRNA.out

Traceback (most recent call last):
  File "/home/sunn/anaconda3/bin/mitoz", line 33, in <module>
    sys.exit(load_entry_point('mitoz==3.4', 'console_scripts', 'mitoz')())
  File "/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/MitoZ.py", line 88, in main
    args.func(args)
  File "/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/annotation.py", line 633, in main
    mt_file_s_rRNA_ft, mt_file_l_rRNA_ft = rRNA_annotation(
  File "/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/annotation.py", line 313, in rRNA_annotation
    if not check_cmsearch_global(cmsearch_s_rRNA_tbl_result):
  File "/home/sunn/anaconda3/lib/python3.9/site-packages/mitoz-3.4-py3.9.egg/mitoz/annotate/annotation.py", line 280, in check_cmsearch_global
    with open(glresult, 'r') as fh:
**FileNotFoundError: [Errno 2] No such file or directory: 'flyetest_flye_scaffold.fasta_mitoscaf.fa.s-rRNA.tbl'**

**Comment by linzhi2013** [comment]
Hi,

1. Make sure your installation has no problem
2. Make sure your input sequences are a real mitochondrial genome

Because `cat: './flyetest_flye_scaffold.fasta_mitoscaf.fa.genewise//.genewise': No such file or directory` means that there is no mitochondrial protein-coding-genes fuond by genewise, or was due to the installation problem.

3. the sequence ID in your input file cannot be too long (< 13 characters)

4. make sure your sample belong to Chordata.
