### ISSUE TITLE
Arguments in findmitoscaf

### ISSUE THREAD

**Issue by dhananyashunmugam** [linzhi2013/MitoZ#158]
--requiring_taxa <STR>
                        filtering out non-requiring taxa sequences which may
                        be contamination [Arthropoda]

By giving Arthropoda, will that consider Arthropoda as contamination or consider other than Arthropoda as contamination?

**Comment by linzhi2013** [comment]
Hi, sorry for the confusion, maybe I need to rewrite the message later.

basically, by giving `--requiring_taxa Arthropoda`, it will discard the non-Arthropoda sequences, the non-Arthropoda sequences are considered as contaminations.

**Comment by dhananyashunmugam** [comment]
Thank you for the clarification.

**Comment by dhananyashunmugam** [comment]
Hi,
I'm using mitoZ for mitochondrial genome assembly. I'm just wondered
whether this tool will accept Nanopore sequencing for Mitochondrial genome
assembly.

Thanks,
Dhananya S
