### ISSUE TITLE
error  -K 71 -o work71 -s work71.soaptrans.lib -p 8

### ISSUE THREAD

**Issue by davidku100** [linzhi2013/MitoZ#16]
Hi,

I got a problem when runing the 'all' module. 

This is the information:
Error occured when running command:
/home/XXXXX/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 8

I used clean data, 4G base pair. 
I got this error information after the 'all' module was running for 10 hours. But I am not really sure what is the error '-K 71 -o work71 -s work71.soaptrans.lib -p 8'.

Could you please give me some advice?

Cheers,

David

**Comment by linzhi2013** [comment]
> Hi,
> 
> I got a problem when runing the 'all' module.
> 
> This is the information:
> Error occured when running command:
> /home/XXXXX/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 8
> 
> I used clean data, 4G base pair.
> I got this error information after the 'all' module was running for 10 hours. But I am not really sure what is the error '-K 71 -o work71 -s work71.soaptrans.lib -p 8'.
> 
> Could you please give me some advice?
> 
> Cheers,
> 
> David

Hi David,

It sounds a bit abnormal that 4 G bp data took more than 10 hours.

1. Since you already have clean data, I think you can just use the `all2` module, which will not perform data filtering any more (and thus faster).

2. You can also go to the `tmp.XXX/XXX.assembly` directory, and run  `mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 8` to check what was going on there. Maybe there was not enough memory for mitoAssemble? (about 100G memory).

3. If it is the memory problem, you may subset the input fastq files. MitoZ-2.4-alpha also has one parameter to this end.

Cheers,
Guanliang

**Comment by davidku100** [comment]
Hi Guanliang, 

Thanks for this suggestion.

I tried to figure out what is the real error by: "go to the tmp.XXX/XXX.assembly directory, and run mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 8".  Also, I did the subsets of the data, using only 0.01 Gp as it is much faster to use a small amount of data.

Then, I got this information "segmentation fault (core dumped)". I tried the advice from Google to solve this "segmentation fault", but sadly none of them worked for me  :(

I run MitoZ using Ubuntu. I am wondering if it will be easier if I run MitoZ under pure Linux system?

Cheers,

David

**Comment by linzhi2013** [comment]
Hi David,

I cannot figure out the exact reason for this `core dumped` error according to the above information.

From my experience, the `core dumped` error (not limited to MitoZ) can be caused by:

1. not enough memory. 
2. data specific. 

Since your test data is 0.01 Gbp, I am not sure if this size of data is too small. 

MitoZ was developed under Cent OS, and Ubuntu should also be fine to run. We don't have a Ubuntu machine with enough memory to test it.

Can you try: 
1. use 1 to 2 Gbp data for testing?
2. Try Docker or singularity version of MitoZ, especially version 2.3, since I haven't test the version 2.4-alpha throughly. 


Cheers,
Guanliang

**Comment by Asyantias** [comment]
Hi Guanliang,
same problem here, version 2.3
##// log file //
Segmentation fault (core dumped)
Error occured when running command:
/home/antias/release_MitoZ_v2.3/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 8
## //
i run it under ubuntu subsystem of windows 10 (wsl)



try "ulimit -s unlimited" before running MitoZ.

best luck.





--- 

英语不太好, 中文说吧.
个人是在win10子系统下跑的mitoZ, 提示该错误.
数据量6Gb, 机器2xCPUx40core 配有256GB RAM, 应该不是内存不足的原因.
记得ubuntu对低权限账户有stack size的限制, 默认为8192KB, 猜测是这个问题.
但悲剧的是win10子系统(wsl)不能修改这个设置, 打算过一阵hyper-V下试试看.

**Comment by linzhi2013** [comment]
Hi everyone,

I have just uploaded a small dataset for testing if your environment is fine with MitoZ. Please kindly go to https://github.com/linzhi2013/MitoZ/tree/master/test.

This test runs very fast (15 minutes), use only 4 CPUs and 2G  memory.

Cheers,
Guanliang

**Comment by Asyantias** [comment]
Hi Guangliang

---bash
python3 ~/release_MitoZ_v2.3/MitoZ.py all2 --genetic_code 5 --clade Arthropoda  --outprefix test \
--thread_number 4 \
--fastq1 ./test.1.fq.gz \
--fastq2 ./test.2.fq.gz \
--fastq_read_length 125 \
--insert_size 250 \
1>m.log 2>m.err
---

---m.err
Segmentation fault (core dumped)
Error occured when running command:
/home/antias/release_MitoZ_v2.3/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 4
---

i run it in WSL under miniconda3 - evns (mitozEnv) as instruction shows.

**Comment by linzhi2013** [comment]
> Hi Guangliang
> 
> ## ---bash
> python3 ~/release_MitoZ_v2.3/MitoZ.py all2 --genetic_code 5 --clade Arthropoda --outprefix test 
> --thread_number 4 
> --fastq1 ./test.1.fq.gz 
> --fastq2 ./test.2.fq.gz 
> --fastq_read_length 125 
> --insert_size 250 
> 1>m.log 2>m.err
> ## ---m.err
> Segmentation fault (core dumped)
> Error occured when running command:
> /home/antias/release_MitoZ_v2.3/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 4
> i run it in WSL under miniconda3 - evns (mitozEnv) as instruction shows.

Hi Asyantias,

Thank you very much for your response!

I have not tested MitoZ on WSL (Windows Subsystem for Linux), thus I am sorry that I cannot provide valuable suggestion to you.

However, is it possible for you to use the Docker version of MitoZ (https://www.docker.com/) ?  The containerized version is mostly easily to use, since all the dependencies have been resolved.


Cheers,
Guanliang

**Comment by Asyantias** [comment]
> > Hi Guangliang
> > ## ---bash
> > python3 ~/release_MitoZ_v2.3/MitoZ.py all2 --genetic_code 5 --clade Arthropoda --outprefix test
> > --thread_number 4
> > --fastq1 ./test.1.fq.gz
> > --fastq2 ./test.2.fq.gz
> > --fastq_read_length 125
> > --insert_size 250
> > 1>m.log 2>m.err
> > ## ---m.err
> > Segmentation fault (core dumped)
> > Error occured when running command:
> > /home/antias/release_MitoZ_v2.3/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 4
> > i run it in WSL under miniconda3 - evns (mitozEnv) as instruction shows.
> 
> Hi Asyantias,
> 
> Thank you very much for your response!
> 
> I have not tested MitoZ on WSL (Windows Subsystem for Linux), thus I am sorry that I cannot provide valuable suggestion to you.
> 
> However, is it possible for you to use the Docker version of MitoZ (https://www.docker.com/) ? The containerized version is mostly easily to use, since all the dependencies have been resolved.
> 
> Cheers,
> Guanliang

Hi Guangliang

I am already running a sample in docker (docker for win10pro ) at 10:00 am. (6Gb+)
![image](https://user-images.githubusercontent.com/28779254/62927997-3de62280-bdea-11e9-8f7e-34984b99e8ea.png)

i will try mitoz:2.3.

**Comment by linzhi2013** [comment]
The Python script for subsetting fastq data seems too slow. Maybe I should rewrite it with Perl or use other existing tools in later version.

Guanliang

**Comment by Asyantias** [comment]
> The Python script for subsetting fastq data seems too slow. Maybe I should rewrite it with Perl or use other existing tools in later version.
> 
> Guanliang

Seems running very well in docker for win10pro (only mitoz:2.3) 
Many thanks.
P.F

**Comment by csmiguel** [comment]
> > Hi,
> > I got a problem when runing the 'all' module.
> > This is the information:
> > Error occured when running command:
> > /home/XXXXX/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 8
> > I used clean data, 4G base pair.
> > I got this error information after the 'all' module was running for 10 hours. But I am not really sure what is the error '-K 71 -o work71 -s work71.soaptrans.lib -p 8'.
> > Could you please give me some advice?
> > Cheers,
> > David
> 
> Hi David,
> 
> It sounds a bit abnormal that 4 G bp data took more than 10 hours.
> 
> 1. Since you already have clean data, I think you can just use the `all2` module, which will not perform data filtering any more (and thus faster).
> 2. You can also go to the `tmp.XXX/XXX.assembly` directory, and run  `mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 8` to check what was going on there. Maybe there was not enough memory for mitoAssemble? (about 100G memory).
> 3. If it is the memory problem, you may subset the input fastq files. MitoZ-2.4-alpha also has one parameter to this end.
> 
> Cheers,
> Guanliang

I have got the same problem. I tried running as suggested `/app/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 2` inside the docker image, but the process stops suddenly. Each 1.fq.gz and 2.fq.gz files are only 22MB, so I doubt it is a memory issue:

![image](https://user-images.githubusercontent.com/12279367/67385259-b572c380-f58a-11e9-856a-35a5ed504dc9.png)

**Comment by zskysafe** [comment]
I also have the same problem.
Error occured when running command:
/apps/MitoZ_v2.4/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 6

I run the MitoZ.py in Ubuntu.Worksation have 48 CPUs and 250G memory.
1.fq.gz=3.2GB 2.fq.gz=3.3GB
command as follows:
python3 $DIR_mitoz/MitoZ.py assemble --genetic_code 5 --clade Arthropoda --outprefix $species \
--thread_number 6 \
--fastq1 $out1 \
--fastq2 $out2 \
--fastq_read_length 150 \
--insert_size 250  \
--run_mode 2 \
--filter_taxa_method 1 \
--requiring_taxa 'Arthropoda'

I ran the program to assemble data for 10 species, and four species had this error.
Besides memory and environmental issues, what else can cause this error?

**Comment by linzhi2013** [comment]
> I also have the same problem.
> Error occured when running command:
> /apps/MitoZ_v2.4/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 6
> 
> I run the MitoZ.py in Ubuntu.Worksation have 48 CPUs and 250G memory.
> 1.fq.gz=3.2GB 2.fq.gz=3.3GB
> command as follows:
> python3 $DIR_mitoz/MitoZ.py assemble --genetic_code 5 --clade Arthropoda --outprefix $species
> --thread_number 6
> --fastq1 $out1
> --fastq2 $out2
> --fastq_read_length 150
> --insert_size 250
> --run_mode 2
> --filter_taxa_method 1
> --requiring_taxa 'Arthropoda'
> 
> I ran the program to assemble data for 10 species, and four species had this error.
> Besides memory and environmental issues, what else can cause this error?

Dear zskysafe,

Do you mean that `1.fq.gz=3.2GB` and  `2.fq.gz=3.3GB`? I think it is because you were using too much input data. We recommend to use 3 to 5 G base pairs data, not the size of a fq.gz file. If a fq.gz file has size of 3.2GB, the base pairs must be 7G bp, and two fq.gz files means 14 G bp.

**Comment by zskysafe** [comment]
Dear linzhi2013
I use fastp -q 37 -u 5 to filter the fq.gz. This means that the Q less than 37 is low quality, and the read that have five percent of the low quality will be deleted.
The result is Q30(97.421274%). If I delete the higher quality read(eg. -q 38 -u 5), the final file size will be 0.
In addition, I found that using MitoZ.py all or assemble will have a *.partial_fastq.
MitoZ.py all have *.cleandata.
Isn't this shrinking the data?
How can I further reduce the data size？
What tool do you use to get part of the file content？ @linzhi2013

**Comment by linzhi2013** [comment]
> Dear linzhi2013
> I use fastp -q 37 -u 5 to filter the fq.gz. This means that the Q less than 37 is low quality, and the read that have five percent of the low quality will be deleted.
> The result is Q30(97.421274%). If I delete the higher quality read(eg. -q 38 -u 5), the final file size will be 0.
> In addition, I found that using MitoZ.py all or assemble will have a *.partial_fastq.
> MitoZ.py all have *.cleandata.
> Isn't this shrinking the data?
> How can I further reduce the data size？
> What tool do you use to get part of the file content？ @linzhi2013

Dear zskysfe,

Sorry that I did not realize that you're using MitoZ-2.4-alpha.

MitoZ-2.4-alpha version internally extracts 5Gbp data for the `all` or `all2` command with a Python script, and the result files are `*.partial_fastq`, which will be used to mitochondrial assembly. This change is to avoid using all input data in case some users providing too much data and getting crash.

therefore, if things go well, given your computer resources available (workstation has 48 CPUs and 250G memory), you should not have a problem with the command `/apps/MitoZ_v2.4/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 6`.

Could you please check if there is some file like `core.XXX` in the `tmp/prefix.assembly` directory?

1. you can use this command to extract part of the data https://github.com/linzhi2013/extractfq.

2. if you do not like the `*.partial_fastq` files to be generated, you may use MitoZ-v2.3.

**Comment by zskysafe** [comment]
> 
> 
> > Dear linzhi2013
> > I use fastp -q 37 -u 5 to filter the fq.gz. This means that the Q less than 37 is low quality, and the read that have five percent of the low quality will be deleted.
> > The result is Q30(97.421274%). If I delete the higher quality read(eg. -q 38 -u 5), the final file size will be 0.
> > In addition, I found that using MitoZ.py all or assemble will have a *.partial_fastq.
> > MitoZ.py all have *.cleandata.
> > Isn't this shrinking the data?
> > How can I further reduce the data size？
> > What tool do you use to get part of the file content？ @linzhi2013
> 
> Dear zskysfe,
> 
> Sorry that I did not realize that you're using MitoZ-2.4-alpha.
> 
> MitoZ-2.4-alpha version internally extracts 5Gbp data for the `all` or `all2` command with a Python script, and the result files are `*.partial_fastq`, which will be used to mitochondrial assembly. This change is to avoid using all input data in case some users providing too much data and getting crash.
> 
> therefore, if things go well, given your computer resources available (workstation has 48 CPUs and 250G memory), you should not have a problem with the command `/apps/MitoZ_v2.4/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 6`.
> 
> Could you please check if there is some file like `core.XXX` in the `tmp/prefix.assembly` directory?
> 
>     1. you can use this command to extract part of the data https://github.com/linzhi2013/extractfq.
> 
>     2. if you do not like the `*.partial_fastq` files to be generated, you may use MitoZ-v2.3.


*.tmp/*.assembly/work71.soaptrans.lib
Only this file in this folder

**Comment by zskysafe** [comment]
> 
> 
> > Dear linzhi2013
> > I use fastp -q 37 -u 5 to filter the fq.gz. This means that the Q less than 37 is low quality, and the read that have five percent of the low quality will be deleted.
> > The result is Q30(97.421274%). If I delete the higher quality read(eg. -q 38 -u 5), the final file size will be 0.
> > In addition, I found that using MitoZ.py all or assemble will have a *.partial_fastq.
> > MitoZ.py all have *.cleandata.
> > Isn't this shrinking the data?
> > How can I further reduce the data size？
> > What tool do you use to get part of the file content？ @linzhi2013
> 
> Dear zskysfe,
> 
> Sorry that I did not realize that you're using MitoZ-2.4-alpha.
> 
> MitoZ-2.4-alpha version internally extracts 5Gbp data for the `all` or `all2` command with a Python script, and the result files are `*.partial_fastq`, which will be used to mitochondrial assembly. This change is to avoid using all input data in case some users providing too much data and getting crash.
> 
> therefore, if things go well, given your computer resources available (workstation has 48 CPUs and 250G memory), you should not have a problem with the command `/apps/MitoZ_v2.4/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 6`.
> 
> Could you please check if there is some file like `core.XXX` in the `tmp/prefix.assembly` directory?
> 
>     1. you can use this command to extract part of the data https://github.com/linzhi2013/extractfq.
> 
>     2. if you do not like the `*.partial_fastq` files to be generated, you may use MitoZ-v2.3.

.tmp/.assembly/work71.soaptrans.lib
Only this file in this folder
I think the *.partial_fastq files is useful.

**Comment by zskysafe** [comment]
.tmp/.assembly/work71.soaptrans.lib
Only this file in this folder
no file like core.XXX in the tmp/prefix.assembly directory

![图片](https://user-images.githubusercontent.com/51896128/72218574-19e46400-3577-11ea-89ce-7a18684fe12a.png)

**Comment by linzhi2013** [comment]
> .tmp/.assembly/work71.soaptrans.lib
> Only this file in this folder
> no file like core.XXX in the tmp/prefix.assembly directory
> 
> ![图片](https://user-images.githubusercontent.com/51896128/72218574-19e46400-3577-11ea-89ce-7a18684fe12a.png)

Hi zskysfe,

Have you tried to run the following command in that `prefix.assembly` directory alone?

`/apps/MitoZ_v2.4/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 6 >a.log 2>a.err`

If it fails again, please send me the `a.log` and `a.err` files.

thanks!

**Comment by zskysafe** [comment]
> 
> 
> > .tmp/.assembly/work71.soaptrans.lib
> > Only this file in this folder
> > no file like core.XXX in the tmp/prefix.assembly directory
> > ![图片](https://user-images.githubusercontent.com/51896128/72218574-19e46400-3577-11ea-89ce-7a18684fe12a.png)
> 
> Hi zskysfe,
> 
> Have you tried to run the following command in that `prefix.assembly` directory alone?
> 
> `/apps/MitoZ_v2.4/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 6 >a.log 2>a.err`
> 
> If it fails again, please send me the `a.log` and `a.err` files.
> 
> thanks!
It's strange that there was always this error when it came to this step.
But there's no problem with what you say.
I don't know why.
[a.log](https://github.com/linzhi2013/MitoZ/files/4079900/a.log)

**Comment by linzhi2013** [comment]
Hi zskysafe,

the `a.log` file seems good, and I do not know what was going on neither.

Maybe you can send me the fastq files you used, as well as the commands you used. I can give it a try.

You can send them to my email linzhi2012<MitoZ>gmail<MitoZ>com. (please replace the "MitoZ" with correct chars).

cheers
