### ISSUE TITLE
Nanopore sequence for Mitochondrial genome assembly?

### ISSUE THREAD

**Issue by linzhi2013** [linzhi2013/MitoZ#160]
I'm using mitoZ for mitochondrial genome assembly. I'm just wondered
whether this tool will accept Nanopore sequence for Mitochondrial genome
assembly.

_Originally posted by @dhananyashunmugam in https://github.com/linzhi2013/MitoZ/issues/158#issuecomment-1245164351_

**Comment by linzhi2013** [comment]
Hi @dhananyashunmugam, thanks for your interest in MitoZ! Unfortunately, the current version of MitoZ doesn't accept  Nanopore data as input, due to the high error rates in these reads and longer length.

But yes, support of PacBio and Nanopore data will be great. Let me see if I can add this feature in the later versions.

Cheers
Guanliang

**Comment by dhananyashunmugam** [comment]
Okay.. Thank you

**Comment by Phismil** [comment]
Thanks @linzhi2013 for maintaining the repository.
Is it recommended to use the assembler with longer Illumina reads (i.e. 2x250 bp) instead of standard 2x150 bp?
Thank you in advance

**Comment by dhananyashunmugam** [comment]
Okay Thank you
