### ISSUE TITLE
 Is longer Illumina reads or shorter reads preferred?

### ISSUE THREAD

**Issue by linzhi2013** [linzhi2013/MitoZ#161]
Is it recommended to use the assembler with longer Illumina reads (i.e. 2x250 bp) instead of standard 2x150 bp?
Thank you in advance

_Originally posted by @Phismil in https://github.com/linzhi2013/MitoZ/issues/160#issuecomment-1259680867_

**Comment by linzhi2013** [comment]
Hi @Phismil, theoretically, the longer NGS reads are better, as they can better circumvent the small repeats because you can use larger kmers, and thus simpler DGB graphs and better results in the end.

**Comment by Phismil** [comment]
Thanks you for your response @linzhi2013.

**Comment by linzhi2013** [comment]
you're welcome!
