### ISSUE TITLE
mitoz visualize -h

### ISSUE THREAD

**Issue by deyuanyang** [linzhi2013/MitoZ#162]
$ mitoz visualize -h
usage: mitoz visualize [-h] [--circos <str>] --gb <file> [--gc {yes,no}]
                       [--win <str>] [--gc_fill <str>] [--depth_file <file>]
                       [--run_map {yes,no}] [--fq1 <file>] [--fq2 <file>]
                       [--bwa <str>] [--thread <int>] [--samtools <str>]
                       [--opts_samtools <str>] [--depth_fill <str>]
                       [--cds_color <str>] [--trna_color <str>]
                       [--rrna_color <str>] [--label_color <str>]
                       [--locus_color <str>] [--base {yes,no}] [--bgc <str>]
                       [--outdir <str>]

請教下，這一步生成的圖片，可以生成svg？ 我運行結果中只有png格式的圖片。 蒙老師有空可以增加下更改圖片的格式的參數嗎？

**Comment by linzhi2013** [comment]
Hi deyuan,

which version of MitoZ did you use?

I tried v3.4:

```bash
$ mitoz visualize --gb DM01_DM01.megahit.mitogenome.fa_mitoscaf.fa.gbf
```

And I got:
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/6203542/193118918-7ef85cf6-c36e-4972-be35-5f6c3e7a2d0b.png">

**Comment by deyuanyang** [comment]
Hi Meng,

Many thanks!  Sorry for reply you later.

Yang

**Comment by linzhi2013** [comment]
No worries.

Cheers
