### ISSUE TITLE
How to introduce breakpoints?

### ISSUE THREAD

**Issue by parmardrashti** [linzhi2013/MitoZ#166]
## How to introduce breakpoints in fasta file in order to complete the incompletely annotated genes?

# Log messages from MitoZ (stdout and stderr)

**Comment by linzhi2013** [comment]
Maybe you can check this part: https://github.com/linzhi2013/MitoZ/wiki/Tutorial#6-broken-genes
<img width="991" alt="image" src="https://user-images.githubusercontent.com/6203542/196400024-8ecdd111-a284-4d80-b077-69c0ac2cfb2c.png">

And this  https://github.com/linzhi2013/MitoZ/wiki/The-%27mitoz-tools-gbfiletool%27-command

`mitoz-tools gbfiletool` is only avaialable in the MitoZ 3.5-beta versions (https://github.com/linzhi2013/MitoZ/releases/tag/3.5-beta-1).
