### ISSUE TITLE
overlap_information file empty and mitogenomes not circularised

### ISSUE THREAD

**Issue by lesserof2weevils** [linzhi2013/MitoZ#167]
Hello, 

I'm having a few issues running mitoZ v 3.4. I've been using the all with megahit, all data, and Kmers 59 to 141 command to go from raw data to complete mtGenome, and for several datasets it works great. However, on some sequence data it seems like the mitogenome is assembled in a linear format and not circularised and the overlap_information file is empty. The file is made but there is no data there. I've attached a log file from one of the failed assemblies.

What would be the best fix for this? Should I try re-running the assembly with a different assembler or is there a way to circularise the assembly that I already have?

Best, 
James 
[mitoz.log](https://github.com/linzhi2013/MitoZ/files/9804934/mitoz.log)

**Comment by linzhi2013** [comment]
Hi James,

`the overlap_information file is empty` means the assembled mitogenome is not complete, and thus there is no overlapping region at the beginning and end of the sequence.

You can try different kmers, especially smaller kmers. Or  try a different assembler in MitoZ.

Cheers
Guan
