### ISSUE TITLE
How to make cirular map to linear?

### ISSUE THREAD

**Issue by deyuanyang** [linzhi2013/MitoZ#168]
Hi, Meng,

Sorry for disrupting you.

MitoZ is  an amazing soft, and I have derived much benefit from it.

Can you add some functions to make a circular map into a linear map when using Mitoz annotation if you have available time? I think it would be easier when comparing the quality of many sequence sequences together.

All the best, Yang

![Uploading image.png…]()

**Comment by linzhi2013** [comment]
Hi Yang,

thanks for the suggestion! I will think about it when I have more time.

The Circos (http://circos.ca/) software is to make circular plots.

You can also try to draw linear graphs by following http://biopython.org/DIST/docs/tutorial/Tutorial.html first (the **Chapter ‍17 Graphics including GenomeDiagram** section) .
