### ISSUE TITLE
Open Reading Frame

### ISSUE THREAD

**Issue by timz0605** [linzhi2013/MitoZ#170]
Hello, just a quick question. I wonder if MitoZ can detect an open reading frame (orf) and show it in the final output?

**Comment by linzhi2013** [comment]
Hi @timz0605 ,

MitoZ has the ability to perform the annotation of any PCGs, but the usage of the current version of MitoZ is difficult for that purpose. I hope that I can address this problem in the next version.

There is other software designed for ORF prediction.

Cheers
