### ISSUE TITLE
Annotation of Gene on Both Sides of Start and End Position Got Cut Off

### ISSUE THREAD

**Issue by timz0605** [linzhi2013/MitoZ#173]
# Problem description

Hello!

I noticed this issue when I was looking at the final output of the circular mitochondrial genome in Geneious. When 1 gene, ND4 for example, falls on both sides of the start and end position of a circular mitochondrial genome, MitoZ will break it into 2 separate annotations. 

Sometimes, only the first part of a gene is annotated. For example, the length of ND4 for animals I am looking at is approx. 1300 bp long. However, if the program identifies somewhere in the middle of the gene as a start and end position of the circular mitochondrial genome, only one part of 900 bp is being annotated. The other 400 bp part will be left out and not annotated. 

In this situation, I am wondering how the program deals with annotations for a gene that happens to be crossing the start and end positions.

Thank you!
![issue](https://user-images.githubusercontent.com/114772844/206538060-39ad082d-d2b0-40d3-846c-306545e74dc6.JPG)

![issue 2](https://user-images.githubusercontent.com/114772844/206538329-396be3a1-295e-466f-b8c4-3b3716c197c0.JPG)

**Comment by linzhi2013** [comment]
Hello!

Have a look at https://github.com/linzhi2013/MitoZ/wiki/Tutorial#6-broken-genes .

You can simply break the circular mitogenome at another breaking point without genes around and then reannotate the whole sequence with MitoZ (the `mitoz annotate`)

Cheers
