### ISSUE TITLE
Mitoz is not working in different directory

### ISSUE THREAD

**Issue by asifratul** [linzhi2013/MitoZ#176]
## MitoZ version?
3.4

## How did you install MitoZ? (e.g. Docker, Udocker, Singularity, Conda-Pack, Conda, or source code)
conda-pack (cannot dockers are showing some issues)

## Did you run a test after your installation, and was the test run okay?
yes. I make a test folder inside the home directory. 
and it worked well. when I mount in another directory, the test dataset is not working.

## The command you used?

source ~/mitoz3.4/bin/activate
cd /mnt/e/AsifAnalysis/mitoZ/test
mitoz all --fq1 test.1.fq.gz  --fq2 test.2.fq.gz --outprefix ttt --clade Arthropoda --data_size_for_mt_assembly 0 --assembler megahit --requiring_taxa Arthropoda

## Problem description
HI, 

I am getting problem frequently. I install the conda-pack, as the dockers are not being installed in my ubuntu 18.02.5 (installed on windows). When I first ran the soft for test data, it work well in home directory. But when I change the directory to separate folder, it is giving errors. 

I assume, there might be issues in different directory. 
I then copy my fastq files in the test folder in home directory, but it is also giving same errors.
can you please let me know, what can I do?

# Log messages from MitoZ (stdout and stderr)
[mitoz.log](https://github.com/linzhi2013/MitoZ/files/10306158/mitoz.log)

**Comment by asifratul** [comment]
Seeming, spades assembler is working! anyway to fix the megahit issue?

[mitoz.log](https://github.com/linzhi2013/MitoZ/files/10306256/mitoz.log)

**Comment by linzhi2013** [comment]
Hi Asifratul,

About the Megahit, can you excute the command within the enviroment?

```
megahit  --out-dir ./megahit_out  --num-cpu-threads 8 --k-list 21,29,39,59,79,99,119,141 --memory 500000000000.0 -1 /mnt/e/AsifAnalysis/mitoZ/test/clean_data/ttt.clean_R1.fq.gz -2 /mnt/e/AsifAnalysis/mitoZ/test/clean_data/ttt.clean_R2.fq.gz  >megahit.log 2>megahit.err
```

and see what is in `megahit.log ` and `megahit.err`.

**Comment by asifratul** [comment]
Getting the same errors!

[megahit.err.txt](https://github.com/linzhi2013/MitoZ/files/10307632/megahit.err.txt)

**Comment by linzhi2013** [comment]
> Getting the same errors!
> 
> [megahit.err.txt](https://github.com/linzhi2013/MitoZ/files/10307632/megahit.err.txt)

thanks!

Seems to be related to your file system. Similar problems have been raised on https://github.com/nmquijada/tormes/issues/21 and https://github.com/voutcn/megahit/issues/303 and https://groups.google.com/g/3d-genomics/c/UQLyV2nDISQ

On the third link, they suggest 
>It's possible that your environment is configured to use a different temp directory instead of "/tmp" so try to find it using "env |grep -i tmp" command. If you see an environment variable defined like TMPDIR (or something similar) then use "--tmp-dir $TMPDIR" instead of "--tmp-dir /tmp"

**Comment by asifratul** [comment]
Hi @linzhi2013, 

adding "--tmp-dir /tmp" within the maghit command works perfectly! Many thanks, much appreciated.
Is there any way to add this temp directory command within "mitoz all" command ?

ASIF

**Comment by linzhi2013** [comment]
Hi ASIF,

that's great.

You can find the megahit commands in the `assembly.py` file:
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/6203542/209685490-55f2c731-a762-4ee8-950a-5f48f2b12c1a.png">

```python
    if resume:
        command = "megahit --continue --out-dir ./megahit_out "
        runcmd(command, logger=logger)
    else:
        if fq1 and fq2:
            command = "megahit " +\
                " --out-dir ./megahit_out "+\
                " --num-cpu-threads " + thread_number +\
                " --k-list " + kmers +\
                " --memory " + str(memory) +\
                " -1 " + fq1 +\
                " -2 " + fq2
        else:
            command = "megahit " +\
                " --out-dir ./megahit_out " +\
                " --num-cpu-threads " + thread_number +\
                " --k-list " + kmers +\
                " --memory " + str(memory) +\
                " --read " + fq1
        runcmd(command, logger=logger)
```

And then add `--tmp-dir /tmp` to the above megahit commands.

**Comment by linzhi2013** [comment]
I will incorporate such an option into MitoZ in subsequent releases. thanks again for your reporting!

**Comment by asifratul** [comment]
Hi @linzhi2013 ,

Thanks for the code. I have incorporated your codes in assembly.py. but still, it is giving the same error! 

![image](https://user-images.githubusercontent.com/40979705/209718431-b23251ea-aa11-4ab0-91c4-f0b1c97db390.png)

**Comment by linzhi2013** [comment]
> defined like TMPDIR (or something similar) then use "--tmp-dir $TMPDIR" instead of "--tmp-dir /tmp"

I see. Maybe you have used the wrong way because the google group says `defined like TMPDIR (or something similar) then use "--tmp-dir $TMPDIR"` **instead of** `--tmp-dir /tmp"`

**Comment by asifratul** [comment]
Hi @linzhi2013, 

I might not get your suggestion properly. what I have done is -

a. added your megahit codes in assembly.py file, with --temp-dir $TMPDIR (see below).
b. then run --> export TMPDIR=./megatemp && mitoz all --fq1 test.1.fq.gz --fq2 test.2.fq.gz --outprefix ttt --clade Arthropoda --data_size_for_mt_assembly 0 --assembler megahit --requiring_taxa Arthropoda

but still getting the same error!  Am I doing something wrong?

ASIF

[mitoz.log](https://github.com/linzhi2013/MitoZ/files/10313201/mitoz.log)


![image](https://user-images.githubusercontent.com/40979705/209785514-aa3eecaf-5a31-420c-b132-05273d33cf68.png)

**Comment by linzhi2013** [comment]
I don't know if you have to create the `TMPDIR` directory before using it (I suppose you need to).

The another thing I am not so sure is if the  `TMPDIR`  variable can be passed to the megahit command with MitoZ using the above method.

I would suggest not use the `TMPDIR` variable method, but using  thehard-code way:

Firstly, create the path of a tmp directory:
```bash
mkdir /your/custom/tmp/path
```

Then replace the `--tmp-dir $TMPDIR` in the `assembly.py` file with  `--tmp-dir  /your/custom/tmp/path`.

Also don't forget to do the same thing with 
<img width="589" alt="image" src="https://user-images.githubusercontent.com/6203542/209820431-29ea81b6-8023-4b78-8db1-aea2897135e4.png">

**Comment by linzhi2013** [comment]
See https://github.com/linzhi2013/MitoZ/releases/tag/3.5
