### ISSUE TITLE
samtools in draw_circos_for_mitogenome_auto_depth.pl line 138

### ISSUE THREAD

**Issue by xiekunwhy** [linzhi2013/MitoZ#177]
Hi,

I think samtools in draw_circos_for_mitogenome_auto_depth.pl line 138 should be "print MAP \"\$bwa mem -t \$conf\{\'threads\'\} \$outdir/circos.mito.fa \$fq1  \$fq2 |**\$samtools** view -bS -q 30 -h -o \$outdir/circos.bam\n\";", but it is "print MAP \"\$bwa mem -t \$conf\{\'threads\'\} \$outdir/circos.mito.fa \$fq1  \$fq2 |**samtools** view -bS -q 30 -h -o \$outdir/circos.bam\n\";" now.

Best,
Kun

**Comment by linzhi2013** [comment]
Hi Kun,

thanks for the message.

You are right, `samtools` should be `$samtools`.

but luckily, whenever we are in the `mitozEnv` environment, both `samtools`  and `$samtools` will work.

**Comment by linzhi2013** [comment]
Hi Kun,

Agree, `$samtools` will always work.

Could you please indicate when `samtools` alone doesn't work? Like when submitting the job to an SGE cluster to run? I am just curious about it, I will change the code to `$samtools` in later releases. Maybe in some situations when executing the above commands the current environmental variables (i.e., `$PATH`) were not inherited.

**Comment by linzhi2013** [comment]
See https://github.com/linzhi2013/MitoZ/releases/tag/3.5
