### ISSUE TITLE
A suggestion for findmitoscaf program design

### ISSUE THREAD

**Issue by comery** [linzhi2013/MitoZ#18]
The program "_findmitoscaf_" is a very convenient tool to find mitochondrial scaffolds. It calculates the mapping depth of each scaffold and employs HMM search against a protein database. Obviously, HMM searching is faster than BWA mapping, so I think you could do HMM first to avoid much computational consumption.

**Comment by linzhi2013** [comment]
fixed in MitoZ 3.0.
