### ISSUE TITLE
makeblastdb error with MitoZ3.5 using Singularity

### ISSUE THREAD

**Issue by bheimbu** [linzhi2013/MitoZ#180]
Hi @linzhi2013,

I'm having troubles running MitoZ3.5 with Singularity, everything works until makeblastdb comes into play:

`makeblastdb -in ttt.megahit.hmmtblout.besthit.sim.fa -dbtype nucl
Error: mdb_dbi_open: MDB_NOTFOUND: No matching key/data pair found
run the tblastn shell file
Error: mdb_dbi_open: MDB_NOTFOUND: No matching key/data pair found
`
I verified that makeblastdb is there: `Singularity> which makeblastdb
/app/anaconda/bin/makeblastdb
`

Did you encounter anything like that before?

Strangely, if I use `makeblastdb version 2.5.1`, I get no error, when I use `makeblastdb -in ttt.megahit.hmmtblout.besthit.sim.fa -dbtype nucl`. That's why, is there any way to specify a different version of blast.

Cheers Bastian

**Comment by linzhi2013** [comment]
Hi Bastian,

When I tried the Docker version of MitoZ on Mac (M1), it works.

```
2023-01-26 15:02:38,588 - mitoz.utility.utility - INFO -
export WISECONFIGDIR=/app/anaconda/share/wise2/wisecfg
perl /app/anaconda/lib/python3.9/site-packages/mitoz-3.5-py3.9.egg/mitoz/annotate/script/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl -i /Users/gmeng/Downloads/mitoz-3.5/test_data/annot/t1/tmp_ttt_work71.mitogenome.fa_mitoscaf.fa/ttt_work71.mitogenome.fa_mitoscaf.fa -d /app/anaconda/lib/python3.9/site-packages/mitoz-3.5-py3.9.egg/mitoz/profiles/MT_database/Arthropoda_CDS_protein.fa -o ./ -g 5 -cpu 8


makeblastdb -in /Users/gmeng/Downloads/mitoz-3.5/test_data/annot/t1/tmp_ttt_work71.mitogenome.fa_mitoscaf.fa/ttt_work71.mitogenome.fa_mitoscaf.fa -dbtype nucl
run the tblastn shell file
Warning: [tblastn] Number of threads was reduced to 4 to match the number of available CPUs
```

I don't have a machine to test the singularity version yet. Maybe you can try to install MitoZ from the source or conda and specify a different version of Blast+.

Cheers
Guan

**Comment by bheimbu** [comment]
HI, sorry for not getting back to you earlier. I was able to run mitoz3.5 with an mamba installation and loaded a different version (2.5.1+) of `ncbi-tools` on our HPC. Thx for the suggestion.

Cheers Bastian

**Comment by linzhi2013** [comment]
> HI, sorry for not getting back to you earlier. I was able to run mitoz3.5 with an mamba installation and loaded a different version (2.5.1+) of `ncbi-tools` on our HPC. Thx for the suggestion.
> 
> Cheers Bastian

No problem. Good to know that!

Cheers
Guanliang
