### ISSUE TITLE
When using mitoz visualize --depth_file, there is no depth track in the resulting image

### ISSUE THREAD

**Issue by Liuxuanzeng** [linzhi2013/MitoZ#183]
Hello Lin,
I'm having some problems using the mitoz visualize --depth_file command, and would like some help.
I run the command is 
 mitoz visualize --gb xyx_mt_02out_xyx_mt_02out.megahit.mitogenome.fa_mitoscaf.fa.gbf --depth_file xya_depth.txt --outdir xya_test

xya_depth.txt is a file I built myself, as shown here
![图片](https://user-images.githubusercontent.com/109024718/224871464-8fcfd730-5310-4e86-9f91-39034a278ffd.png)
![图片](https://user-images.githubusercontent.com/109024718/224871496-5081fde6-424b-4cc4-b034-c26f036f3651.png)

This two depth_file, I tried input respectively, but the resulting graph did not have the depth track.And the circos.dept.txt file in the result file is blank.
![图片](https://user-images.githubusercontent.com/109024718/224871541-8b740abc-bc05-4103-9ca7-1821c4342577.png)
![图片](https://user-images.githubusercontent.com/109024718/224871575-af5f2a18-a8e8-461d-91b1-9c591d2c970d.png)
The above is the result image and the result folder. I used MitoZ3.4 and 3.5 respectively to try, and there was no depth track in the image.
I wasn't sure what was wrong and wanted help. Thank you very much!

Liuxuanzeng

**Comment by linzhi2013** [comment]
Hi Liuxuanzeng, 

Could you please try to use the **absolute paths** to the files?

**Comment by Liuxuanzeng** [comment]
Hi Lin,
Thank you for your help. I tried to use the absolute path, this problem has been solved. Sorry to trouble you with such a stupid mistake. Thank you very much.

Liuxuanzeng

**Comment by linzhi2013** [comment]
Hi Liuxuanzeng,

No, I am pleased that you raised the issue, I should have converted the (relative) path of input files into an absolute path in MitoZ. I will fix it at the next release.

Cheers
Guan

**Comment by linzhi2013** [comment]
Fixed on https://github.com/linzhi2013/MitoZ/releases/tag/3.6
