### ISSUE TITLE
No QC.json file generated and run truncated

### ISSUE THREAD

**Issue by njbayonav** [linzhi2013/MitoZ#184]
## on which platform/server? (Windows? Windows Sublinux? MacOS? Ubuntu? etc.)
MacOS
## MitoZ version?
3.5
## How did you install MitoZ? (e.g. Docker, Udocker, Singularity, Conda-Pack, Conda, or source code)
Docker
## Did you run a test after your installation, and was the test run okay?
Yes
## The command you used?
docker run -v $PWD:$PWD -w $PWD --rm guanliangmeng/mitoz:3.5  mitoz all --fq1 Whale_1_2_1.fastq.gz --fq2 Whale_1_2_2.fastq.gz --outprefix whale --clade Chordata --data_size_for_mt_assembly 0 --assembler megahit --requiring_taxa Chordat
## Problem description
I have tried to run MitoZ 3.5 using megahit and using MitoZ (default), however, in both occasions I got the error: "No such file or directory: '/path_to_working_directory/clean_data/whale.QC.json'. Does it mean that no data passed the quality filter? Is there any parameter I can use to try a less restrictive quality filter just to make sure this is the source of the problem? It is worth mentioning that the whale.clean_R1.fq.gz and whale.clean_R1.fq.gz are each ~5Gb in size, so it tells me there is clean data to move forward.

## Log messages from MitoZ (stdout and stderr)
Killed
Traceback (most recent call last):
  File "/app/anaconda/bin/mitoz", line 33, in <module>
    sys.exit(load_entry_point('mitoz==3.5', 'console_scripts', 'mitoz')())
  File "/app/anaconda/lib/python3.9/site-packages/mitoz-3.5-py3.9.egg/mitoz/MitoZ.py", line 99, in main
    args.func(args)
  File "/app/anaconda/lib/python3.9/site-packages/mitoz-3.5-py3.9.egg/mitoz/all/all.py", line 308, in main
    filtered_fq1, filtered_fq2 = mitoz.filter.main(filter_args)
  File "/app/anaconda/lib/python3.9/site-packages/mitoz-3.5-py3.9.egg/mitoz/filter/filter.py", line 290, in main
    actual_clean_data_size = get_clean_data_size(fastp_json_file=report_json, logger=logger)
  File "/app/anaconda/lib/python3.9/site-packages/mitoz-3.5-py3.9.egg/mitoz/filter/filter.py", line 215, in get_clean_data_size
    with open(fastp_json_file, 'r') as fh:
    FileNotFoundError: [Errno 2] No such file or directory: '/Users/oxfordlab/Documents/whale/clean_data/whale.QC.json'
[mitoz.log](https://github.com/linzhi2013/MitoZ/files/11070644/mitoz.log)

**Comment by linzhi2013** [comment]
Hello,

Please ensure that both `Whale_1_2_1.fastq.gz` and `Whale_1_2_2.fastq.gz ` are in your `$PWD` directory, i.e., the two files are in the same directory as where you ran the above command.

Also, use ` --requiring_taxa Chordata` instead of ` --requiring_taxa Chordat`
