### ISSUE TITLE
parameters_parser SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by xiekunwhy** [linzhi2013/MitoZ#185]
Hi,

I got SyntaxError when install mitoZ.

source ~/miniconda3/bin/activate mitozEnv
~/miniconda3/envs/mitozEnv/bin/python3 setup.py install
byte-compiling build/bdist.linux-x86_64/egg/mitoz/utility/__init__.py to __init__.cpython-311.pyc
byte-compiling build/bdist.linux-x86_64/egg/mitoz/utility/parameters_parser.py to parameters_parser.cpython-311.pyc
  File "build/bdist.linux-x86_64/egg/mitoz/utility/parameters_parser.py", line 100
    metavar="<INT>", default=71, nargs="+",,
                                           ^
SyntaxError: invalid syntax

creating /home/kxie/miniconda3/envs/mitozEnv/lib/python3.11/site-packages/mitoz-3.5-py3.11.egg
Extracting mitoz-3.5-py3.11.egg to /home/kxie/miniconda3/envs/mitozEnv/lib/python3.11/site-packages
  File "/home/kxie/miniconda3/envs/mitozEnv/lib/python3.11/site-packages/mitoz-3.5-py3.11.egg/mitoz/utility/parameters_parser.py", line 100
    metavar="<INT>", default=71, nargs="+",,
                                           ^
SyntaxError: invalid syntax

Are there really SyntaxError?

Best,
Kun

**Comment by xiekunwhy** [comment]
Python 3.9 also not works
byte-compiling build/bdist.linux-x86_64/egg/mitoz/tools/to_be_integrated/Mitogenome_reorder.py to Mitogenome_reorder.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/mitoz/utility/__init__.py to __init__.cpython-39.pyc
byte-compiling build/bdist.linux-x86_64/egg/mitoz/utility/parameters_parser.py to parameters_parser.cpython-39.pyc
  File "build/bdist.linux-x86_64/egg/mitoz/utility/parameters_parser.py", line 100
    metavar="<INT>", default=71, nargs="+",,
                                           ^
SyntaxError: invalid syntax

Processing mitoz-3.5-py3.9.egg
creating /home/kxie/miniconda3/envs/mitozEnv/lib/python3.9/site-packages/mitoz-3.5-py3.9.egg
Extracting mitoz-3.5-py3.9.egg to /home/kxie/miniconda3/envs/mitozEnv/lib/python3.9/site-packages
  File "/home/kxie/miniconda3/envs/mitozEnv/lib/python3.9/site-packages/mitoz-3.5-py3.9.egg/mitoz/utility/parameters_parser.py", line 100
    metavar="<INT>", default=71, nargs="+",,
                                           ^
SyntaxError: invalid syntax

**Comment by linzhi2013** [comment]
<img width="941" alt="image" src="https://user-images.githubusercontent.com/6203542/229376515-5763c932-3320-4def-baf2-771382d79935.png">


You can edit the source of MitoZ to remove the error (to remove the comma).

I don't know why I didn't get the complaint before, it's very straightforward to fix it.

Thanks for report the issue!

**Comment by linzhi2013** [comment]
Fixed on https://github.com/linzhi2013/MitoZ/releases/tag/3.6
