### ISSUE TITLE
Dear tearcher Meng, i have some questions about circularity 

### ISSUE THREAD

**Issue by xjt1234** [linzhi2013/MitoZ#189]
Hello Mr. Meng, sorry to bother you in your busy schedule, I found that when I assembled and annotated the mitochondrial whole genome of Butterfly, the result of my assembly with mitoassemble contains the complete mitochondrial genome, but the loop test did not pass, I checked Github and you mentioned that there are other scripts that can be used to perform the loop test, I don't know how it works. I don't know how to run it? Here is the code I ran: 
```
nohup mitoz all --genetic_code 5 --outprefix scorpionfly_mito_2_ZND \
--thread_number 40 \
--fq1 /home/data/t200301/hll/reassemble/ZND/4_ZND_1_clean.fq.gz \
--fq2 /home/data/t200301/hll/reassemble/ZND/4_ZND_2_clean.fq.gz \
--fastq_read_length 150 --insert_size 250 \
--requiring_taxa "Arthropoda" \
--skip_filter \
--assembler mitoassemble \
--memory 150 &
```
![QQ截图20230418092239](https://user-images.githubusercontent.com/95855039/232645095-536a402c-461f-4828-b38a-49ea0a1e2778.png)
![QQ图片20230418092310](https://user-images.githubusercontent.com/95855039/232645105-452d35dc-eb2b-452b-98a4-843a9637904a.png)

And I found that I can't assemble the complete mitochondrial genome by using Megahit in a different assembly method, is it necessary to set the kmer parameters in this assembly software. Please take a look at it, thank you very much!

**Comment by linzhi2013** [comment]
Hi, 

Could you please tell me what your definition of "complete" is? With all 37 genes found?


You can open the resulting mitogenome fasta file using MEGA, and check if the sequence has an identical sequence at the 5'-end and 3'-end.

**Comment by xjt1234** [comment]
Yes, i mean 37genes found. But the circularity is no. Is that means this result can not be used, i should use the other way or change the parameters to reassemble these clean data?

**Comment by xjt1234** [comment]
I found that in circularity problem and its solution, you said we could use another circularity check script.

**Comment by xjt1234** [comment]
OK, very very thankful.

**Comment by xjt1234** [comment]
By the way,  where can I find the list of kmer? I want to try more parameters

**Comment by linzhi2013** [comment]
> By the way, where can I find the list of kmer? I want to try more parameters

You can invent them by yourself: odd numbers no larger than your read length. For example, 39 59 79 or even 99 or 199.

If you are using megahit, the differences of adjacent kmers must be <= 28.

**Comment by xjt1234** [comment]
Thank you very much!!!
