### ISSUE TITLE
Error in annotate module

### ISSUE THREAD

**Issue by Asyantias** [linzhi2013/MitoZ#19]
Dear Guanliang Meng:
I've got a mitochondrial assembly file through MitoZ, and rearrangement of fasta file basing on reference mitogeome. When i  use the Mitoz annotate module to annotate and visualize the new fasta file, its reported err.

I been try it under docker envs (ubuntu-18.04.1 both mitoZ-2.3 and mitoZ-2.4-alpha), also used different input file(rearranged mitochondrial fasta file generated by Mitogenome_reorder.py, original assembly file generated by MitoZ-2.3 all2 , another mitogeome download from NCBI ), almost same errors here.

Here is the Log file. 
[anno.log](https://github.com/linzhi2013/MitoZ/files/3524767/anno.log)
The input file is generated by mitoZ-2.3 with following command.
```bash
python3 /app/release_MitoZ_v2.3/MitoZ.py all2 --genetic_code 2 --clade Chordata --outprefix ${g}_${b} \
--thread_number 20 \
--fastq1 ./${g}_${b}_R1.fq.gz \
--fastq2 ./${g}_${b}_R2.fq.gz \
--fastq_read_length 150 \
--insert_size 250 \
--run_mode 2 \
--filter_taxa_method 1 \
--requiring_taxa 'Rodentia' \
1>${g}_${b}.log 2>${g}_${b}.err
```

thanks

**Comment by comery** [comment]
I think you may give a wrong Log file, I can see a line just like below:
 >"GaoHongMei:GaoHongMei931200:8121009:3812:GaoHongMei:/home/GaoHongMei:/bin/bash"

is that what you want to show us ?

**Comment by Asyantias** [comment]
> I think you may give a wrong Log file, I can see a line just like below:
> 
> > "GaoHongMei:GaoHongMei931200:8121009:3812:GaoHongMei:/home/GaoHongMei:/bin/bash"
> 
> is that what you want to show us ?

OMG, sorry, my bad.

**Comment by linzhi2013** [comment]
Hi Asynatias,

Could you please show us the detailed `annotate` command you used? And the log file?

The rearrangment should not have impact on the `annotate`.

But beware that the sequence id of your input fasta file for `annotate` should be short. If that's the case, you can rename the sequence id firstly.


Cheers,
Guanliang

**Comment by Asyantias** [comment]
> Hi Asynatias,
> 
> Could you please show us the detailed `annotate` command you used? And the log file?
> 
> The rearrangment should not have impact on the `annotate`.
> 
> But beware that the sequence id of your input fasta file for `annotate` should be short. If that's the case, you can rename the sequence id firstly.
> 
> Cheers,
> Guanliang

Hi Guangliang:

Thanks for reply.
I followed your suggestion to short the ID of my input fasta file, and totally work! 
Many Thanks.

**Comment by linzhi2013** [comment]
Glad to hear that!

I'm going to close ths issue. Any feedback on MitoZ is greatly welcomed, please feel free to open new issues if you have questions.


Cheers,
Guanliang
