### ISSUE TITLE
这个软件可以用于植物叶绿体、线粒体，真菌的线粒体吗？

### ISSUE THREAD

**Issue by maruiqi0710** [linzhi2013/MitoZ#190]
这个软件的名字叫做animal mitochondrial genome assembly，为什么要特别指出animal mitochondrial？那么对于植物叶绿体、线粒体，真菌的线粒体的基因组的组装情况如何？

**Comment by linzhi2013** [comment]
因为未对“植物叶绿体、线粒体，真菌的线粒体的基因组的组装”进行过测试。

**Comment by comery** [comment]
动物线粒体跟植物线粒体，植物叶绿体，真菌线粒体的基因组差异很大，所以如果先挑reads再组装的话，需要这些类群的线粒体基因组作为参考，才能进一步的组装；但如果是全基因组组装然后再去找相关线粒体基因组序列，应该是可以做的，但是效果如何得自己去看一下。
如果做了相关测试，希望可以分享一下经验~
