### ISSUE TITLE
error code "all  -K 71 -o work71 -s work71.soaptrans.lib -p 4"

### ISSUE THREAD

**Issue by laradey** [linzhi2013/MitoZ#191]
## on which platform/server? (Windows? Windows Sublinux? MacOS? Ubuntu? etc.)
linux Ubuntu

## MitoZ version?
3.6

## How did you install MitoZ? (e.g. Docker, Udocker, Singularity, Conda-Pack, Conda, or source code)
Docker

## Did you run a test after your installation, and was the test run okay?
yes, test dataset was running

## The command you used?
# make sure your fq1 and fq2 files are in $PWD directory!
fq1=6112-JK-16_1_S1_L005_R1_001.good.fq.gz
outprefix=test
time docker run -v $PWD:$PWD -w $PWD  --rm guanliangmeng/mitoz:2.3 \
python3 /app/release_MitoZ_v2.3/MitoZ.py all2 \
--genetic_code 5 \
--clade Arthropoda \
--insert_size 250 \
--thread_number 4 \
--fastq1 $fq1 \
--outprefix $outprefix \
--fastq_read_length 125 \
1>m.log 2>m.err

## Problem description
Test dataset is running smoothly, by entering my data I get always an error code. Does anybody know how to solve this?

## Log messages from MitoZ (stdout and stderr)
Error occured when running command:
/app/release_MitoZ_v2.3/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 4

**Comment by linzhi2013** [comment]
Could you please upload the `m.log` and `m.err` files, so I can check the log.

You can also go to the directory and run the code
```
/app/release_MitoZ_v2.3/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 4    1>s.log 2>s.err
```
directly, to see what happens.  and upload the `s.log` and `s.err` files.

**Comment by laradey** [comment]
work71.soaptrans
###
max_rd_len=125
[LIB]
avg_ins=250
reverse_seq=0
asm_flags=3
map_len=32
q=/home/student/Documents/mitoz/6112-JK-16_1_S1_L005_R1_001.good.fq.gz


m.err
###
Killed
Error occured when running command:
/app/release_MitoZ_v2.3/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 4


m.log
###
2023-05-04 13:29:55
/app/release_MitoZ_v2.3/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 4


mitoAssemble is based on SoapTrans v1.03 and modified to fit mitogenome assembly by BGI-ENVers

pregraph -s work71.soaptrans.lib -K 71 -p 4 -o work71 
In work71.soaptrans.lib, 1 libs, max seq len 125, max name len 256

4 thread created
read from file:
 /home/student/Documents/mitoz/6112-JK-16_1_S1_L005_R1_001.good.fq.gz

**Comment by linzhi2013** [comment]
It got `Killed`. It seems that you don't have not enough RAM.
