### ISSUE TITLE
recur'Segmentation fault (core dumped)'when run mitoAssemble

### ISSUE THREAD

**Issue by BingyingQ** [linzhi2013/MitoZ#194]
## on which platform/server? (Windows? Windows Sublinux? MacOS? Ubuntu? etc.)
Linux (the server of my lab)
## MitoZ version?
version_2.4-alpha
## How did you install MitoZ? (e.g. Docker, Udocker, Singularity, Conda-Pack, Conda, or source code)
source code
## Did you run a test after your installation, and was the test run okay?
The step of assemble is ok, the cmsearch had error.
## The command you used?
nohup ./mitoz.all2.sh &

mitoz.all2.sh ↓
fq1=R1_19_ATCCAT.fastq.gz
fq2=R2_19_GGCAGA.fastq.gz
outprefix=mitoz_huanghouwu
python3 /mnt/disk5/Lab_Users/qby_zhangdongsheng/enrichment/wudong/MitoZ-master/version_2.4-alpha/release_MitoZ_v2.4-alpha/MitoZ.py all2 \
--genetic_code 2 \
--clade Chordata \
--insert_size 500 \
--thread_number 4 \
--fastq1 $fq1 \
--fastq2 $fq2 \
--outprefix $outprefix \
--fastq_read_length 128 \
1>m.log 2>m.err

## Problem description
When I run the module of all2,it was broke up in the step of assemble,then I run the line that says ' Error occured ', recur''Segmentation fault (core dumped)'. I had check the memory and cpu， it is enough and unlimited.
I had tried many type of threads ,such as 4,8,20,30,80,it is always lead to the same Error--'Segmentation fault (core dumped)'
## Log messages from MitoZ (stdout and stderr)
Error occured when running command:
/mnt/disk5/Lab_Users/qby_zhangdongsheng/enrichment/wudong/MitoZ-master/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 4

**Comment by linzhi2013** [comment]
Hi,

Maybe there is too much input data (`fq1` and `fq2`)? `mitoAssemble` does not work with too big dataset.
