### ISSUE TITLE
missing Perl modules:GD

### ISSUE THREAD

**Issue by klcym** [linzhi2013/MitoZ#196]
## on CentOS7

## It print :
`
missing GD
  error Can't load '/local_data/cym_home/software/miniconda3/envs/1_genome/lib/perl5/5.32/site_perl/auto/GD/GD.so' for module GD: /local_data/cym_home/software/miniconda3/envs/1_genome/lib/./libfontconfig.so.1: undefined symbol: FT_Done_MM_Var at /local_data/cym_home/software/miniconda3/envs/1_genome/lib/perl5/5.32/core_perl/DynaLoader.pm line 193. at (eval 41) line 1.Compilation failed in require at (eval 41) line 1.
missing GD::Polyline
  error Attempt to reload GD.pm aborted.Compilation failed in require at /local_data/cym_home/software/miniconda3/envs/1_genome/lib/perl5/5.32/site_perl/GD/Polyline.pm line 45.
All done!
`
## Log messages from MitoZ (stdout and stderr, e.g., both `m.log` and `m.err` files)
[mitoz.log](https://github.com/linzhi2013/MitoZ/files/11943649/mitoz.log)

**Comment by klcym** [comment]
there is the related software version  in my conda environment：
`perl-gd                   2.76            pl5321h5b5514e_1    bioconda`
`mitoz                     3.6                pyhdfd78af_1    bioconda`

**Comment by linzhi2013** [comment]
Hi @klcym ,

Indeed, this happened to me too before, and I couldn't figure it out even after I have spent a lot of time on it. So please try to figure it out by yourself, or you can try other installation methods.

> The **easiest way** to install MitoZ is to use **Apptainer/Singularity** and **Docker** (or **Udocker**) MitoZ images, which can help you avoid a lot of potential installation troubles. The **Conda-Pack** version may also be helpful, because, unlike the usual Conda installation method, its tar file has packed all dependencies so there is no need to download them again from the website, and thus it can be useful if your network is not so good. Conda is a good tool but may **NOT** solve all dependency problems all the time. Tips: after your installation, always **run the test dataset first** to make sure that there is no installation problem.  (From https://github.com/linzhi2013/MitoZ/wiki)

Good luck!

**Comment by klcym** [comment]
Thanks for your reply, 

Fortunatly, this bug is just shown in the visualize module and other function can properly run. Anyway, MitoZ is an excellent software.👍
