### ISSUE TITLE
Vertebrate mitogenome comes out 10k bp, linear, and unannotated

### ISSUE THREAD

**Issue by ResidentialDragonSlayer** [linzhi2013/MitoZ#197]
I am using the `all` subcommand to assemble and annotate six clouded leopard mitogenomes from subsampled WGS reads. Using `assembler megahit` and k-mer values that worked on my other samples, I'm getting only a length of 10k bp for one individual, and the genome refuses to circularize. I have tried `assembler spades` and it is throwing an error.
Does anyone know what might be wrong?
Log file is here:
[mitoz_saming_2.log](https://github.com/linzhi2013/MitoZ/files/12322506/mitoz_saming_2.log)

Thank you!

**Comment by linzhi2013** [comment]
HI @ResidentialDragonSlayer ,

You are using `kmers_megahit=['59', '79', '99', '119', '141']`. You can try to add smaller kmers, e.g. 29, 35, 45.

Your Read 1 and Read 2 have 4 Gbp data in total. You can also try to use more data if you have.

Cheers

**Comment by linzhi2013** [comment]
You run stopped at 
```

2023-08-07 16:30:18,489 - mitoz.utility.utility - INFO - 
cp -r /scratch/genomics/willish/mtdna/mitoz_2_Saming/mt_assembly/Saming.megahit.result /scratch/genomics/willish/mtdna/mitoz_2_Saming/mt_annotation/Saming.Saming.megahit.mitogenome.fa.result /scratch/genomics/willish/mtdna/mitoz_2_Saming/Saming.result
global cmsearch could not find results! Now try local cmsearch
global cmsearch could not find results! Now try local cmsearch
= Mon Aug 7 16:30:18 EDT 2023 job mitoz_saming done
```

Can you please provide also the stderr information? Based on the log, I can't figure out what was wrong there. Thanks!

**Comment by ResidentialDragonSlayer** [comment]
@linzhi2013 Thank you, I will try it with smaller kmers.

Which file contains stderr information?
