### ISSUE TITLE
Java error at MiTFi step

### ISSUE THREAD

**Issue by AlesBucek** [linzhi2013/MitoZ#20]
Hi!
I'd like to use Mitoz for its assemble and annotate steps.
Currently, "annotate" gives me a java error with the test data you provide.  I run the "assemble" step followed by "annotate" step as below:

```
#assemble module
cd /work/BourguignonU/BUCEK/Kalos/MitoZ_assemble_out
fastqDir=/work/BourguignonU/BUCEK/Kalos/sandbox
for sample in test
do MitoZ.py assemble --genetic_code 5 --clade Arthropoda --outprefix $sample \
--thread_number 10 \
--fastq1 ${fastqDir}/test.1.fq.gz \
--fastq2 ${fastqDir}/test.2.fq.gz \
--fastq_read_length 150 \
--insert_size 250 \
--run_mode 2 \
--filter_taxa_method 1 \
--requiring_taxa 'Arthropoda'
done

#annotate module
cd /work/BourguignonU/BUCEK/Kalos/MitoZ_assemble_out/test.result
for sample in test
do MitoZ.py annotate --genetic_code 5 --clade Arthropoda \
--outprefix ${sample} --thread_number 10 \
--fastafile work71.mitogenome.fa 
done
```

The error is: 

> MiTFi - mitochondrial tRNA finder v0.1
> Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 2, end 0, length 14
> 	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
> 	at java.base/java.lang.String.substring(String.java:1874)
> 	at mitfi.Main.main(Main.java:221)
> Error occured when running command:
> cd /home/a/ales-bucek/bin/release_MitoZ_v2.3/bin/annotate/mitfi
> java -Xmx2048m -jar mitfi.jar -cores 1  -code 5 -evalue 0.001 -onlycutoff /work/BourguignonU/BUCEK/Kalos/MitoZ_assemble_out/test.result/tmp/test.annotation/test_mitoscaf.fa.C5 >>/work/BourguignonU/BUCEK/Kalos/MitoZ_assemble_out/test.result/tmp/test.annotation/test_mitoscaf.fa.trna

Since that happens with test data I believe it is something specific to my system rather then an actual Mitoz bug but in case you have any suggestions how to fix this I'd be thankful for them!

**Comment by linzhi2013** [comment]
Dear AlesBucek,

Thanks for you feedback!

Can you tell me that what was the way you used MitoZ? If you installed MitoZ from source code, did you run `source activate mitozEnv` firstly when you ran the MitoZ commands?

It seems to be the problem of Java. Could you please check which java you used, e.g. `which java`, it should be from the `mitozEnv` environment.

Cheers,
Guanliang

**Comment by AlesBucek** [comment]
Dear Guanliang,
thanks for your fast response.
I indeed installed MitoZ from source code following instructions in INSTALL.md, paragraph 3.
I run MitoZ from the mitozEnv environment activated by `source activate mitozEnv`
(Note that the Assemble module runs without any problems)
Java seen from within the environment is 

> ~/anaconda_ete/envs/mitozEnv/bin/java

Thanks and cheers,
Ales

**Comment by linzhi2013** [comment]
HI Ales,

I tried the following:

```
$ source activate mitozEnv
$ cd release_MitoZ_v2.3/bin/annotate/mitfi
$ java -Xmx2048m -jar mitfi.jar -cores 1 -code 5 -evalue 0.001 -onlycutoff  mitogenome.fasta > mitogenome.fasta.trna

```
The output is:
```
MiTFi - mitochondrial tRNA finder v0.1
 #RESULTS (cutoff evalue: 0.001)
#22 hits
```

My platform information:
```
$ cat /etc/os-release

NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

$ uname -r

3.10.0-957.12.2.el7.x86_64
```

Could you have a try as above?

I don't know why it did not work for you.

Cheers,
Guanliang

**Comment by AlesBucek** [comment]
Hi Gunliang,
thanks for the instructions.
Running just mitfi.jar as you specified from the MitoZ folder reproduces for me the Java error:

```
MiTFi - mitochondrial tRNA finder v0.1
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: begin 2, end 0, length 14
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at mitfi.Main.main(Main.java:221)
```
My system is very similar to yours:
```

$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

uname -r
3.10.0-327.el7.x86_64
```

I'll check with the system administrators if they have an explanation but if you have any suggestions or just general idea what might be wrong I'd be thankful for that.
Cheers,
Ales

**Comment by AlesBucek** [comment]
The version of java in the environment is:
`~/anaconda_ete/envs/mitozEnv/bin/java -version`

> openjdk version "11.0.1" 2018-10-16 LTS
> OpenJDK Runtime Environment Zulu11.2+3 (build 11.0.1+13-LTS)
> OpenJDK 64-Bit Server VM Zulu11.2+3 (build 11.0.1+13-LTS, mixed mode)

Is this ok?

**Comment by linzhi2013** [comment]
I think your java is fine.

Here is mine java:

```
$ source activate mitozEnv

$ which java
~/soft/bio/Miniconda3/envs/mitozEnv/bin/java

$ java --version
openjdk 11.0.1 2018-10-16 LTS
OpenJDK Runtime Environment Zulu11.2+3 (build 11.0.1+13-LTS)
OpenJDK 64-Bit Server VM Zulu11.2+3 (build 11.0.1+13-LTS, mixed mode)

```

**Comment by linzhi2013** [comment]
Do not if your download is complete.

Check if your md5sum is the same as mine:

```
$ cd release_MitoZ_v2.3/bin/annotate/mitfi/
$ md5sum mitfi.jar
62c373a654aded66c3e5c5459f67eef5  mitfi.jar
$ md5sum cmsearch
8b0fc1e7b9fc65208050630c9a848ac4  cmsearch
$ md5sum mitfi_config.txt
9c508e843d4e606ae66a0236c7cd5985  mitfi_config.txt
$ md5sum gc.prt
832f30603211c17f37a58faf9a05278b  gc.prt
```

**Comment by AlesBucek** [comment]
Md5sums are identical.

**Comment by linzhi2013** [comment]
> Md5sums are identical.

That's weird.

I don't know what to do next...

Perhaps you should try Docker or Singularity version if possible.

**Comment by AlesBucek** [comment]
I'm now running MitoZ with Singularity without any problems. I did not try to resolve the java problem any further. Thanks for your help an suggestions.

**Comment by linzhi2013** [comment]
> I'm now running MitoZ with Singularity without any problems. I did not try to resolve the java problem any further. Thanks for your help an suggestions.

You're welcome!

Please feel free to open new issues when you have questions.
