### ISSUE TITLE
Issue with tRNA annotation

### ISSUE THREAD

**Issue by b-roberts21** [linzhi2013/MitoZ#200]
## on which platform/server? (Windows? Windows Sublinux? MacOS? Ubuntu? etc.)
Windows

## MitoZ version?
3.6

## How did you install MitoZ? (e.g. Docker, Udocker, Singularity, Conda-Pack, Conda, or source code)
Conda

## Did you run a test after your installation, and was the test run okay?
Yes - all fine

## How much data (roughly) did you use for mitogenome assembly? e.g. 5Gbp?
1.8Gbp PE150 data

## The command you used?
mitoz all \
        --genetic_code 5 \
        --clade Arthropoda \
        --outprefix Mir_01  \
        --fq1 out_1.fq.gz \
        --fq2 out_2.fq.gz \
        --data_size_for_mt_assembly 0,0 \
        --fastq_read_length 150 \
        --assembler megahit \
        --kmers_megahit 59 79 99 119 141 \
        --memory 50 \
        --slow_search \
        --requiring_taxa Arthropoda

## Problem description
Assembly completes as expected, yielding a mitogenome with the expected closest related species. However, annotation is failing to find any tRNA genes. CDS and rRNA are there as expected, however no tRNA genes are retrieved, even when using the slow_search argument. When using an online annotation tool (e.g. Mitos) on the MitoZ assembly, all expected genes are retrieved. Also, when manually aligning the assembly to the tRNA genes of closely related species, they align in roughly the expected position.

## Log messages from MitoZ (stdout and stderr, e.g., both `m.log` and `m.err` files)
Std.out and Std.err files are attached. 
[2023-07-18_MitoZ_bjr21.sh.o7975069.txt](https://github.com/linzhi2013/MitoZ/files/12378490/2023-07-18_MitoZ_bjr21.sh.o7975069.txt)
[2023-07-18_MitoZ_bjr21.sh.e7975069.txt](https://github.com/linzhi2013/MitoZ/files/12378489/2023-07-18_MitoZ_bjr21.sh.e7975069.txt)

**Comment by linzhi2013** [comment]
HI @b-roberts21 ,

Thanks for your reporting!

I checked your log files, they both look good. Since your run with MitoZ provided teset dataset was also fine, I suspect that it was due to the incompleteness of tRNA/rRNA database.

If you don't mind, you can send the mitogenome to me (linzhi2012<MitoZ>gmail<dot>com), replace "<MitoZ>" with "@") and tell me more details about your target your species (i.e. which specific group), I can have a look at it. Thanks!

PS: "slow_search" does not have influence on gene annotation. It is only used for candidate mitogenome searching.

Best
Guanliang

**Comment by linzhi2013** [comment]
Hi Ben,

I tried MitoZ 3.6 (on Cent OS) with your mitogenome, all genes are annotated. So the cause could be the Windows platform. You can try the Docker version of MitoZ Windows. But I don't have a Windows machine to test it yet.

```
Protein coding genes totally found: 13
tRNA genes totally found:           22
rRNA genes totally found:            2
--------------------------------------
Genes totally found:                37
```


Cheers
Guanliang
