### ISSUE TITLE
mitoz all: error: the following arguments are required: --fq1, --requiring_taxa

### ISSUE THREAD

**Issue by Cloudyellowww** [linzhi2013/MitoZ#204]
Hi, sorry to bother you
I installed MitoZ (version 3.6) and I am in the mitozEnv. I get an error when I run the following command:

mitoz all  \
--outprefix Asp \
--thread_number 16 \
--clade Arthropoda \
--genetic_code 2 \
--species_name "Asp" \
--fq1 Asp-F1_FDSW220039885-1r_1.clean.fq.gz \
--fq2 Asp-F1_FDSW220039885-1r_2.clean.fq.gz \
--fastq_read_length 151 \
--data_size_for_mt_assembly 1,0 \
--assembler megahit \
--kmers_megahit 59 79 99 119 141\
--memory 50 \
--requiring_taxa Arthropoda

The contents of fq1 and fq2 commands are the same, and their corresponding files are in the same directory. Why does fq1 report an error while fq2 has no problem? And what's the problem with requiring_taxa?

Thank you for answering my questions!

**Comment by linzhi2013** [comment]
Maybe you need to add `/` to the end of each line and change the `genetic_code`:
```
mitoz all  \
--outprefix Asp  \
--thread_number 16  \
--clade Arthropoda  \
--genetic_code 5   \
--species_name "Asp"   \
--fq1 Asp-F1_FDSW220039885-1r_1.clean.fq.gz  \
--fq2 Asp-F1_FDSW220039885-1r_2.clean.fq.gz  \
--fastq_read_length 151  \
--data_size_for_mt_assembly 1,0  \
--assembler megahit  \
--kmers_megahit 59 79 99 119 141  \
--memory 50  \
--requiring_taxa Arthropoda >m.log 2>m.err

```

`--data_size_for_mt_assembly 1,0 `, you're using 1 Gbp raw data, which could be too small.
