### ISSUE TITLE
Issue with Installation

### ISSUE THREAD

**Issue by timz0605** [linzhi2013/MitoZ#206]
## on which platform/server? (Windows? Windows Sublinux? MacOS? Ubuntu? etc.)
Ubuntu

## MitoZ version?
3.6**

## How did you install MitoZ? (e.g. Docker, Udocker, Singularity, Conda-Pack, Conda, or source code)
Conda

## The command you used?
 mamba create -n mitozEnv -c bioconda -c conda-forge mitoz=3.6
## Problem description
I encountered an issue with conflicts
## Log messages from MitoZ (stdout and stderr, e.g., both `m.log` and `m.err` files)
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
warning  libmamba Problem type not implemented SOLVER_RULE_STRICT_REPO_PRIORITY
Could not solve for environment specs
The following package could not be installed
└─ mitoz 3.6**  is not installable because it requires
   └─ ete3 >=3.1.2 , which conflicts with any installable versions previously reported.

**Comment by linzhi2013** [comment]
[](https://user-images.githubusercontent.com/6203542/285040529-11cb944f-f257-4124-8250-7c36ff0d1bdd.png)
