### ISSUE TITLE
the result assembled mito genome have more than one contigs

### ISSUE THREAD

**Issue by jiangzy26** [linzhi2013/MitoZ#207]
Hi,
    I found the result 'my_species.megahit.mitogenome.fa' has more than one contig, which one should I use? Thank you!
"
k141_84035_FivePCGs	4615	37	4615	4616
k141_321078_FivePCGs	5007	4691	5007	5008
k141_98991	18980	9727	18980	18981
k141_6742_FivePCGs	16774	28744	16774	16775
k141_398225_FivePCGs	16868	45557	16868	16869

"

**Comment by jiangzy26** [comment]
I downloaded the re-sequencing data from NCBI, it is only one species, why there are FivePCGs of other species? what are the implications? The best close species of these five contigs is not the species itself, I am not sure whether there are problems, could you share your help? Thank you very much

**Comment by linzhi2013** [comment]
In the MitoZ paper, 

> In addition, Sequences, regardless of gene conflicts, containing ≥ 5 PCGs (complete or not) will be retained to confirm identities, e.g. parasites.

Therefore, the users should further check what the "_FivePCGs" sequences belong to. The first and easy step, is to do a NT blast (https://blast.ncbi.nlm.nih.gov/Blast.cgi?PROGRAM=blastn&PAGE_TYPE=BlastSearch&LINK_LOC=blasthome)

**Comment by linzhi2013** [comment]
See also https://github.com/linzhi2013/MitoZ/wiki/Tutorial#7-what-now

**Comment by jiangzy26** [comment]
Thank you very much for your kind reply, I'll read these carefully.
