### ISSUE TITLE
MitoZ low abundance (<10X) error

### ISSUE THREAD

**Issue by Veldem** [linzhi2013/MitoZ#21]
Dear Gaunliang,
Currently, I am trying to assemble the mitochondrial genomes of two fishes species using pair-end NGS data and some analysis is working seamlessly without any error but some have when applying the same  MitoZ singularity parameters. As follows;

Sample Name                    Read Number                    Sequence Length (bp)
Oe1                                    56117045 (x2)                    150                                      
Oe2                                    88703882 (x2)                    150                                     
Yt2                                     60001863 (x2)                    150                     
Yt3                                     61976186 (x2)                    150

Code:
`MitoZ.simg all --genetic_code 2 --clade Chordata --outprefix Oe1 --thread_number 28 --fastq1 Oe1_FDSW190704924-1a_HN2HFDSXX_L3_1.fq.gz --fastq2 Oe1_FDSW190704924-1a_HN2HFDSXX_L3_2.fq.gz --fastq_read_length 150 --insert_size 250 --run_mode 2  --filter_taxa_method 1 --requiring_taxa 'Actinopterygii'`

Following the analysis, Oe1 and Yt3 samples worked perfectly and output results whereas Oe2 and Yt2 samples gave the errors (attached to the mail), it seems that everything is OK but we could not obtain the ".fasta" file for these samples. If you help us with this issue we will be greatly appreciated.
[slurm-Oe2.txt](https://github.com/linzhi2013/MitoZ/files/3604554/slurm-Oe2.txt)
[slurm-Yt2.txt](https://github.com/linzhi2013/MitoZ/files/3604555/slurm-Yt2.txt)

**Comment by Veldem** [comment]
Dear Gaunliang,

Thank you for your detailed explanation. as you indicated,  roughly 2 Gb reads were subsampled using extractfq and performed assembly and annotations. It works well now.

Cheers
Vahap

**Comment by linzhi2013** [comment]
Dear Vahap,

Glad to hear that you worked it out.

Please feel free to open new issues when you have questions.


Cheers
Guanliang

**Comment by ITSallGDM** [comment]
Dear Gaunliang，

Sorry to disturb you.

![gz](https://github.com/linzhi2013/MitoZ/assets/132741330/0d3796b4-f9d6-4b79-8f96-4b45e50bd539)

Im trying to assamble the mitochondrial genome of Piscicola geometra, and I set the '--clade' as 'Annelida-segmented-worms',
then I meet the same error in log now, "All sequences are low abundance (<10X)".

And there is only one file ''Piscicola_geometra.megahit.hmmtblout.besthit.sim.filtered-by-taxa' in the folder 'Piscicola_geometra.megahit.result' .

Im not sure how to sovle this problem.
I hope to get your help.

Thanks a lot.
ZhaoDong

**Comment by linzhi2013** [comment]
> Dear Gaunliang，
> 
> Sorry to disturb you.
> 
> ![gz](https://private-user-images.githubusercontent.com/132741330/318441986-0d3796b4-f9d6-4b79-8f96-4b45e50bd539.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5ODM5ODEsIm5iZiI6MTcxMTk4MzY4MSwicGF0aCI6Ii8xMzI3NDEzMzAvMzE4NDQxOTg2LTBkMzc5NmI0LWY5ZDYtNGI3OS04Zjk2LTRiNDVlNTBiZDUzOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwMVQxNTAxMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjVkNTEyZmNiMjEwNWJjNTQyZjQ2ZTk4M2NlMDllZjY0NDM0NWY1YWVkYzdjMzViMjRhMjZiNjYxNDFiMjVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.exi_p7aaeKj6cgeRjtARa9tg9ilJPB5JVPKIOo2bfd4)
> 
> Im trying to assamble the mitochondrial genome of Piscicola geometra, and I set the '--clade' as 'Annelida-segmented-worms', then I meet the same error in log now, "All sequences are low abundance (<10X)".
> 
> And there is only one file ''Piscicola_geometra.megahit.hmmtblout.besthit.sim.filtered-by-taxa' in the folder 'Piscicola_geometra.megahit.result' .
> 
> Im not sure how to sovle this problem. I hope to get your help.
> 
> Thanks a lot. ZhaoDong

Hi, what is your command? You may try different kmers, for example, `--kmers_megahit 21 29 39 59 79 99`

**Comment by ITSallGDM** [comment]
Dear Guanliang,

Here is my command 
"docker run -v $PWD:$PWD -v $PWD/get_taxonomy_rank_with_ete3_with_super_and_sub.py:/app/anaconda/envs/mitoz3.6/lib/python3.8/site-packages/mitoz/tools/taxonomy_ranks/get_taxonomy_rank_with_ete3_with_super_and_sub.py -w $PWD --rm guanliangmeng/mitoz:3.4 mitoz all --genetic_code 9 --clade Annelida-segmented-worms --outprefix Piscicola_geometra --thread_number 40 --fq1 L-SX1_raw_1.fq.gz --fq2 L-SX1_raw_2.fq.gz --fastq_read_length 150 --insert_size 250 --species_name 'Piscicola geometra' --requiring_taxa 'Annelida-segmented-worms' --data_size_for_mt_assembly 8 --profiles_dir $PWD/mitoz_custom_db --kmers_megahit 21 29 39 59 79 99 &>log.txt"

I have used the "--kmers_megahit" as your suggestion, but i still dont know where the problem is.
Or should i think about the depth of sequencing? 

Thanks a lot
ZhaoDong

**Comment by linzhi2013** [comment]
```
All sequences are low abundance (<10X)
```

You can first have a look at the low abundance sequences, how long they are? Can mitogenomes be in it? If they are short, try a different assembler. 

Is the data from DNA sequencing, or RNA-seq?
