### ISSUE TITLE
summary.txt empty when no CDS genes annotated

### ISSUE THREAD

**Issue by DruryCF** [linzhi2013/MitoZ#212]
## on which platform/server? (Windows? Windows Sublinux? MacOS? Ubuntu? etc.)

Ubuntu 20.04 Linux

## MitoZ version?

3.6

## How did you install MitoZ? (e.g. Docker, Udocker, Singularity, Conda-Pack, Conda, or source code)

Udocker

## Did you run a test after your installation, and was the test run okay?

yes

## How much data (roughly) did you use for mitogenome assembly? e.g. 5Gbp?

range of bp (e.g. 1500bp)

## The command you used?

for example:
udocker run  --volume=$PWD:$PWD --workdir=$PWD --rm guanliangmeng/mitoz:3.6  mitoz annotate --workdir $PWD/novoplasty_33kmer_noRefGuide_noConcat_bm/EC1_Leporillus_apicalis_C90H/annotation --fastafiles "novoplasty assembly fasta file" --fq1 "raw forward sequence reads" --fq2 "raw reverse sequence reads" --clade Chordata --outprefix EC1_Leporillus_apicalis_C90H --species_name EC1_Leporillus_apicalis_C90H

## Problem description

summary.txt file empty when no CDS genes annotated -> trna and rrna annotated genes present in *.fa.gbf.gene.fasta file and other files. Across 234 examples, no CDS genes found and varying number and completeness of trna and rrna genes found all with empty summary.txt files. Same command generated complete summary.txt files when CDS genes were found.

## Log messages from MitoZ (stdout and stderr, e.g., both `m.log` and `m.err` files)

example of mitoz log file:
[mitoz.log](https://github.com/linzhi2013/MitoZ/files/15316678/mitoz.log)

**Comment by DruryCF** [comment]
Hi, thanks for getting back so quick! I've sent an example mitogenome sequence as well as the existing EC1_Leporillus_apicalis_C90H_Contigs_1_EC1_Leporillus_apicalis_C90H_assembly.fasta_mitoscaf.fa.gbf file to linzhi2012@gmail.com. Please let me know if that's the wrong address.

**Comment by linzhi2013** [comment]
```bash
$ /home/gmeng/.conda/envs/mybase/envs/mitoz3.6/bin/python3.8 /home/gmeng/.conda/envs/mybase/envs/mitoz3.6/lib/python3.8/site-packages/mitoz/annotate/script/genbank_gene_stat_v2.py /home/gmeng/test/tm/tmp_M2_example_mitogenome_noSummary.fasta_mitoscaf.fa/M2_example_mitogenome_noSummary.fasta_mitoscaf.fa.gbf /home/gmeng/test/tm/tmp_M2_example_mitogenome_noSummary.fasta_mitoscaf.fa/M2_example_mitogenome_noSummary.fasta_mitoscaf.fa.most_related_species.txt annotate > summary.txt
Traceback (most recent call last):
  File "/home/gmeng/.conda/envs/mybase/envs/mitoz3.6/lib/python3.8/site-packages/mitoz/annotate/script/genbank_gene_stat_v2.py", line 238, in <module>
    main()
  File "/home/gmeng/.conda/envs/mybase/envs/mitoz3.6/lib/python3.8/site-packages/mitoz/annotate/script/genbank_gene_stat_v2.py", line 202, in main
    seqid_len_topology_relatedSP = get_seq_topology_and_related_sp(gbfile=gbfile, closely_related_sp_file=closely_related_sp_file)
  File "/home/gmeng/.conda/envs/mybase/envs/mitoz3.6/lib/python3.8/site-packages/mitoz/annotate/script/genbank_gene_stat_v2.py", line 183, in get_seq_topology_and_related_sp
    with open(closely_related_sp_file, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/gmeng/test/tm/tmp_M2_example_mitogenome_noSummary.fasta_mitoscaf.fa/M2_example_mitogenome_noSummary.fasta_mitoscaf.fa.most_related_species.txt'
```

The problem comes from a non-existent `M2_example_mitogenome_noSummary.fasta_mitoscaf.fa.most_related_species.txt` file.


Solution:

Please replace your `mitoz/annotate/script/genbank_gene_stat_v2.py ` file with this 
[genbank_gene_stat_v2.py.gz](https://github.com/linzhi2013/MitoZ/files/15322100/genbank_gene_stat_v2.py.gz) (decompress it after downloading, Github does not allow us to upload *.py file).


Or you can simply modify the target file:
```python
def get_seq_topology_and_related_sp(gbfile=None, closely_related_sp_file=None):
    seqid_len_topology_relatedSP = collections.defaultdict(list)
    for rec in SeqIO.parse(gbfile, 'gb'):
        seqlen = str(len(rec))
        seqid = str(rec.id)
        topology = rec.annotations['topology']
        circular_yes_no = 'no'
        if topology == 'circular':
            circular_yes_no = 'yes'

        seqid_len_topology_relatedSP[seqid].extend([seqlen, circular_yes_no])

   # add the following 5 lines to your file
    if not os.path.exists(closely_related_sp_file):
        print(f"warning: can not find {closely_related_sp_file}!!\n", file=sys.stderr)
        for seqid in seqid_len_topology_relatedSP:
            seqid_len_topology_relatedSP[seqid].append('Not Available')
        return seqid_len_topology_relatedSP

    with open(closely_related_sp_file, 'r') as fh:
        for i in fh:
            i = i.strip()
            seqid, sp = i.split('\t')
            seqid_len_topology_relatedSP[seqid].append(sp)

    return seqid_len_topology_relatedSP
```

**Comment by DruryCF** [comment]
Hi, works great! Problem solved. Thank you so much for your extremely prompt help. I'll leave you to decide to close this issue in case there's a workflow reason you'd like to keep it open.
