### ISSUE TITLE
Mitogenome sequences identification

### ISSUE THREAD

**Issue by wenyanJIA** [linzhi2013/MitoZ#214]
## MitoZ version? 
version 3.6
## Did you run a test after your installation, and was the test run okay? 
yes
## Problem description
Dear teacher MENG
By reading the paper,i find mitoz will first filter out candidate mitogenome sequences using the profile HMM when assembling. But when I check the document——final.contigs.fa (in megahit_out folder), I can find nuclear genome sequences. And the paper also said MitoZ outputs assemblies containing both mitogenome sequences and nuclear genome sequences.
Do I understand that MitoZ will use all input data to assemble all contigs (final.contigs.fa) first , then use HMMER to choose mitogenome（megahit.mitogenome.fa）?
If not，because I use enriched mtDNA data, is there a way that can skip “filter out mitogenome ” so that i can use all input data to assemble to get more information.
Additionally, I try to skip by closing the "--filter_by_taxa"（default is True）, but it always "error: unrecognized arguments" whether I type true or false. Only when it's blank, it can work.  Do I type it incorrectly?
Thanks for reading my question and I look forward to your reply!

Here are the error information:
(mitoz36) [localhost test_MT]$ mitoz all --outprefix test --thread_number 8 --fq1 test-R1.fq --fq2 test-R2.fq --requiring_taxa 'Arthropoda' --filter_by_taxa False --requiring_relax 6
usage: mitoz [-h] [--version] [--debug]
             {filter,assemble,findmitoscaf,annotate,visualize,all} ...
mitoz: error: unrecognized arguments: False
(mitoz36) [localhost test_MT]$ mitoz all --outprefix test --thread_number 8 --fq1 test-R1.fq --fq2 test-R2.fq --requiring_taxa 'Arthropoda' --filter_by_taxa True --requiring_relax 6
usage: mitoz [-h] [--version] [--debug]
             {filter,assemble,findmitoscaf,annotate,visualize,all} ...
mitoz: error: unrecognized arguments: True
(mitoz36) [localhost test_MT]$ mitoz all --outprefix test --thread_number 8 --fq1 test-R1.fq --fq2 test-R2.fq --requiring_taxa 'Arthropoda' --filter_by_taxa false --requiring_relax 6
usage: mitoz [-h] [--version] [--debug]
             {filter,assemble,findmitoscaf,annotate,visualize,all} ...
mitoz: error: unrecognized arguments: false
(mitoz36) [localhost test_MT]$ mitoz all --outprefix test --thread_number 8 --fq1 test-R1.fq --fq2 test-R2.fq --requiring_taxa 'Arthropoda' --filter_by_taxa  --requiring_relax 6

2024-06-12 02:49:32,535 - mitoz.utility.utility - INFO - 
Found: /home/zf/install/mambaforge/envs/mitoz36/bin/spades.py

**Comment by linzhi2013** [comment]
I think you should use `--filter_by_taxa ` instead of `--filter_by_taxa False`.

**Comment by wenyanJIA** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wenyanJIA** [comment]
Dear teacher MENG
Thanks for your reply!

We have prior enriched mtDNA sequence data before MitoZ assembly. Is it possible to omit or bypass "search mitochondrial sequences" step in MitoZ pipeline so that all clean data could be used for assembly?

**Comment by linzhi2013** [comment]
> Dear teacher MENG Thanks for your reply!
> 
> We have prior enriched mtDNA sequence data before MitoZ assembly. Is it possible to omit or bypass "search mitochondrial sequences" step in MitoZ pipeline so that all clean data could be used for assembly?

MitoZ always uses all input data for assembly. and then searches for candidate mitochondrial sequences from the assembly result.

- If you think your data contains only mt reads and do not want any sequences to be filtered out during the "search mitochondrial sequences" step, you can go to `mt_assembly/megahit/` directory to find the original  "assembly result"
- However, I would recommend to  "search mitochondrial sequences" in case the assembly result has non-mt-DNA sequences.
