### ISSUE TITLE
Mitogenome_reorder Error

### ISSUE THREAD

**Issue by Veldem** [linzhi2013/MitoZ#23]
Dear Guanliang,

I hope that you are doing well and thank you again for providing MitoZ for us, it seems really useful for us.  I have a question regarding reordering of newly assembled mitogenomes using following code;

python3 /okyanus/users/veldem/05.Miscellaneous/MitoZ/MitoZ/version_2.3/useful_scripts/Mitogenome_reorder.py -f **Oe2.fasta** -r **Schistura_longa.fasta**

When running above code, it gives an error;

can not find topology=[circular|linear] in seqID

But the fasta header has already this information;

>C720972;len=16571;topology=circular

I am missing something to do this job? Many thanks in advance for your help!

**Comment by Veldem** [comment]
Dear Guanliang,

There is another issue about useful script called "circle_check.py" when running this script, the output considers the mtDNA assembly as "linear", but however, the summary file of MitoZ output indicates the mtDNA assembly is circular. Could we clarify this issue?

cat jjj.mitogenome.fa
>C108631;len=16571;topology=**circular topology=linear**


#Seq_id        Length(bp)     Circularity    Closely_related_species
C108631        16571          **yes**            Schistura scaturigina

Best wishes

**Comment by linzhi2013** [comment]
> Dear Guanliang,
> 
> There is another issue about useful script called "circle_check.py" when running this script, the output considers the mtDNA assembly as "linear", but however, the summary file of MitoZ output indicates the mtDNA assembly is circular. Could we clarify this issue?
> 
> cat jjj.mitogenome.fa
> 
> > C108631;len=16571;topology=**circular topology=linear**
> 
> #Seq_id Length(bp) Circularity Closely_related_species
> C108631 16571 **yes** Schistura scaturigina
> 
> Best wishes

Dear Vahap,

The basic idea of `circle_check.py` script is to check if the two ends of a sequence are overlapping, regardless of the sequence title information. The overlapping region will be removed in the output.

So I think the MitoZ summary output saying "Circular" looks good.

If you run  `circle_check.py`  again with the "circularized" sequence, in which its two ends have no overlapping regions anymore, then  `circle_check.py` will add ` topology=linear` comment on the output title.

Best wishes,
Guanliang

**Comment by comery** [comment]
Dear Vahap,

I think this problem is raised by your sequence ID. I remember the assembly result generated by MitoZ looks like "C720972 topology=circular", there is " " after sequence id "C720972", not linked by ";". 

In this case, the script ```Mitogenome_reorder.py``` will find topology information from string "topology=circular" which is defined as the description for a fasta sequence.
So, try to change the format of your sequence, it will work!

Best wishes,
Chentao

**Comment by Veldem** [comment]
Dear Guanliang & Chentao,

Thank you for the quick response but despite my numerous effort, I could not reorder our mtDNA like the reference. Here I am sharing the mtDNA assembly and reference genome with you and code, it will be perfect if you overcome this problem! Many thanks in advance for all your help.

Code: 
python3 Mitogenome_reorder.py -f Ase1.fasta -r Schistura_longa.fasta

[Schistura_longa.zip](https://github.com/linzhi2013/MitoZ/files/3636413/Schistura_longa.zip)
[Ase1.fasta.zip](https://github.com/linzhi2013/MitoZ/files/3636403/Ase1.fasta.zip)

**Comment by comery** [comment]
Dear Vahap,

I checked my code and found there is a little bug in that script. I am sorry for that make your time.

Now you can use the attached script to reorder your mitogenome as the way you did. I will let Guanliang update this script later.

Best wishes,
Chentao
[Mitogenome_reorder.py.zip](https://github.com/linzhi2013/MitoZ/files/3638357/Mitogenome_reorder.py.zip)

**Comment by Veldem** [comment]
Dear Chentao,

Thank you for all your help, now, the script is working seamlessly with your help!

Best wishes!
