### ISSUE TITLE
Can I use this program to assemble the fungal mitochondrial genome?

### ISSUE THREAD

**Issue by OmonkeyGOD** [linzhi2013/MitoZ#25]
Hi,
Can I use this program to assemble the fungal mitochondrial genome?

**Comment by linzhi2013** [comment]
Dear OmonkeyGOD,

I have not tried MitoZ with fungal data.

Two things I can confirm,

1. the `assemble` command can do assembly, generating the nucl + mt assembly.

2.  but it may not be able to find out the fungal mitochondrial sequences, since MitoZ does not include HMM profiles of fungi.

However, you can try the `assemble` command, and find the nucl + mt assembly file in the `tmp/XXX.assembly`  directory, and filename looks like `*.ScafSeq`.

Then you can blast this  `*.ScafSeq` file to some true fungi mitochondrial genomes (e.g download from Genbank by yourself).

Hope this helps!

**Comment by OmonkeyGOD** [comment]
Thank you very much. I will try this assembler.

**Comment by OmonkeyGOD** [comment]
Hi,
When it comes annotation...
If I am only interested in one or two species of fungal, and there are only two or three GenBank files of this species in NCBI, do I need to add more related species' GenBank files to build the database for annotation?  If so, does that mean the bigger the database the better of the results? 
On the other hand, If there is no complete Genbank file for that species, but some fragments of the mitogenome could be found in NCBI, can anyone use these fragments to build the annotation database? 
Thank you very much!

**Comment by linzhi2013** [comment]
> Hi,
> When it comes annotation...
> If I am only interested in one or two species of fungal, and there are only two or three GenBank files of this species in NCBI, do I need to add more related species' GenBank files to build the database for annotation? If so, does that mean the bigger the database the better of the results?
> On the other hand, If there is no complete Genbank file for that species, but some fragments of the mitogenome could be found in NCBI, can anyone use these fragments to build the annotation database?
> Thank you very much!

Hi OmenkyGOD,

During building the database for annotation, we deal with each gene one by one. Thus you do not have have a complete Genbank file for that species.

But building the database for annotation by yourself can be a little overhead, and this is due that I have not a chance to document the procedures.

Therefore, I would suggest you use http://mitos.bioinf.uni-leipzig.de/index.py for annotating your fungi species currently.

Cheers

**Comment by OmonkeyGOD** [comment]
Hi,
Thank you very much for your quick reply.
I just tried one of my assemblies with MITOS Web Server and I find the result is not very good. Because it only has genetic code 04 related to fungi, and I believe it is quite different from the species I am studying.  For example, it did not find gene atp8. But when I blast the atp8 sequence with my contig, it shows a 100% match. Thus, I still want to build a very small database with only several species information related to my study. If so, it will be easier and convenient for my future studies.
I found your advice for annotating other species in question #8 changing MitoZ's annotating database to annotate other types of mitogenome, and I think I will try it first. 

Thanks.

**Comment by Prunoideae** [comment]
Dear linzhi2013,
In the version v2.4-alpha, it seems that there are already *.fa files other than Chordata and Arthropoda inside, but it seems that the --clade option only accepts the Chordata and Arthropoda, as the `MitoZ.py` has `choices=["Chordata", "Arthropoda"]` to limit it.
Is that a miss on script programming, or is the *.fa files of other phylogenic classes are invalid or 'untuned' for annotation?

**Comment by OmonkeyGOD** [comment]
Hi,
Sorry to bother you again. I feel frustrated when I try to annotate my sample with new annotation files and I really need your help.

I have just generated the .hmm profile with several isolates' sequences of my interested species and .fasta  file of proteins sequences.  Then I put the profiles in the profiles subdirectories where they should be and 

-  replace the Mitoz.py script with   

`_search_and_annot_mito_parser.add_argument("--clade", default="Cryptococcus",
        choices=["Chordata", "Arthropoda","Porifera-sponges", "Cryptococcus"],
        # "Echinodermata", "Annelida-segmented-worms", "Bryozoa", "Mollusca", "Nematoda", "Nemertea-ribbon-worms", "Porifera-sponges"],
        help="which clade does your species belong to? [%(default)s]")_`  

- change the product_dict of the script cds_ft_v2.py.
But I still get this error :

Traceback (most recent call last):
  File "/home/yue/release_MitoZ_v2.4-alpha/bin/annotate/prepare_CDSposition.py", line 47, in <module>
    fh_in = open(in_f, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'ERR1810384_mitoscaf.fa.solar.genewise.gff.cds.position.cds'.

Please give me some advice.
Thank you very much!

**Comment by linzhi2013** [comment]
> Dear linzhi2013,
> In the version v2.4-alpha, it seems that there are already *.fa files other than Chordata and Arthropoda inside, but it seems that the --clade option only accepts the Chordata and Arthropoda, as the `MitoZ.py` has `choices=["Chordata", "Arthropoda"]` to limit it.
> Is that a miss on script programming, or is the *.fa files of other phylogenic classes are invalid or 'untuned' for annotation?


If your interested species happens to be in the clades as below, the easiest way to work around is:
(1)   Find the main script “MitoZ.py”
(2)   Then edit the “search_and_annot_mito_parser.add_argument” to be below (e.g. with a text editor like vi command, or Sublime Text, or notepad++, but never use Windows’s text editor):
```
 
search_and_annot_mito_parser.add_argument("--clade", default="Arthropoda",
        choices=["Chordata", "Arthropoda", "Echinodermata", "Annelida-segmented-worms", "Bryozoa", "Mollusca", "Nematoda", "Nemertea-ribbon-worms", "Porifera-sponges"],
        help="which clade does your species belong to? [%(default)s]")
```

**Comment by OmonkeyGOD** [comment]
Hi, 
Sorry to bother you again. I feel frustrated when I try to annotate my sample with new annotation files and I really need your help.
I have just generated the .hmm profile with several isolates' sequences of my interested species and .fasta file of proteins sequences. Then I put the profiles in the profiles subdirectories where they should be and
•	replace the Mitoz.py script with
`search_and_annot_mito_parser.add_argument("--clade", default="Cryptococcus", choices=["Chordata", "Arthropoda","Porifera-sponges", "Cryptococcus"], # "Echinodermata", "Annelida-segmented-worms", "Bryozoa", "Mollusca", "Nematoda", "Nemertea-ribbon-worms", "Porifera-sponges"], help="which clade does your species belong to? [%(default)s]")`
•	change the product_dict of the script cds_ft_v2.py.
•	genbank_gene_stat_v2.py
But I still get this error :
Traceback (most recent call last): File "/home/yue/release_MitoZ_v2.4-alpha/bin/annotate/prepare_CDSposition.py", line 47, in fh_in = open(in_f, 'r') FileNotFoundError: [Errno 2] No such file or directory: 'ERR1810384_mitoscaf.fa.solar.genewise.gff.cds.position.cds'.
Please give me some advice. Thank you very much!

**Comment by Prunoideae** [comment]
> I am not quite sure what kind of clade that your interested species belong to, but I have actually built some HMM profiles for other clades in the latest version of MitoZ. However, since we still don’t have enough time and material to test their efficiency, I intendedly make them not available from the command lines currently.

Dear linzhi2013,
Thank you for your quick reply!
I'm using MitoZ to assemble and annotate the mitogenome of Platyhelminthes, which already has a .fa file in the directory, but it seems that the .hmm file is missing.

**Comment by linzhi2013** [comment]
> > I am not quite sure what kind of clade that your interested species belong to, but I have actually built some HMM profiles for other clades in the latest version of MitoZ. However, since we still don’t have enough time and material to test their efficiency, I intendedly make them not available from the command lines currently.
> 
> Dear linzhi2013,
> Thank you for your quick reply!
> I'm using MitoZ to assemble and annotate the mitogenome of Platyhelminthes, which already has a .fa file in the directory, but it seems that the .hmm file is missing.

Do not worry about the HMM. you may just copy the Arthropoda or chordate's hmm file then rename it to
the clade (`--clade` option) which your species belong to.

HMM files are just to search for PCGs, and I think HMM model has enough power to handle distant species.

**Comment by linzhi2013** [comment]
> Hi,
> 
> I just solved the problem by resetting the environment.

That's great!

**Comment by OmonkeyGOD** [comment]
Hi,
I just developed another error :(  . Eventhough I can generate .result/ and .tmp/ folders at the very end, some files (.cds; .misc_feature; .rrna; .trna)  are empty. It seems that this error is due to `$track_data && @$track_data > fetch_conf("max_points_per_track"`, but I am very new to Circos. I also trid to use Mitoz without changing anything and use the default clade, and there was no error at all! 
Is there anything default that related to Circos that I should change? 
`
[main] Version: 0.7.17-r1188
[main] CMD: bwa mem -t 8 /home/yue/example/ERR1810384.tmp/ERR1810384.annotation/visualization/circos.mito.fa /home/yue/example/ERR1810384_1.fastq /home/yue/example/ERR1810384_2.fastq
[main] Real time: 141.321 sec; CPU: 1143.902 sec
 at /home/yue/miniconda3/envs/newEnv/bin/../lib/Circos/Error.pm line 425.
	Circos::Error::fatal_error("track", "max_number", 29002, "line", "/home/yue/example/ERR1810384.tmp/ERR1810384.annotation/visual"..., 25000) called at /home/yue/miniconda3/envs/newEnv/bin/../lib/Circos.pm line 1562
	Circos::run("Circos", "_cwd", "/home/yue/example/ERR1810384.tmp/ERR1810384.annotation", "configfile", "/home/yue/example/ERR1810384.tmp/ERR1810384.annotation/visual"..., "_argv", "-conf /home/yue/example/ERR1810384.tmp/ERR1810384.annotation/"...) called at /home/yue/miniconda3/envs/newEnv/bin/circos line 536
All done!
PNG => /home/yue/example/ERR1810384.tmp/ERR1810384.annotation/visualization/circos.png
SVG => /home/yue/example/ERR1810384.tmp/ERR1810384.annotation/visualization/circos.svg
2019-10-31 23:51:35
cp ERR1810384_mitoscaf.fa.gbf ERR1810384_mitoscaf.fa.sqn ERR1810384_mitoscaf.fa.val /home/yue/example/ERR1810384.result

2019-10-31 23:51:35
cp errorsummary.val /home/yue/example/ERR1810384.result/ERR1810384.errorsummary.val
cp visualization/circos.svg /home/yue/example/ERR1810384.result/ERR1810384.circos.svg
cp visualization/circos.png /home/yue/example/ERR1810384.result/ERR1810384.circos.png
cp visualization/circos.karyotype.txt /home/yue/example/ERR1810384.result/ERR1810384.circos.karyotype.txt
cp visualization/circos.dep /home/yue/example/ERR1810384.result/ERR1810384.circos.dep


cp: cannot stat `visualization/circos.png': No such file or directory
2019-10-31 23:51:35
/home/yue/miniconda3/envs/newEnv/bin/python3 /home/yue/release_MitoZ_v2.4-alpha/bin/common/get_result-dir_file_intro.py /home/yue/example/ERR1810384.result > /home/yue/example/ERR1810384.result/README.txt
`
Thank you very much!
