### ISSUE TITLE
Corrupt release_MitoZ_v2.4-alpha.tar.bz2 

### ISSUE THREAD

**Issue by OmonkeyGOD** [linzhi2013/MitoZ#26]
Hi,

I could not unzip the package. It gave this error: bzip2: (stdin) is not a bzip2 file.
tar: Child returned status 2
tar: Error is not recoverable: exiting now

This also happened when I tried to unzip example files. I think they are all corrupt
Please assist. Thank you very much!

**Comment by linzhi2013** [comment]
Hi OmonkeyGOD,

This usually means that your downloaded file was broken (e.g. due to bad network connection), please download it again.

Cheers,
Guanliang
