### ISSUE TITLE
Please update the install.md of v2.4-alpha

### ISSUE THREAD

**Issue by Prunoideae** [linzhi2013/MitoZ#27]
The constructor of the NCBITaxa class at the version of 3.0.0b35 doesn't take the augment 'taxdump_file', which caused really a problem when I'm installing the MitoZ from source code, as downloading the dump file from NCBI is slow and unstable, and there's no way for the NCBITaxa to use downloaded dump file in version 3.0.0b35. Updating the ete3 toolkit to version 3.1.1 using conda update or just specify the version when creating environment will solve this issue.

**Comment by linzhi2013** [comment]
Dear Prunoideae,

Thank you very much for pointing it out and give detail suggestions!

Now the ete3 toolkit has been specified to version 3.1.1  when creating the `mitozEnv` using conda.

Thanks!
Guanliang
