### ISSUE TITLE
Mitogenome_reorder error

### ISSUE THREAD

**Issue by ekarsalan** [linzhi2013/MitoZ#28]
Dear Guanliang,
Thank for updating the repository.
I have an issue with nitogenome_reorder in V2.4.
I constantly receive the error "can not find topology=[circular|linear] in seqID"
However, my heading(seq-id) are like below:
>scaffold26058;len=15661;topology=linear     <<< for mito.fa >>> >scaffold26058;len=18661;topology=circular  <<< for reference.fasta >>>

Thanks in advance
Arsalan

**Comment by linzhi2013** [comment]
Dear Arsalan,

Please refer to https://github.com/linzhi2013/MitoZ/issues/23#issuecomment-533770215

Should that not work, please feel free to inform me.


Cheers
Guanliang

**Comment by ekarsalan** [comment]
Thanks, Guanliang for your kind response.
All good!
Cheers
