### ISSUE TITLE
assembley error (all module)

### ISSUE THREAD

**Issue by NilaKMMA** [linzhi2013/MitoZ#3]
Hello, I was exploring MitoZ to see if it can be implemented in our research. I tried following the all module, but when it tries to assemble the clean data I'm presented with the following error:

Error occured when running command:
/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 12

I checked that all files have the correct format, but can't find any anomalies there. 
Any ideas what the problem could be and how to solve this issue?
Thanks in advance

**Comment by linzhi2013** [comment]
Hi NilaKMMA,

Could you please send me the command you used and the log file?

the log files can be generated with command like this:

`MitoZ.py all  your_parameters 1>m.log  2>m.err`

then send me the `m.log` and `m.err' files (as well as the command), and the file `work71.soaptrans.lib`.

I also would like to know the input data size you used, the computer resources you have (i.e. the maximum memory of your computer). I noticed that you set thread number to be 12, which can make MitoZ take too much memory (e.g. 100G for 3G fastq data), I am wondering if that was the reason.

Best wishes
Guanliang

**Comment by NilaKMMA** [comment]
Hi Guanliang, 

Thank you for your fast reply. I have found my mistake however, so it had nothing to do with the program (I used unzipped input files instead of zipped files). I'm looking forward to see the results. 

Cheers, 
NilaKMMA

**Comment by linzhi2013** [comment]
Hi NilaKMMA,

Glad to hear you found the problem! 

The input fastq files should be either  gzip or non-compressed (i.e. plain text) format. zip format is different from gzip format.

Cheers,
Guanliang

**Comment by linzhi2013** [comment]
Please feel free to open new issues if you meet new problems.
