### ISSUE TITLE
Gene coordinates problem in the `summary.txt` file

### ISSUE THREAD

**Issue by linzhi2013** [linzhi2013/MitoZ#30]
![image](https://user-images.githubusercontent.com/6203542/68528181-64a0f000-032a-11ea-9572-da22e7425a94.png)

---后边是我手动矫正后的位置

Python编码问题。对于一个基因，Python坐标是 [0, 2）。我提取这个坐标的时候，起始位置记得+1了，但是结束位置忘记减1了。

**Comment by comery** [comment]
who are you talking about?
