### ISSUE TITLE
Discussion group about how to use MitoZ

### ISSUE THREAD

**Issue by zhounan1356** [linzhi2013/MitoZ#32]
Dear professor Meng 
   Thanks for your software:MitoZ，it is a so convenient tool for me. However, sometimes there are some errors caused by my mistakes during running MitoZ, maybe an online discussion group for users will be better.Then users who have questions can help each other in time. I create a discussion group based on QQ, the number is 818630967. I sincerely hope you can join us and welcome other users too. Thanks for your help again.

**Comment by linzhi2013** [comment]
Dear Zhounan,

Please post related issues on Github, making them possible to be reached by other users. If issues were discussed in a QQ group, then the same problem will be asked over and over again, since other users wouldn't be aware that his/her could have already been answered.

Cheers

**Comment by zhounan1356** [comment]
Dear professor Meng
It is my fault, then I will post my issues on Github.&nbsp; Thanks for your help! Have a good day!&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Guanliang MENG"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 上午9:13
收件人:&nbsp;"linzhi2013/MitoZ"<MitoZ@noreply.github.com&gt;;
抄送:&nbsp;"周"<1356389546@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [linzhi2013/MitoZ] Discussion group about how to use MitoZ (#32)




Dear Zhounan,
 
Please post related issues on Github, making them possible to be reached by other users. If issues were discussed in a QQ group, then the same problem will be asked over and over again, since other users wouldn't be aware that his/her could have already been answered.
 
Cheers

**Comment by linzhi2013** [comment]
> Dear professor Meng It is my fault, then I will post my issues on Github.&nbsp; Thanks for your help! Have a good day!&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"Guanliang MENG"<notifications@github.com&gt;; 发送时间:&nbsp;2019年11月27日(星期三) 上午9:13 收件人:&nbsp;"linzhi2013/MitoZ"<MitoZ@noreply.github.com&gt;; 抄送:&nbsp;"周"<1356389546@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [linzhi2013/MitoZ] Discussion group about how to use MitoZ (#32) Dear Zhounan, Please post related issues on Github, making them possible to be reached by other users. If issues were discussed in a QQ group, then the same problem will be asked over and over again, since other users wouldn't be aware that his/her could have already been answered. Cheers — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Dear Zhounan,

Sorry for the inconvenience. But if there are some issues difficult to explain on Github or not suitable for posting to Github, you may write to my email (linzhi2012[AT]gmail[DOT]com), I would be glad to help you if I can.

Best
