### ISSUE TITLE
A quesstion about how to find the missing genes？ 

### ISSUE THREAD

**Issue by zhounan1356** [linzhi2013/MitoZ#34]
Dear professor Meng
I found a problem I can't handle it. Sometimes the annotated mitogenome will miss tRNA and PCGs, how can I find complete mitochondrial genomes as much as possible. I tried to use the multi-kmer model to handle it however, the results were unsatisfactory. What should I do next?
sincerely,
Nan Zhou

**Comment by linzhi2013** [comment]
How much data did you run with?

Too much data or not enough can lead to missing genes. Please check also https://github.com/linzhi2013/MitoZ/issues/21#issuecomment-530740690

**Comment by zhounan1356** [comment]
Dear professor Meng
There are 156,861 used sequences,  each of them has 150 base pairs, 24,000,000 base pairs totally. And the document size about 8.4MB, and I have confused about there are too much or less for the MitoZ? The version I have used is MitoZ v2.4-alpha. I try my best to solve this issue but it still missing some tRNAs and PCGs.
Many thanks,
Nan Zhou

**Comment by linzhi2013** [comment]
> Dear professor Meng
> There are 156,861 used sequences, each of them has 150 base pairs, 24,000,000 base pairs totally. And the document size about 8.4MB, and I have confused about there are too much or less for the MitoZ? The version I have used is MitoZ v2.4-alpha. I try my best to solve this issue but it still missing some tRNAs and PCGs.
> Many thanks,
> Nan Zhou

Hi Zhounan,

It depends on the mitochondrial reads ratio on your dataset. Normally, if you did not enrich the mitochondrial DNA during experiment procedures, the mitochondrial reads ratio would be very low (ca 0.05%), and this also depends on the tissue type you used to extract the DNA. thus, in genernal, I would recommend you use 2 to 5 G bp data to assemble mitogenome. The relationship is `1X10^9 = 1 G bp`.

Hence, 24,000,000 base pairs  is about 0.024 G bp, which is not enough for mitochondrial genome assembly.

**Comment by zhounan1356** [comment]
Dear professor Meng  
Thank you so much for your detailed explanation. I will recheck the mitochondrial ratio on my dataset again. Thank you again for everything you've done.
Sincerely,
Nan Zhou
