### ISSUE TITLE
disk I/O error

### ISSUE THREAD

**Issue by lichao2015021118** [linzhi2013/MitoZ#35]
>>> from ete3 import NCBITaxa
>>> ncbi = NCBITaxa()
NCBI database format is outdated. Upgrading
Downloading taxdump.tar.gz from NCBI FTP site (via HTTP)...
Done. Parsing...
Loading node names...
2194198 names loaded.
213209 synonyms loaded.
Loading nodes...
2194198 nodes loaded.
Linking nodes...
Tree is loaded.
Updating database: /share/home/zhaojun01/.etetoolkit/taxa.sqlite ...
 2194000 generating entries...
Uploading to /share/home/zhaojun01/.etetoolkit/taxa.sqlite
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/share/home/zhaojun01/.conda/envs/mitozEnv/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 120, in __init__
    self.update_taxonomy_database(taxdump_file)
  File "/share/home/zhaojun01/.conda/envs/mitozEnv/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 129, in update_taxonomy_database
    update_db(self.dbfile)
  File "/share/home/zhaojun01/.conda/envs/mitozEnv/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 760, in update_db
    upload_data(dbfile)
  File "/share/home/zhaojun01/.conda/envs/mitozEnv/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 791, in upload_data
    db.execute(cmd)
sqlite3.OperationalError: disk I/O error

**Comment by linzhi2013** [comment]
Hi there,

Maybe your disk was running out of space.

Please check (https://github.com/linzhi2013/MitoZ/blob/master/version_2.4-alpha/INSTALL.md)

> HOME directory must have more than 500M space available. If not, please refer to https://github.com/linzhi2013/taxonomy_ranks/blob/master/README.md

**Comment by lichao2015021118** [comment]
Hi Guanliang,
Thanks for the reply, I will try.
Li Chao

**Comment by lichao2015021118** [comment]
Hi Guangliang,
I have checked my HOME directory and it has more than 500 M space. I can download the taxdump.tar.gz file in the directory. I also tried the solution in the link and it showed the error "File has existed : .etetoolkit". Do you have any ideas to install the database manually in the .etetoolkit directory or any other solutions?
Thanks.
Li Chao

**Comment by linzhi2013** [comment]
> .etetoolkit

Hi Li Chao,

You can just delete the whole folder `.etetoolkit` by doing `rm -rf ~/.etetoolkit`. then follow the instruction in the link https://github.com/linzhi2013/taxonomy_ranks/blob/master/README.md again.

I am not sure why you got the `sqlite3.OperationalError: disk I/O error` when your `HOME` has enough space.

**Comment by lichao2015021118** [comment]
Yes, I have done these steps in the link and it shows the error. I think in the **ln -s /other/place/myetetoolkit ~/.etetoolkit** step, it creats the ~/.etetoolkit directory and when I do the **taxaranks my_taxonomy_list outfile**, it shows the error "file has existed".

**Comment by linzhi2013** [comment]
> Yes, I have done these steps in the link and it shows the error. I think in the **ln -s /other/place/myetetoolkit ~/.etetoolkit** step, it creats the ~/.etetoolkit directory and when I do the **taxaranks my_taxonomy_list outfile**, it shows the error "file has existed".

Can you try to use the Docker or Singularity version? Installing the dependencies is always frustrating.

**Comment by lichao2015021118** [comment]
No, I can't because I am not the root user. But I will try to figure it out later.
