### ISSUE TITLE
Error while running circos 

### ISSUE THREAD

**Issue by bastianheimburger** [linzhi2013/MitoZ#36]
Dear @linzhi2013,

MitoZ is running fine until visualization. Here is the error message I'm getting:

perl: symbol lookup error: /usr/users/bheimbu/perl5/lib/perl5/x86_64-linux-thread-multi/auto/List/Util/Util.so: undefined symbol: Perl_xs_apiversion_bootcheck

Do I have to use a specific version of perl to run circos?

Cheers Bastian

**Comment by linzhi2013** [comment]
Dear Bastian,

It seems that you were not in the `mitozEnv` environment, since the Perl was not from the `mitozEnv` environment.

https://github.com/linzhi2013/MitoZ/blob/master/version_2.4-alpha/INSTALL.md

Did you run `source activate mitozEnv` before run MitoZ?

**Comment by bastianheimburger** [comment]
Dear Guanling,

I did yes. Can I somehow re-direct to the specific Perl version used within the MitoZ environment?


Cheers Bastian

**Comment by linzhi2013** [comment]
Hi Bastian,

I am not sure about the way you said about.

Can you check which Perl you are using by running `which perl` in your console (in the `mitozEnv` environment)?

Cheers,
Guanliang

**Comment by bastianheimburger** [comment]
Sorry,

was a bit confusing my comment/question. Here is the output from $ which perl:

~/miniconda2/envs/mitoz/bin/perl

**Comment by linzhi2013** [comment]
That's weird. I cannot figure it out why you ran into this problem.

After googling a bit, someone had such similar problem, e.g. https://stackoverflow.com/questions/30626245/undefined-symbol-perl-xs-apiversion-bootcheck.

You may google "undefined symbol: Perl_xs_apiversion_bootcheck" and maybe can find a solution (though I haven't seen a definite one)

**Comment by bastianheimburger** [comment]
I already did this,

and could not find a solution. I may try to reinstall the whole thing again. I tried to change the first line in draw_circos_for_mitogenome_auto_depth.pl from #!/usr/bin/perl to #!/usr/bin/env perl, but without any luck. It still shows the same error as before.

Cheers Bastian

**Comment by linzhi2013** [comment]
I see. Maybe re-install the whole is a solution, or use Docker or Singularity version? I found many people have problems with solving the dependencies.

Cheers,
Guanliang

**Comment by bastianheimburger** [comment]
I don't have root privileges on the cluster I'm using though docker and singularity cannot be used, right?

Cheers Bastian

**Comment by bastianheimburger** [comment]
I could install MitoZ locally on my PC, but then I'm limited in the usage of threads to use. But I may have to do it this way then.

**Comment by linzhi2013** [comment]
> I could install MitoZ locally on my PC, but then I'm limited in the usage of threads to use. But I may have to do it this way then.

yes, the visualization step won't take much memory.

**Comment by bastianheimburger** [comment]
Hi,

docker did the trick. Nice programm --- Congrats. I will close this issue now.

Cheers and have a good weekend,

Bastian

**Comment by bastianheimburger** [comment]
Hi,

I've encountered another problem once I'm trying to use the Singularity container. I just downloaded the container without problems but when I'm typing `$ ./MitoZ.simg --help` I get: 

`/app/anaconda/bin/python3: can't open file '/app/release_MitoZ_v2.4-alpha/MitoZ.py': [Errno 2] No such file or directory`

Though, where is this folder?

Cheers Bastian

**Comment by bastianheimburger** [comment]
Hi,

I've encountered another problem once I'm typing 
```
$ ./MitoZ.simg --help
/app/anaconda/bin/python3: can't open file '/app/release_MitoZ_v2.4-alpha/MitoZ.py': [Errno 2] No such file or directory
```
I plainly downloaded the container, though what am I doing wrong here? Is the download link broken?


Cheers Bastian

**Comment by linzhi2013** [comment]
> Hi,
> 
> I've encountered another problem once I'm typing
> 
> ```
> $ ./MitoZ.simg --help
> /app/anaconda/bin/python3: can't open file '/app/release_MitoZ_v2.4-alpha/MitoZ.py': [Errno 2] No such file or directory
> ```
> 
> I simply downloaded the container, though what am I doing wrong here? Is the download link broken?
> 
> Cheers Bastian

Hi Bastian,

Maybe the Singularity image was not built successfully for version 2.4. Please consider the version 2.3 for now. I will check what happened to the version 2.4 Singularity images.

Thank you for reporting the issue.
Cheers,
guanliang

**Comment by bastianheimburger** [comment]
Hi,

any news whether the image of version 2.4 is broken or not?


Cheers Bastian

**Comment by linzhi2013** [comment]
> or

it is broken. Now we use `conda` for MitoZ 3.0.
