### ISSUE TITLE
Annotation Issue: Genewise Error

### ISSUE THREAD

**Issue by kneubehl** [linzhi2013/MitoZ#37]
I have successfully installed the docker version of MitoZ 2.4alpha and ran the test data set with no problem. I am interested in the annotation and visualization models. I have tried only using the annotation module, with a consensus sequence from a full length amplicon, and it will not proceed past the 'run the genewise shell file'. I copied a part of the terminal output, it proceeded to go through a number of other species besides O. porcinus with the same error, that it cannot read the fasta file. The input file is formatted appropriately and has a sequence ID less than 10 characters with "topology=circular" included. Any help would be appreciated!

$/project# python3 /app/release_MitoZ_v2.4-alpha/MitoZ.py annotate --genetic_code 5 --clade Arthropoda --thread_number 4 --fastafile travis.consensus.fasta --outprefix nano  
2019-12-15 06:20:09
export WISECONFIGDIR=/app/release_MitoZ_v2.4-alpha/bin/annotate/wisecfg
perl /app/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl -i nano_mitoscaf.fa -d /app/release_MitoZ_v2.4-alpha/bin/profiles/MT_database/Arthropoda_CDS_protein.fa -o ./ -g 5 -cpu 4

makeblastdb -in nano_mitoscaf.fa -dbtype nucl
run the tblastn shell file
Run solar to conjoin HSPs and filter bad HSPs and redundance.
preparing genewise input directories and files
name gi_NC_009093_ATP6_Galendromus_occidentalis_222_aa is not uniq at /app/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 1163.
name gi_NC_009093_ATP8_Galendromus_occidentalis_53_aa is not uniq at /app/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 4737.
name gi_NC_009093_COX1_Galendromus_occidentalis_517_aa is not uniq at /app/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 7701.
name gi_NC_009093_COX2_Galendromus_occidentalis_221_aa is not uniq at /app/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 10455.
name gi_NC_009093_COX3_Galendromus_occidentalis_275_aa is not uniq at /app/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 14025.
name gi_NC_009093_CYTB_Galendromus_occidentalis_357_aa is not uniq at /app/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 17589.
name gi_NC_009093_ND1_Galendromus_occidentalis_270_aa is not uniq at /app/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 21171.
name gi_NC_009093_ND4_Galendromus_occidentalis_437_aa is not uniq at /app/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 31847.
name gi_NC_009093_ND4L_Galendromus_occidentalis_89_aa is not uniq at /app/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 35423.
name gi_NC_009093_ND5_Galendromus_occidentalis_560_aa is not uniq at /app/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 38985.
run the genewise shell file
running genewise
Warning Error
	Cannot open

caf.fa.genewise/001/gi_NC_005820_ND3_Ornithodoros_porcinus_111_aa_Nan
for read_fasta_file

**Comment by linzhi2013** [comment]
Dear kneubehl,

Sorry for my late response. 

I cannot identify what may cause the problem you met. Would it be possible for you to send your sequence file to me (linzhi2012[MitoZ]Gmail[MitoZ]com)? (please replace [MitoZ] with `@` and `.`, respectively)

Cheers,
Guanliang

**Comment by kneubehl** [comment]
It was a semicolon in the sequence ID of the fasta file (example, >seqid;topology=circular) (>seqid topology=circular, worked)
