### ISSUE TITLE
Problems with bult-in database

### ISSUE THREAD

**Issue by taioba75** [linzhi2013/MitoZ#38]
I am trying to use MitoZ to annotate the mitochondrial genome of an ant assembled from target captured sequences by another application. I get the following error, which I think is internal and has to do with NCBI's taxonomy:

name gi_NC_009093_ATP6_Galendromus_occidentalis_222_aa is not uniq at /users/PAS1032/osu9668/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 1163.
name gi_NC_009093_ATP8_Galendromus_occidentalis_53_aa is not uniq at /users/PAS1032/osu9668/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 4737.
name gi_NC_009093_COX1_Galendromus_occidentalis_517_aa is not uniq at /users/PAS1032/osu9668/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 7701.
name gi_NC_009093_COX2_Galendromus_occidentalis_221_aa is not uniq at /users/PAS1032/osu9668/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 10455.
name gi_NC_009093_COX3_Galendromus_occidentalis_275_aa is not uniq at /users/PAS1032/osu9668/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 14025.
name gi_NC_009093_CYTB_Galendromus_occidentalis_357_aa is not uniq at /users/PAS1032/osu9668/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 17589.
name gi_NC_009093_ND1_Galendromus_occidentalis_270_aa is not uniq at /users/PAS1032/osu9668/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 21171.
name gi_NC_009093_ND4_Galendromus_occidentalis_437_aa is not uniq at /users/PAS1032/osu9668/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 31847.
name gi_NC_009093_ND4L_Galendromus_occidentalis_89_aa is not uniq at /users/PAS1032/osu9668/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 35423.
name gi_NC_009093_ND5_Galendromus_occidentalis_560_aa is not uniq at /users/PAS1032/osu9668/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 38985.

my config file is:

genetic_code = auto
clade = Arthropoda
fastq1 = ./ponera_latreille_1.fastq
fastq2 = ./ponera_latreille_2.fastq
topology = circular
outprefix = plat
thread_number = 4
fastafile = ./plat.fa

Any help will be very welcome!

Cheers!

**Comment by linzhi2013** [comment]
Hi taioba75,

This is a problem with the database, but it should not have a bad effect on the result.

Cheers
