### ISSUE TITLE
A question about gw2gff.pl in the MT annotation toolkit

### ISSUE THREAD

**Issue by Prunoideae** [linzhi2013/MitoZ#40]
Dear Meng:
I'm trying to port the annotation toolkit to Python for my own pipeline usage, but it seems that some output number from *.genewise.gff is unreasonably low:
![image](https://user-images.githubusercontent.com/24620047/71946587-3d20b380-3205-11ea-8153-aeb659f4b4b2.png)
![image](https://user-images.githubusercontent.com/24620047/71946599-43169480-3205-11ea-8e0f-5dc4935a0337.png)

So I digged through the code of MT_annotation_BGI_V1.32, and found that your wrapped version has a unexpected round bracket in line 44 of the gw2gff.pl. Which multiplied the gene length in database by 100 before the overlapped length divide it, then caused the gene coverage dropped.

```perl
my $cover=sprintf("%.2f",$len/($Len{$pid}*100));
```

I also search out the original toolkit repository, and found that their [code ](https://github.com/gigascience/papers/blob/master/zhou2013/MT_annotation_BGI/gw2gff.pl#L44)is correct:

```perl
my $cover=sprintf("%.2f",$len/$Len{$pid}*100);
```

Is this coverage calculation was done intended or just a mistake? My lab is already worked out some result with the uncorrected toolkit, so it could be a serious problem if the results had to be rerun once more.

**Comment by linzhi2013** [comment]
Dear Prunoideae,

thank you very much for the report. I am not quite sure about this.

@lyy005 Hi YY, could please classify this question? thanks a lot!

**Comment by Prunoideae** [comment]
Dear Meng,

After a deeper investigating of the code, it seems that this bug will not affect the major flow of the annotating and filtering, as the calculated coverage data are disposed outside of the BGI toolkit.

But wrong results could affect our judging of the raw data quality and the reliability of the result, especially after I made a profiler for this to examine most numbers of the results, so I made a quick fix on my own platform, and it works out just fine.
