### ISSUE TITLE
findmitoscaf error

### ISSUE THREAD

**Issue by magadancito** [linzhi2013/MitoZ#41]
Hello 

I have a problem with findmitoscaf, I have a mitogenome sequences form Trinity assembly for this reason I run MitoZ with the tag --from_soaptrans, but MitoZ return this error:

2020-01-09 21:53:49
/app/anaconda/bin/python3 /app/release_MitoZ_v2.4-alpha/bin/assemble/filter_by_abundance.py 10  alud_findmitoscaf.hmmtblout.besthit.sim.filtered  /media/osl/trabajo/Moscas_BGI/all_alud.fasta 

Traceback (most recent call last):
  File "/app/release_MitoZ_v2.4-alpha/bin/assemble/filter_by_abundance.py", line 61, in <module>
    main()
  File "/app/release_MitoZ_v2.4-alpha/bin/assemble/filter_by_abundance.py", line 56, in main
    min_abundance=float(min_abundance)
  File "/app/release_MitoZ_v2.4-alpha/bin/assemble/filter_by_abundance.py", line 24, in filter_by_abundance
    abun = m.group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Error occured when running command:
/app/anaconda/bin/python3 /app/release_MitoZ_v2.4-alpha/bin/assemble/filter_by_abundance.py 10  alud_findmitoscaf.hmmtblout.besthit.sim.filtered  /media/osl/trabajo/Moscas_BGI/all_alud.fasta

**Comment by linzhi2013** [comment]
> Hello
> 
> I have a problem with findmitoscaf, I have a mitogenome sequences form Trinity assembly for this reason I run MitoZ with the tag --from_soaptrans, but MitoZ return this error:
> 
> 2020-01-09 21:53:49
> /app/anaconda/bin/python3 /app/release_MitoZ_v2.4-alpha/bin/assemble/filter_by_abundance.py 10 alud_findmitoscaf.hmmtblout.besthit.sim.filtered /media/osl/trabajo/Moscas_BGI/all_alud.fasta
> 
> Traceback (most recent call last):
> File "/app/release_MitoZ_v2.4-alpha/bin/assemble/filter_by_abundance.py", line 61, in
> main()
> File "/app/release_MitoZ_v2.4-alpha/bin/assemble/filter_by_abundance.py", line 56, in main
> min_abundance=float(min_abundance)
> File "/app/release_MitoZ_v2.4-alpha/bin/assemble/filter_by_abundance.py", line 24, in filter_by_abundance
> abun = m.group(1)
> AttributeError: 'NoneType' object has no attribute 'group'
> Error occured when running command:
> /app/anaconda/bin/python3 /app/release_MitoZ_v2.4-alpha/bin/assemble/filter_by_abundance.py 10 alud_findmitoscaf.hmmtblout.besthit.sim.filtered /media/osl/trabajo/Moscas_BGI/all_alud.fasta

Dear magadancito,

yes, this behavior is intended for those input fasta file not generated by SOAPdenovo-Trans (or the mitoAssemble program in MitoZ). 

You should provide fastq files (e.g. 3G bp) to this `findmitoscaf` command and do not use the `--from_soaptrans` parameter.


Cheers

**Comment by magadancito** [comment]
Thanks I changed the flag --findmitoscaf for --annotate in Trinity genome guided mitogenome and works fine. Thanks for you answer.
