### ISSUE TITLE
Not able to used Docker Container of MitoZ

### ISSUE THREAD

**Issue by srimku** [linzhi2013/MitoZ#44]
I have used this command with docker container:
fq1=test.1.fq.gz fq2=test.2.fq.gz outprefix=test docker run -v /home/sridhar/mito/ --rm guanliangmeng/mitoz:2.3 python /home/sridhar/mito/MitoZ.py all2 --genetic_code 5 --clade Arthropoda --insert_size 150 --thread_number 4 --fastq1 $fq1 --fastq2 $fq2 --outprefix $outprefix --fastq_read_length 124 1>m.log 2>m.err

Message in m.err file:

python: can't open file '/home/sridhar/mito/MitoZ.py': [Errno 2] No such file or directory

**Comment by linzhi2013** [comment]
this is because the script `MitoZ.py` is not in `/home/sridhar/mito/MitoZ.py` but  `/app/release_MitoZ_v2.3/MitoZ.py` (https://github.com/linzhi2013/MitoZ/blob/master/version_2.3/INSTALL.md#23-run-the-container)
