### ISSUE TITLE
How update NCBI database in Docker

### ISSUE THREAD

**Issue by magadancito** [linzhi2013/MitoZ#46]
Hi, my question is simple. How can I update NCBI database in docker Container from MitoZ?.
Thanks.

**Comment by linzhi2013** [comment]
Hi magadancito,

you can login the docker container  (without the `--rm` option of `docker run`) and update the NCBI database following the 3.5 section on https://github.com/linzhi2013/MitoZ/blob/master/version_2.3/INSTALL.md.

When finished, you must Create an Image From a Container (e.g. https://www.scalyr.com/blog/create-docker-image/).

cheers

**Comment by magadancito** [comment]
Thank a lot.
