### ISSUE TITLE
installation error: packages incompatibilities

### ISSUE THREAD

**Issue by rderelle** [linzhi2013/MitoZ#47]
Hi,

I have tried to install MitoZ on a Linux server and a MacOs laptop, and in both cases the installation failed due to incompatibilities between python packages.

Here is the error message I obtained on my Mac:

conda create  -n mitozEnv libgd=2.2.4 python=3.6.0 biopython=1.69 ete3=3.0.0b35 perl-list-moreutils perl-params-validate perl-clone circos=0.69 perl-bioperl blast=2.2.31  hmmer=3.1b2  bwa=0.7.12 samtools=1.3.1 infernal=1.1.1 tbl2asn openjdk

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                        

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package libiconv conflicts for:
libgd=2.2.4 -> libiconv
Package libidn11 conflicts for:
tbl2asn -> libidn11
Package perl-exporter-tiny conflicts for:
perl-list-moreutils -> perl-exporter-tiny
Package perl-time-hires conflicts for:
circos=0.69 -> perl-time-hires
Package perl-readonly conflicts for:
circos=0.69 -> perl-readonly
Package xz conflicts for:
python=3.6.0 -> xz=5.2
Package perl-bio-tools-phylo-paml conflicts for:
perl-bioperl -> perl-bio-tools-phylo-paml
...
...

I'm pretty sure I'm doing something wrong since I am apparently the only one getting such error.
Any help would be appreciated.

thanks
Romain

**Comment by linzhi2013** [comment]
Hi Romain,

Firstly, MitoZ will not work on MacOS, unless you use the Docker (maybe Singularity as well) version.

anyway, which version do you try to install? did you check the instructions on https://github.com/linzhi2013/MitoZ/blob/master/version_2.3/INSTALL.md ?

Please firstly run:
`$ conda config --show channels
`
and have a look at the printed results:
```
channels:
  - conda-forge
  - bioconda
  - defaults
  # or 
channels:
  - conda-forge/label/cf201901
  - bioconda/label/cf201901
  - defaults
```

If something is wrong, try:
`$ conda clean -a -y
`
and remove the wrong channels by:
`conda config --remove  channels`

and add the correct channels:
```
$ conda config --add channels defaults
$ conda config --add channels bioconda
$ conda config --add channels conda-forge
```

Finally, install the environment again:
```
$ conda create  -n mitozEnv libgd=2.2.4 python=3.6.0 biopython=1.69 ete3=3.0.0b35 perl-list-moreutils perl-params-validate perl-clone circos=0.69 perl-bioperl blast=2.2.31  hmmer=3.1b2  bwa=0.7.12 samtools=1.3.1 infernal=1.1.1 tbl2asn openjdk
$ conda update -c bioconda tbl2asn ete3
```

Hope this helps!

Cheers
Guanliang

**Comment by rderelle** [comment]
Hi Guanliang

many thanks for getting back to me.

I gave it another try on our linux server and unfortunately I obtained again an incompatibility error message (I have first checked that my channels were correct (they were) and I have cleaned my conda settings using 'conda clean -a -y'):

conda create  -n mitozEnv libgd=2.2.4 python=3.6.0 biopython=1.69 ete3=3.0.0b35 perl-list-moreutils perl-params-validate perl-clone circos=0.69 perl-bioperl blast=2.2.31  hmmer=3.1b2  bwa=0.7.12 samtools=1.3.1 infernal=1.1.1 tbl2asn openjdk

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                        
                                                                                                                                                                              
UnsatisfiableError: The following specifications were found to be incompatible with each other:                                                                               

Package readline conflicts for:
biopython=1.69 -> python=3.6 -> readline[version='6.2.*|7.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
openjdk -> lcms2[version='>=2.9,<3.0a0'] -> libtiff[version='>=4.1.0,<5.0a0'] -> zstd[version='>=1.3.7,<1.3.8.0a0'] -> lz4 -> python[version='>=3.6,<3.7.0a0'] -> readline[version='6.2.*|7.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
python=3.6.0 -> readline=6.2
blast=2.2.31 -> boost=1.60 -> python[version='>=3.6,<3.7.0a0'] -> readline[version='6.2.*|7.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
circos=0.69 -> perl-gd -> libgd -> libtiff[version='>=4.0.3,<4.0.8'] -> zstd[version='>=1.4.4,<1.4.5.0a0'] -> lz4 -> python[version='>=3.6,<3.7.0a0'] -> readline[version='6.2.*|7.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
libgd=2.2.4 -> libtiff=4.0 -> zstd[version='>=1.3.7,<1.3.8.0a0'] -> lz4 -> python[version='>=3.6,<3.7.0a0'] -> readline[version='6.2.*|7.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
ete3=3.0.0b35 -> python=3.5 -> readline[version='7.*|>=7.0,<8.0a0']
perl-bioperl -> perl-bio-tools-run-alignment-tcoffee -> t_coffee -> python=3.6 -> readline[version='6.2.*|7.*|7.0.*|7.0|>=7.0,<8.0a0|>=8.0,<9.0a0']
Package freetype conflicts for:
biopython=1.69 -> reportlab -> freetype[version='2.7|2.7.*|>=2.8.1,<2.9.0a0|>=2.9.1,<3.0a0']
openjdk -> freetype[version='>=2.9.1,<3.0a0']
libgd=2.2.4 -> freetype[version='2.7|2.7.*']
ete3=3.0.0b35 -> pyqt=4.11 -> qt=4.8 -> pango -> freetype=2.7
ete3=3.0.0b35 -> pyqt=4.11 -> qt=4.8 -> freetype[version='2.7|2.7.*']
circos=0.69 -> perl-gd -> libgd -> freetype[version='2.6.*|2.7|2.8.1|2.7|2.7.*|>=2.9.1,<3.0a0']
libgd=2.2.4 -> fontconfig=2.12 -> freetype==2.7
biopython=1.69 -> reportlab -> pillow[version='>=2.4.0'] -> freetype[version='2.7|2.8.*|2.8.1.*|2.8.1|>=2.8,<2.9.0a0']
perl-bioperl -> perl-bioperl-core -> perl-gd -> libgd -> freetype[version='2.6.*|2.7|2.8.1|2.7|2.7.*|>=2.9.1,<3.0a0']
circos=0.69 -> perl-gd -> libgd -> fontconfig=2.12 -> freetype[version='>=2.8,<2.9.0a0|>=2.8.1,<2.9.0a0|>=2.9,<3.0a0']
perl-bioperl -> perl-bioperl-core -> perl-gd -> libgd -> fontconfig=2.12 -> freetype[version='2.7.*|>=2.8,<2.9.0a0|>=2.8.1,<2.9.0a0|>=2.9,<3.0a0']
Package python conflicts for:
circos=0.69 -> perl-gd -> libgd -> libtiff[version='>=4.0.3,<4.0.8'] -> zstd[version='>=1.4.4,<1.4.5.0a0'] -> lz4 -> setuptools -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
ete3=3.0.0b35 -> lxml -> python[version='>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0']
perl-bioperl -> perl-bioperl-core -> perl-gd -> libgd -> libtiff[version='>=4.0.3,<4.0.8'] -> zstd[version='>=1.4.4,<1.4.5.0a0'] -> lz4 -> setuptools -> python[version='2.7.*|3.4.*|3.5.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
python=3.6.0
perl-bioperl -> perl-bio-tools-run-alignment-tcoffee -> t_coffee -> python[version='3.6.*|>=3.6,<3.7.0a0']
libgd=2.2.4 -> libtiff=4.0 -> zstd[version='>=1.3.7,<1.3.8.0a0'] -> lz4 -> setuptools -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
ete3=3.0.0b35 -> python[version='2.7.*|3.5.*|3.6.*']
circos=0.69 -> perl-gd -> libgd -> libtiff[version='>=4.0.3,<4.0.8'] -> zstd[version='>=1.4.4,<1.4.5.0a0'] -> lz4 -> python[version='>=3.6,<3.7.0a0']
blast=2.2.31 -> boost=1.60 -> python[version='3.6.*|>=3.6,<3.7.0a0']
blast=2.2.31 -> boost=1.60 -> numpy[version='>=1.9.3,<2.0a0'] -> python[version='2.7.*|3.4.*|3.5.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
openjdk -> lcms2[version='>=2.9,<3.0a0'] -> libtiff[version='>=4.1.0,<5.0a0'] -> zstd[version='>=1.3.7,<1.3.8.0a0'] -> lz4 -> python[version='>=3.6,<3.7.0a0']
libgd=2.2.4 -> libtiff=4.0 -> zstd[version='>=1.3.7,<1.3.8.0a0'] -> lz4 -> python[version='>=3.6,<3.7.0a0']
openjdk -> lcms2[version='>=2.9,<3.0a0'] -> libtiff[version='>=4.1.0,<5.0a0'] -> zstd[version='>=1.3.7,<1.3.8.0a0'] -> lz4 -> setuptools -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.7,<3.8.0a0|>=3.8,<3.9.0a0']
Package tk conflicts for:
libgd=2.2.4 -> libtiff=4.0 -> zstd[version='>=1.3.7,<1.3.8.0a0'] -> lz4 -> python[version='>=3.6,<3.7.0a0'] -> tk[version='8.5.*|8.6.*|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
biopython=1.69 -> python=3.6 -> tk[version='8.5.*|8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
blast=2.2.31 -> boost=1.60 -> python[version='>=3.6,<3.7.0a0'] -> tk[version='8.5.*|8.6.*|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
ete3=3.0.0b35 -> python=3.5 -> tk[version='8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
openjdk -> lcms2[version='>=2.9,<3.0a0'] -> libtiff[version='>=4.1.0,<5.0a0'] -> zstd[version='>=1.3.7,<1.3.8.0a0'] -> lz4 -> python[version='>=3.6,<3.7.0a0'] -> tk[version='8.5.*|8.6.*|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
python=3.6.0 -> tk=8.5
circos=0.69 -> perl-gd -> libgd -> libtiff[version='>=4.0.3,<4.0.8'] -> zstd[version='>=1.4.4,<1.4.5.0a0'] -> lz4 -> python[version='>=3.6,<3.7.0a0'] -> tk[version='8.5.*|8.6.*|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
biopython=1.69 -> reportlab -> pillow[version='>=2.4.0'] -> tk[version='>=8.6.10,<8.7.0a0']
perl-bioperl -> perl-bio-tools-run-alignment-tcoffee -> t_coffee -> python=3.6 -> tk[version='8.5.*|8.6.*|>=8.6.10,<8.7.0a0|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']
Package sqlite conflicts for:
openjdk -> lcms2[version='>=2.9,<3.0a0'] -> libtiff[version='>=4.1.0,<5.0a0'] -> zstd[version='>=1.3.7,<1.3.8.0a0'] -> lz4 -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='3.13.*|3.20.*|3.9.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0']
python=3.6.0 -> sqlite=3.13
ete3=3.0.0b35 -> python=3.5 -> sqlite[version='>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0']
biopython=1.69 -> python=3.6 -> sqlite[version='3.13.*|3.20.*|3.9.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0']
blast=2.2.31 -> boost=1.60 -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='3.13.*|3.20.*|3.9.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0']
libgd=2.2.4 -> libtiff=4.0 -> zstd[version='>=1.3.7,<1.3.8.0a0'] -> lz4 -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='3.13.*|3.20.*|3.9.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0']
circos=0.69 -> perl-gd -> libgd -> libtiff[version='>=4.0.3,<4.0.8'] -> zstd[version='>=1.4.4,<1.4.5.0a0'] -> lz4 -> python[version='>=3.6,<3.7.0a0'] -> sqlite[version='3.13.*|3.20.*|3.9.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0']
perl-bioperl -> perl-bio-tools-run-alignment-tcoffee -> t_coffee -> python=3.6 -> sqlite[version='3.13.*|3.20.*|3.9.*|>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.1,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.28.0,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0']
Package mmtf-python conflicts for:
biopython=1.69 -> mmtf-python
Package msgpack-python conflicts for:
biopython=1.69 -> numpy=1.10 -> msgpack-python
Package perl-dbd-sqlite conflicts for:
perl-bioperl -> perl-bioperl-core -> perl-dbd-sqlite
Package fontconfig conflicts for:
circos=0.69 -> perl-gd -> libgd -> fontconfig[version='2.11.*|2.12.*|>=2.13.0,<3.0a0|>=2.13.1,<3.0a0']
libgd=2.2.4 -> fontconfig=2.12
perl-bioperl -> perl-bioperl-core -> perl-gd -> libgd -> fontconfig[version='2.11.*|2.12.*|>=2.13.0,<3.0a0|>=2.13.1,<3.0a0']
ete3=3.0.0b35 -> pyqt=4.11 -> qt=4.8 -> fontconfig=2.12
openjdk -> fontconfig[version='>=2.13.1,<3.0a0']

Romain

**Comment by rderelle** [comment]
I found someone having similar issue with another program: https://github.com/nanoporetech/ont_tutorial_pinfish/issues/3

I created an empty environment and then tried to install each package manually.
It worked for python=3.6.0, libgd=2.2.4,  biopython=1.69 but crashed when trying to install ete3=3.0.0b35 due to incompatibility issue:

(mitozEnv) [dereller@bb-pg-login01 ~]$ conda install ete3=3.0.0b35
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                        
                                                                                                                                                                              
UnsatisfiableError: The following specifications were found to be incompatible with each other:                                                                               

Package python conflicts for:
python=3.6.0
Package sqlite conflicts for:
python=3.6.0 -> sqlite=3.13
ete3=3.0.0b35 -> python=3.5 -> sqlite[version='>=3.20.1,<4.0a0|>=3.22.0,<4.0a0|>=3.23.1,<4.0a0|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0']
Package readline conflicts for:
python=3.6.0 -> readline=6.2
ete3=3.0.0b35 -> python=3.5 -> readline[version='7.*|>=7.0,<8.0a0']
Package tk conflicts for:
python=3.6.0 -> tk=8.5
ete3=3.0.0b35 -> python=3.5 -> tk[version='8.6.*|>=8.6.7,<8.7.0a0|>=8.6.8,<8.7.0a0|>=8.6.9,<8.7.0a0']


I do not see any work around.
Romain

**Comment by mptrsen** [comment]
This is apparently something within the Conda dependency network that prevents some specific versions of packages from getting installed. I played around, removing version specifications to end up with a conda env that works. Below is the result of my `conda env export`. You should be able to create an identical environment by saving this yaml to a file (mitoz.yaml or whatever) and use it with `conda env create -n mitoz -f mitoz.yaml`.

The MitoZ installation instructions should be updated to reflect this. It's probably simplest to just supply the environment definition as a yaml file (as below).

```
name: mitoz
channels:
  - etetoolkit
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - alsa-lib=1.1.5=h516909a_1002
  - argtable2=2.13=0
  - biopython=1.76=py36h516909a_0
  - blast=2.9.0=h20b68b9_1
  - boost=1.68.0=py36h8619c78_1001
  - boost-cpp=1.68.0=h11c811c_1000
  - bwa=0.7.17=hed695b0_7
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py36_0
  - circos=0.69.8=0
  - clustalo=1.2.4=h4346872_0
  - curl=7.65.3=hf8cf82a_0
  - dbus=1.13.6=he372182_0
  - dialigntx=1.0.2=hdce4c0c_0
  - ete3=3.1.1=pyhf5214e1_0
  - ete_toolchain=3.0.0=h73706c9_0
  - expat=2.2.9=he1b5a44_2
  - fasttree=2.1=hdfd2403_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_1
  - glib=2.58.3=py36h6f030ca_1002
  - gmp=6.2.0=he1b5a44_1
  - gnutls=3.6.5=hd3a4fd2_1002
  - gst-plugins-base=1.14.5=h0935bb2_1
  - gstreamer=1.14.5=h36ae1b5_1
  - hmmer=3.1b2=3
  - icu=58.2=hf484d3e_1000
  - infernal=1.1.1=0
  - iqtree=1.5.5=he390d98_0
  - jpeg=9c=h14c3975_1001
  - kalign=2.03=h29c49b8_0
  - krb5=1.16.4=h2fd8d38_0
  - lcms2=2.9=hbd6801e_1
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcurl=7.65.3=hda55be3_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgd=2.2.5=h0d07dcb_1005
  - libgfortran-ng=7.3.0=hdf63c60_4
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1005
  - libidn11=1.34=h1cef754_0
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hea5a465_1
  - libxslt=1.1.33=h7d1a2b0_0
  - lxml=3.8.0=py36_0
  - lz4-c=1.8.3=he1b5a44_1001
  - mafft=6.861=h7f9ae3c_0
  - muscle=3.8.31=he5e28f3_0
  - ncurses=6.1=hf484d3e_1002
  - nettle=3.4.1=h1bed415_1002
  - numpy=1.17.5=py36h95a1406_0
  - openjdk=11.0.1=h600c080_1018
  - openssl=1.1.1d=h516909a_0
  - paml=4.8=h48adae2_0
  - pcre=8.43=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - perl-archive-tar=2.32=pl526_0
  - perl-autoloader=5.74=pl526_2
  - perl-bioperl=1.7.2=pl526_11
  - perl-carp=1.38=pl526_3
  - perl-clone=0.42=pl526h516909a_0
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-config-general=2.63=pl526_0
  - perl-digest-perl-md5=1.9=pl526_1
  - perl-dynaloader=1.25=pl526_1
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-font-ttf=1.06=pl526_0
  - perl-gd=2.71=pl526he860b03_0
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-string=1.08=pl526_3
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-math-bezier=0.01=pl526_1
  - perl-math-round=0.07=pl526_1
  - perl-math-vecstat=0.08=pl526_1
  - perl-module-implementation=0.09=pl526_2
  - perl-module-runtime=0.016=pl526_1
  - perl-number-format=1.75=pl526_3
  - perl-params-validate=1.29=pl526h14c3975_1
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-readonly=2.05=pl526_0
  - perl-regexp-common=2017060201=pl526_0
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-set-intspan=1.19=pl526_1
  - perl-statistics-basic=1.6611=pl526_2
  - perl-svg=2.84=pl526_0
  - perl-text-format=0.59=pl526_2
  - perl-threaded=5.26.0=0
  - perl-time-hires=1.9760=pl526h14c3975_1
  - perl-try-tiny=0.30=pl526_1
  - perl-types-serialiser=1.0=pl526_2
  - perl-xml-parser=2.44=pl526h4e0c4b3_7
  - perl-xsloader=0.24=pl526_0
  - perl-yaml=1.29=pl526_0
  - phylobayes=4.1c=hac87e47_0
  - phyml=20160115.patched=hee5dff1_0
  - pip=20.0.2=py36_1
  - pmodeltest=1.4=py36h545a9a4_0
  - pthread-stubs=0.4=h14c3975_1001
  - pyqt=5.9.2=py36hcca6a23_4
  - python=3.6.7=h357f687_1006
  - qt=5.9.7=h52cfd70_2
  - raxml=8.2.11=h6db2ed4_0
  - readline=8.0=hf8c457e_0
  - samtools=1.3.1=h0592bc0_6
  - scipy=1.4.1=py36h921218d_0
  - setuptools=45.1.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.14.0=py36_0
  - slr=1.4.3=h69822e3_0
  - sqlite=3.30.1=hcee41ef_0
  - t_coffee=11.00=h99d273f_0
  - tbl2asn=25.7=0
  - tk=8.6.10=hed695b0_0
  - trimal=1.4=h87cb4c3_0
  - wheel=0.34.2=py36_0
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxtst=1.2.3=h516909a_1002
  - xorg-recordproto=1.14.2=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
```

**Comment by linzhi2013** [comment]
Thank you very much @mptrsen !!!

I was not too familiar with `conda`, and the method  described  in the `Install.md` did  work last year. Perhaps the channels have some changes again (as happened for `conda-forge/label/cf201901`) (or changes in `conda`).

I will firstly test your method and if it works, then I will update the documentation.


All the best
Guanliang

**Comment by rderelle** [comment]
brilliant, it works.

thanks a lot for your help!
Romain

**Comment by gjbex** [comment]
@mptrsen Excellent job, thanks!

**Comment by charlesfoster** [comment]
Thanks @mptrsen! Worked for me too. You've saved me from putting in a service request and annoying my University IT team.

**Comment by zskysafe** [comment]
I found that removing the version number can avoid conflicts.

conda create  -n mitozEnv libgd python biopython ete3 perl-list-moreutils perl-params-validate perl-clone circos perl-bioperl blast  hmmer  bwa samtools infernal tbl2asn openjdk fastp

I have run it without any problem
