### ISSUE TITLE
Question about parameter insert size

### ISSUE THREAD

**Issue by depengl** [linzhi2013/MitoZ#48]
Hi,
I am trying to get Mitochondrial Genome from some SRA data.
How can I I know the insert size of those data if the author didn't list the information?
Can I use --insert_size 250 for all the data no matter how long it actually is  ?

For example:
Run=SRR9308458:  Is this file too large(over200GB) for MITOZ?  How can I know the insert size?
Run=SRR8695259: Insert size is 3000bp(according to the information in Design). Is it too long for MitoZ?

Looking forwart to your reply!

Sincerely,
Depeng

**Comment by linzhi2013** [comment]
> Hi,
> I am trying to get Mitochondrial Genome from some SRA data.
> How can I I know the insert size of those data if the author didn't list the information?
> Can I use --insert_size 250 for all the data no matter how long it actually is ?
> 
> For example:
> Run=SRR9308458: Is this file too large(over200GB) for MITOZ? How can I know the insert size?
> Run=SRR8695259: Insert size is 3000bp(according to the information in Design). Is it too long for MitoZ?
> 
> Looking forwart to your reply!
> 
> Sincerely,
> Depeng

Hi Depeng,

1. generally, the input data should not be more than 5 Gb (maximum 8 Gb). If you're using version 2.4-alpha, MitoZ will extract 5 Gb for you. For MitoZ version 2.3, you need to use other tools to subsample the data, e.g. https://github.com/linzhi2013/extractfq.

2. the insert size will not matter too much. But I won't recommend to use mate-pair data (insert size > 1 Kb), they are error-prone. You can also provide them as single-end data.
