### ISSUE TITLE
RE: mode_3 parameters

### ISSUE THREAD

**Issue by depengl** [linzhi2013/MitoZ#51]
Hi,
It's me again.

Must this parameter "--quick_mode_fa_genes_file" be set whem running mode_3/Multi-Kmer mode?

Since I have multiple jobs to run, I didn't set it. The result seems worse than mode_2 or incomplete.
Pictures below are two result folders. 
This is the error :
Error occured when running command:
/home/depengli/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all  -K 31 -o work31 -s work31.soaptrans.lib -p 40
This the the command I use : 
python3 /home/depengli/release_MitoZ_v2.4-alpha/MitoZ.py all2 --genetic_code auto --clade Arthropoda --outprefix ${base}_multi_kmer \
--thread_number 40 \
--fastq1 ${base}_1.trim.fastq \
--fastq2 ${base}_2.trim.fastq \
--fastq_read_length 150 \
--insert_size 250 \
--run_mode 3 \
--filter_taxa_method 1 \
--fq_size 8 \
--requiring_taxa 'Arthropoda' \
--quick_mode_seq_file=/home/depengli/ncbi/public/genome/${base}_.trim.tmp/${base}_.trim.assembly/work71.hmmout.fa \
--missing_PCGs ND4L ND6 ND2 CYTB COX1 COX2 COX3 ND4 ND1 \
--quick_mode_score_file=/home/depengli/ncbi/public/genome/${base}_.trim.tmp/${base}_.trim.assembly/work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted \
--quick_mode_prior_seq_file=/home/depengli/ncbi/public/genome/${base}_.trim.tmp/${base}_.trim.assembly/work71.hmmtblout.besthit.sim.filtered.fa
#--quick_mode_fa_genes_file quick_mode_fa_genes.txt

![image](https://user-images.githubusercontent.com/58092271/74895285-15655500-5346-11ea-8375-9a0ce18198a4.png) 
![image](https://user-images.githubusercontent.com/58092271/74895297-1bf3cc80-5346-11ea-9c60-3569960e3322.png)

Thank you!

Depeng

**Comment by linzhi2013** [comment]
Hi Depeng,

sorry for my late reply.

`--quick_mode_fa_genes_file` is not necessary, if I am correct.

`Error occured when running command:
/home/depengli/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all -K 31 -o work31 -s work31.soaptrans.lib -p 40`
>this error has nothing to do with `--quick_mode_fa_genes_file` option.
>this error occurs mostly because you do not have enough memory for the `mitoAssemble` command to run. try to use less threads, say `-p 8`.

**Comment by depengl** [comment]
Hi Guanliang,

Thank you！
It's still running.  If I get any result I will let you know.
I am also try to check whether the size of data extraction would affect the result. It seems that for some data bigger size(8Gb) is better but some are not.

I also have a problem about what do the different color columns inside the circular in final visualized pictures refer to? Or where can I find some reference about this? 

Thank you!

Depeng

**Comment by linzhi2013** [comment]
Now MitoZ 3.0 has an option `--kmers` for setting multiple kmers at the same time.
