### ISSUE TITLE
Error when running all module

### ISSUE THREAD

**Issue by gtsiamis** [linzhi2013/MitoZ#52]
I am trying to run the all module but regardless which version of MitoZ (tried 2.2, 2.3 and 2.4-alpha)I am using I am getting the same error

Killed
Error occured when running command:
/app/release_MitoZ_v2.2/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 12
     1127.53 real         0.09 user         0.03 sys

I am using mac OS X 10.13.6 and I am running MitoZ through docker.

I attached the script that I am running - renamed with a txt extension in order to upload the file and also the log and error files.

Any suggestions?
George

PS When I am running the annotate module the program runs without an issue.

[m.err.txt](https://github.com/linzhi2013/MitoZ/files/4235154/m.err.txt)
[m.log.txt](https://github.com/linzhi2013/MitoZ/files/4235155/m.log.txt)
[docker.sh.txt](https://github.com/linzhi2013/MitoZ/files/4235158/docker.sh.txt)

**Comment by linzhi2013** [comment]
Hi gtsiamis,

I would like to know how many base pairs  to run MitoZ?

The error was due to you Mac OS does not have enough memory for the `mitoAssemble` command.  it needs at least ca. 50G - 60 G memory for 2-5 Gbp data. see **section 2.3** on https://github.com/linzhi2013/MitoZ
