### ISSUE TITLE
Museum DNA settings

### ISSUE THREAD

**Issue by Rowley-l** [linzhi2013/MitoZ#53]
I have been using MitoZ on test data for pair end reads for good quality DNA successfully. 

But now i am using museum DNA which is 2 x 75 bp pair end reads and i cant seem to get MITOZ to work.  Would you be able to advise me on appropriate settings. 

Intially i have been running pair end reads on the all module, the command line i used is this: 

fq1=s2_BMNH189112315_R1_combined.fastq.gz
fq2=s2_BMNH189112315_R1_combined.fastq.gz
outprefix=s2_BMNH189112315_mitoz_PE.2

python3 $MITOZ all --genetic_code 2 --clade Chordata --outprefix $outprefix \
--thread_number ${SLURM_CPUS_PER_TASK}  \
--fastq1 $fq1 \
--fastq2 $fq2 \
--fastq_read_length 76 \
--insert_size 10  \
--run_mode 2 \
--filter_taxa_method 1 \
--requiring_taxa 'Chordata'

But the error message reads: quick mode got no result! 

So i wanted to try the Kmer mode with the clean files but the initial assembly didnt produce the required files to run the slow mode. e.g. work71.hmmout.fa  work71.hmmtblout.besthit.sim.filtered.fa, work71.hmmtblout.besthit.sim.filtered.high_abundance_*X.reformat.sorted. 

Is there a way to change the all module to use a 41 in the first instance or can you advise me with this? 

Alternatively, i have merged the pair end reads into single end reads to run the all module with a file that has a greater number of reads. The single end file has the reads ranging from 15-121 bp  with the majority being 60-75 bp so used read length = 71 as this is the lowest number the module can run.

python3 $MITOZ all --genetic_code 2 --clade Chordata --outprefix $outprefix \
--thread_number ${SLURM_CPUS_PER_TASK}  \
--fastq1 $fq1 \
--fastq_read_length 71 \
--insert_size 10  \
--run_mode 2 \
--filter_taxa_method 1 \
--requiring_taxa 'Chordata'

But i have not been able to get a result, the error file reads: 
Error occured when running command:
/mnt/scratch/nodelete/c1532905/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 12 

the output file reads: 
Usable Environment Variables:
=============================
hostname=f02-02.cluster
$SLURM_JOB_ID=37166
$SLURM_NTASKS=1
$SLURM_NTASKS_PER_NODE=1
$SLURM_CPUS_PER_TASK=12
$SLURM_JOB_CPUS_PER_NODE=12
$SLURM_MEM_PER_CPU=102400
2020-02-24 21:20:32
/mnt/scratch/nodelete/c1532905/miniconda3/envs/mitozEnv_3.6/bin/python3 /mnt/scratch/nodelete/c1532905/release_MitoZ_v2.4-alpha/bin/common/extractfq.py -fq1 /mnt/scratch/c1532905/parakeet_combined/s2_merged_BMNH189112315.fastq.gz -outfq1 /mnt/scratch/c1532905/parakeet_combined/s2_BMNH189112315_SE.4.tmp/s2_BMNH189112315_SE.4.partial_fastq/partial.1.fq.gz -size_required 5 -gz  -cache_num 1500000 

Base required: 5,000,000,000
Base got: 997,355,823
2020-02-24 21:31:00
perl /mnt/scratch/nodelete/c1532905/release_MitoZ_v2.4-alpha/bin/filter/raw_reads_filter_SE_v0.5.pl -1 /mnt/scratch/c1532905/parakeet_combined/s2_BMNH189112315_SE.4.tmp/s2_BMNH189112315_SE.4.partial_fastq/partial.1.fq.gz -3 /mnt/scratch/c1532905/parakeet_combined/s2_BMNH189112315_SE.4.tmp/s2_BMNH189112315_SE.4.cleandata/clean.1.fq.gz -n 10 -q 55,20 -z 

input files:
	/mnt/scratch/c1532905/parakeet_combined/s2_BMNH189112315_SE.4.tmp/s2_BMNH189112315_SE.4.partial_fastq/partial.1.fq.gz
output files:
	/mnt/scratch/c1532905/parakeet_combined/s2_BMNH189112315_SE.4.tmp/s2_BMNH189112315_SE.4.cleandata/clean.1.fq.gz
filter parameters:
	k, keep only bases between BEG and END for each read: full length read
	n, the maximun N allowed in single end reads: 10
	q, the maixmum percentage of low quality (ASCII code's integer) bases allowed in single end reads: 55,20
2020-02-24 21:35:25
/mnt/scratch/nodelete/c1532905/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 12

mitoAssemble is based on SoapTrans v1.03 and modified to fit mitogenome assembly by BGI-ENVers

pregraph -s work71.soaptrans.lib -K 71 -p 12 -o work71 
In work71.soaptrans.lib, 1 libs, max seq len 71, max name len 256

12 thread created
read from file:
 /mnt/scratch/c1532905/parakeet_combined/s2_BMNH189112315_SE.4.tmp/s2_BMNH189112315_SE.4.cleandata/clean.1.fq.gz
time spent on hash reads: 17s, 13428746 reads processed
[LIB] 0, avg_ins 10, reverse 0 
0 nodes allocated, 0 kmer in reads, 0 kmer processed
0 linear nodes
time spent on marking linear nodes 0s
time spent on pre-graph construction: 33s

deLowKmer 0, deLowEdge 1
Start to remove kmer of out frequency kmers < 0.100000
0 kmers off
12 thread created
0 linear nodes
time spent on cut kmer: 0s

Start to remove tips of single frequency kmers short than 142
0 tips off
12 thread created
0 linear nodes
Start to remove tips which don't contribute the most links
kmer set 0 done
kmer set 1 done
kmer set 2 done
kmer set 3 done
kmer set 4 done
kmer set 5 done
kmer set 6 done
kmer set 7 done
kmer set 8 done
kmer set 9 done
kmer set 10 done
kmer set 11 done
0 tips off
12 thread created
0 linear nodes
time spent on cutTipe: 0s

0 (0) edges 0 extra nodes
time spent on making edges: 0s

In file: work71.soaptrans.lib, max seq len 71, max name len 256

12 thread created
read from file:
 /mnt/scratch/c1532905/parakeet_combined/s2_BMNH189112315_SE.4.tmp/s2_BMNH189112315_SE.4.cleandata/clean.1.fq.gz
13428746 reads processed
time 0,0,0,0,0,0,0
0 markers outputed
done mapping reads, 0 reads deleted, 0 arcs created
[LIB] 0, avg_ins 10, reverse 0 
time spent on mapping reads: 34s

0 vertex outputed
overall time for lightgraph: 1m

contig -g work71 -M 3 
there're 0 kmers in vertex file
there're 0 edge in edge file
done sort
input 0 edges
0 pre-arcs loaded
start to pinch bubbles, cutoff 0.100000, MAX NODE NUM 30, MAX DIFF 10
0 startingPoints, 0 dheap nodes
0 pairs found, 0 pairs of paths compared, 0 pairs merged
sequenc compare failure: 0 0 0 0
DFibHeap: 0 Nodes allocated
a linear concatenation lap, 0 concatenated
0 edges in graph
time spent on bubblePinch: 0s

Start to remove the low coverage edge < 2
0 edges removed

strict 0, cutLen 142
a cutTipsInGraph lap, 0 tips cut
0 dead arcs removed
a linear concatenation lap, 0 concatenated
0 edges in graph
there're 0 edges
after compacting 0 edges left

delete unlike arc :0
1 time to delete light arcs 
0 loops removed in Graph
Start to remove light arc using the rate 0.050000 and 0.020000
delete light arc :0/0

0 short contig(<48) removed 
a linear concatenation lap, 0 concatenated
0 edges in graph
there're 0 edges
after compacting 0 edges left

0 contigs longer than 72 output
time elapsed: 0m

map -s work71.soaptrans.lib -g work71 -p 12 -K 71 -f 
K = 71
contig len cutoff: 73

there're 0 contigs in file: work71, max seq len 10, min seq len 0, max name len 10
time spent on parse contigs file 0s
12 thread created
time spent on hash reads: 0s
0 nodes allocated, 0 kmer in reads, 0 kmer processed
time spent on De bruijn graph construction: 2s

In file: work71.soaptrans.lib, max seq len 71, max name len 256

12 thread created
0 edges in graph
0 out of 0 (-nan)% reads mapped to contigs
no paired reads found
[LIB] 0, avg_ins 10, reverse 0 
time spent on mapping reads: 14s

overall time for alignment: 0m

scaff -g work71 -F -p 12 
there're 0 grads, 0 reads, max read len 71
K = 71
there're 0 edge in edge file
0 arcs loaded
input 0 contigs
done loading updated edges

Do you have any advice on running the single end file?

**Comment by linzhi2013** [comment]
Dear Rowley-l,

the error from ```Error occured when running command:
/mnt/scratch/nodelete/c1532905/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 12`` is mostly due to there was not enough memory.

You can edit the file `MitoZ.py`:
![image](https://user-images.githubusercontent.com/6203542/75264656-b2cef600-582a-11ea-9aaa-66ff231208d9.png)

for example, change the 877 line to be `kmer = 41`

**Comment by Rowley-l** [comment]
Thank you very much for your help, i will give this a try! :)
