### ISSUE TITLE
error message -- out of memory --

### ISSUE THREAD

**Issue by dalynoll** [linzhi2013/MitoZ#54]
Hello, 
I'm trying to run the module all2 for 1.9Gb genomes, but the process is aborted and the error message says - out of memory--
When I review the processes, I am using only one of the 8 cores. Is there any parallelization option for Mitoz?

-- Out of memory --
Aborted (core dumped)
Error occured when running command:
/app/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 8

Thanks
Daly

**Comment by linzhi2013** [comment]
Hi Daly, 

How many base pairs of your fastq files? (not the size of the file). Normally, you should only use 3-5 Gbp data (no more than 8 Gbp) for mitochondrial genome assembly with MitoZ, and the memory usage can be up to 100 G. Do you have such computer memory available?

If you do not have enough memory even when you use only ~ 5 Gbp data, then you might want to see **section 2.3** on https://github.com/linzhi2013/MitoZ

Cheers

**Comment by Rowley-l** [comment]
Hi, 

I have been experiencing a similar issue though i am using the all module. My files are much larger however, each paired end is aprox 7.2G though mitoZ does filter this down to around 3GB after the filter module. Everytime i try to run the all module on this data i get the memory message, i am running the module with 120G of memory. 

What is the max memory i can use for MitoZ to run? and is the max file size 8Gbp?

I have read section 2.3 so i can give BWA a try first too.

I tried running one file as a single read with 120G and this was succsessful giving me a mitogenome ~16,000bp. 

Thank you. 

Lucy

**Comment by linzhi2013** [comment]
> Hi,
> 
> I have been experiencing a similar issue though i am using the all module. My files are much larger however, each paired end is aprox 7.2G though mitoZ does filter this down to around 3GB after the filter module. Everytime i try to run the all module on this data i get the memory message, i am running the module with 120G of memory.
> 
> What is the max memory i can use for MitoZ to run? and is the max file size 8Gbp?
> 
> I have read section 2.3 so i can give BWA a try first too.
> 
> I tried running one file as a single read with 120G and this was succsessful giving me a mitogenome ~16,000bp.
> 
> Thank you.
> 
> Lucy

Hi Lucy,

Thank you for sharing your experience!

Only the total bases matter, not the file size. Based on my experience, MitoZ could run very long time if you provide too much data, and the memory usage can be high (e.g. 150 G memory for 10 G bp data and 12 threads). I haven't tried much more data and threads and so I do not know what is the maximum memory/threads MitoZ can use.

but, of course, you need to make sure the server has enough memory first.

Cheers
Guanliang
