### ISSUE TITLE
Is there an option to disable compression of raw data files?

### ISSUE THREAD

**Issue by Prunoideae** [linzhi2013/MitoZ#55]
I'm benchmarking MitoZ against my own implementation of the workflow, then I noticed that a hard bottleneck is when the filter tries to compress output clean data.
Since compressing is a single-threaded method and not much we can do to boost CPU clock, a faster solution is to disable to compressing, a filtered clean data file should not be too big for a server to store...

Also, I have a question about your workflow, if extractfq is used to extract about 5Gbps of the data out of the total file, and filter is an independent module besides it, does it means that extractfq will NOT check if extracted sequence is of enough quality or not, where cause a constant loss of data due to the 5Gbps limit? And will this become a severe problem of clean data size, if the total volume of raw data is huge, but the overall (or at the beginning of X Gbps) base quality is quite poor?

**Comment by linzhi2013** [comment]
Hi Prunoideae,

1. you might check the Perl script used for data filtering.

2. You're right, the filter does not stop when it has got 5 G bp data. we should provide this option. thanks for the question.

**Comment by Prunoideae** [comment]
> 2. You're right, the filter does not stop when it has got 5 G bp data. we should provide this option. thanks for the question.

Dear linzhi,
Thank you for your reply, but I think the problem here is not mainly about the filter, is about that the filter will always filter data extracted by extractfq.py, which has limited the size to 5 G bps, so the filtered dataset is always smaller than 5 G bps, since extractfq also extracts sequence of low quality from the raw data. So a solution at my point of view, is to remove the extractfq.py and add a size check for the Perl script.

Maybe I misunderstood something, but it's better than none to declared in a more clear way.
