### ISSUE TITLE
Assembling stucked on test sample

### ISSUE THREAD

**Issue by Prunoideae** [linzhi2013/MitoZ#56]
Dear linzhi,
I'm benchmarking MitoZ against my own implementation of the assemble-findmitoscaf-annotate workflow, but recently I found an archive (SRR1946581) was stucked on the server for over 4 hours.

I thought it was still assembling, but on top command it shows that the modified SOAPdenovo-Trans only takes a very little CPU time (about 3%-4%, but I have set the thread number to 80 equals the number of cores, so at max it should be 8000%), and the memory is not overflowed(10G/1.5T of total physical memory). The file system still have 2T spare at that time, so it's strange that why MitoZ is stuck. When I'm using MEGAHIT, in my assemble module, takes only 40 minute to finish this, and outputted a circular genome of 13/13 PCGs in the end.

I have downloaded the full dataset from SRA using wgets, and extracted with fastq-dump, since MEGAHIT outputs right result in a reasonable time, I wonder if there's something stuck in the assembler when assembling some data. And if other raw data with similar quality, or something else similar, will also stuck on the process of assembling.

I'm not quite familiar to the modified SOAP, so any of your advice could help a lot, thanks!

**Comment by Prunoideae** [comment]
CPUs on my server are 4 `Intel(R) Xeon(R) E7-4830 v2`, I'm running MitoZ on `CentOS 7`.
The last line printed is `80 threads created`, log output before was spammed with `searchKmer: kmer 0 xxx xxxxxxxx xxxxxxxx is not found`.

**Comment by linzhi2013** [comment]
> CPUs on my server are 4 `Intel(R) Xeon(R) E7-4830 v2`, I'm running MitoZ on `CentOS 7`.
> The last line printed is `80 threads created`, log output before was spammed with `searchKmer: kmer 0 xxx xxxxxxxx xxxxxxxx is not found`, where xxx is a long hex string looks like hash or something.

Hi Prunoideae,

Sorry for the late reply.

`80 threads` might be the reason. we have not tried so many threads on MitoZ. and I think this could be a problem even for the original SOAPdenovo-Trans program.



Cheers

**Comment by Prunoideae** [comment]
Dear linzhi,
Thank you for your reply, I terminated the current process and scheduled it to a later batch test, which I will specify a lower thread number.
So is it a dead-locking created just because the high concurrency environment created by specifying thread number to 80 ? But the jam is not always, since I'm running through the whole test sample, I noticed that the `searchKmer: kmer xx is not found` will not happen, or happen lesser in samples that are not stuck, and every stuck sample will have a huge log of missing kmer, maybe there could be other reason?

**Comment by linzhi2013** [comment]
> Dear linzhi,
> Thank you for your reply, I terminated the current process and scheduled it to a later batch test, which I will specify a lower thread number.
> So is it a dead-locking created just because the high concurrency environment created by specifying thread number to 80 ? But the jam is not always, since I'm running through the whole test sample, I noticed that the `searchKmer: kmer xx is not found` will not happen, or happen lesser in samples that are not stuck, and every stuck sample will have a huge log of missing kmer, maybe there could be other reason?

I don't know the answer, honestly. the test sample provided in the MitoZ repo is small. 

Does MEGAHIT outperform SOAPdenovo-Trans for mitochondrial genome assembly? Maybe it can be integrated into MitoZ in the future.

Cheers

**Comment by Prunoideae** [comment]
> Does MEGAHIT outperform SOAPdenovo-Trans for mitochondrial genome assembly? Maybe it can be integrated into MitoZ in the future.
> 
> Cheers

After multiple assembly and have tested it with several datasets my lab currently have, the answer might be yes, MEGAHIT's multi-kmer iterative assemble method seemed to be much better than the SOAPdenovo-Trans, and it concatenated several fragments I met using MitoZ before. Though it is quite resource intensive, under my server environment this used about 2h to assemble a contig, with kmers stepping from 21 to 141 and 80 threads given.

> I don't know the answer, honestly. the test sample provided in the MitoZ repo is small.

I don't mean that the test sample on repo is stuck, MitoZ stucke at a sample provided in your paper (SRR1946581), which made me can't reproduce your result given on the paper.

To be honest, I'm writing a toolkit to provide an alternative selection for MitoZ, named MitoFlex, for more clear code structure, faster process and better assemble quality, I have already opened a repo at https://github.com/Prunoideae/MitoFlex , and going to write my first paper to publish this, sorry for not asking your opinion about this since I'm quite shy, but it always better to ask for the opinion of the original author, even though I have already built this from earth...

Your honesty,
Prunoideae

**Comment by linzhi2013** [comment]
Hi Prunoideae,

That's no problem! And I must admit that the codes in MitoZ are not well organized. MitoZ came when I started to learn Python. I've checked your code, which is much better organized than MitoZ.  I am glad to see new improvments in this mitogenomic field.


Cheers
Guanliang
