### ISSUE TITLE
Annotation fails Mitoz

### ISSUE THREAD

**Issue by Spieler2999** [linzhi2013/MitoZ#57]
Hi,

we have problems with Mitoz, that continusly fails at the annotation step. We have tried reinstalling different components, but Mitoz always fails at the same stage. We have tried different data sets and using a previous installation of Mitoz on a different server but it keeps on failing at the same stage.  Below is the full error report.

thank you for your time and help!

run the genewise shell file
running genewise
convert result to gff3 format
cat: './work71.hmmtblout.besthit.sim.fa.genewise/*/*.genewise': No  
such file or directory
Sorry, the annotation finished with no result!
2020-03-10 14:54:23
rm -rf *.nhr *.nin *.nsq formatdb.log *.tblastn.shell *.length *.blast  
*.blast.filter *.shell *.blast.solar *.blast.solar.filter  
*.blast.solar.filter.table *.blast.solar.filter.table.nonredundance  
*.blast.solar.filter.nr *.genewise *.solar.genewise.gff  
*.solar.genewise.gff.cds

Traceback (most recent call last):
   File  
"/home/lgries/softwares/release_MitoZ_v2.4-alpha/bin/findmitoscaf/filter_taxonomy_by_CDS_annotation.py", line 336, in  
<module>
     requiring_taxa=args.requiring_taxa)
   File  
"/home/lgries/softwares/release_MitoZ_v2.4-alpha/bin/findmitoscaf/filter_taxonomy_by_CDS_annotation.py", line 198, in  
filter_taxa
     with open(cdspos, 'r') as fh, open(cdspos_taxa_log, 'w') as fh_taxalog:
FileNotFoundError: [Errno 2] No such file or directory:  
'work71.hmmtblout.besthit.sim.fa.solar.genewise.gff.cds.position.cds'
Error occured when running command:
/home/lgries/miniconda3/envs/mitozEnv/bin/python3  /home/lgries/softwares/release_MitoZ_v2.4-alpha/bin/findmitoscaf/filter_taxonomy_by_CDS_annotation.py -fa work71.hmmtblout.besthit.sim.fa -MTsoft /home/lgries/softwares/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl -db /home/lgries/softwares/release_MitoZ_v2.4-alpha/bin/profiles/MT_database/Animal_CDS_protein.fa -thread 30 -genetic_code 5 -requiring_taxa 'Arthropoda' -relax 0 -WISECONFIGDIR /home/lgries/softwares/release_MitoZ_v2.4-alpha/bin/annotate/wisecfg -outf  work71.hmmtblout.besthit.sim.filtered.fa

**Comment by linzhi2013** [comment]
Hi, Spieler

can you check the file `work71.hmmtblout.besthit.sim.fa`. MitoZ said `Sorry, the annotation finished with no result!`. Maybe this is the problem.

Guanliang

**Comment by Spieler2999** [comment]
Dear Guanliang,

please see the attached file. There are some sequences in there, but very limited. This was run with 4 Gb of short read BGISEQ data from an invertebrate. Would the sequencing method/length influence the results? 

thank you and kind regards,

Maria

[work71.hmmtblout.besthit.sim copy.fa.txt](https://github.com/linzhi2013/MitoZ/files/4317528/work71.hmmtblout.besthit.sim.copy.fa.txt)

**Comment by linzhi2013** [comment]
> Dear Guanliang,
> 
> please see the attached file. There are some sequences in there, but very limited. This was run with 4 Gb of short read BGISEQ data from an invertebrate. Would the sequencing method/length influence the results?
> 
> thank you and kind regards,
> 
> Maria
> 
> [work71.hmmtblout.besthit.sim copy.fa.txt](https://github.com/linzhi2013/MitoZ/files/4317528/work71.hmmtblout.besthit.sim.copy.fa.txt)

Hi Maria,

It seems that there was not many potential mitochondrial sequences in the attached file:

```
C61708	177
C73518	212
C122884	254
C142188	291
C144684	298
C151194	322
C160064	370
C174916	628
C181872	6298
```
I would suspect that it is because none of them can be annotated as PCGs by `/home/lgries/miniconda3/envs/mitozEnv/bin/python3 /home/lgries/softwares/release_MitoZ_v2.4-alpha/bin/findmitoscaf/filter_taxonomy_by_CDS_annotation.py `

Do you have some more data? maybe use more data can help?

If not, please try the command:

`/app/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all -K 51 -o work51 -s work71.soaptrans.lib -p 8`

This command uses a smaller kmer to assemble. the `work71.soaptrans.lib ` file can be found in the `tmp` directory. After this, you will find a `work51.ScafSeq` file. then run the `findmitoscaf` command to search for the mitochondrial sequences.

the `-K 51` means kmer size. You can try different kmers.


Cheers
Guanliang

**Comment by Spieler2999** [comment]
Dear Guanliang,

The problems keep on continuing and we have no idea on how to solve them. How relevant is the OS system on the server where Mitoz is installed? Any help is highly welcome as we are not able to run Mitoz on any of our servers at the moment.

After using the "/app/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble   
all -K 51 -o work51 -s work71.soaptrans.lib -p 8" command the work51.ScafSeq file is generated.

Running the following command generates another error.
$ python3 MitoZ.py findmitoscaf --genetic_code 5 --outprefix   
Nem4findmitoscaf_Test   --thread_number 12 --from_soaptrans --fastafile   
Nem4Test.tmp/Nem4Test.assembly/work51.scafSeq

Error message:
run the genewise shell file
running genewise
GeneWise6 Matrix calculation: [   57000] Cells 98%
GeneWise6 Matrix calculation: [   99000] Cells 99%
GeneWise6 Matrix calculation: [   70000] Cells 98%
GeneWise6 Matrix calculation: [   46000] Cells 99%
GeneWise6 Matrix calculation: [   76000] Cells 99%
GeneWise6 Matrix calculation: [   36000] Cells 98%
GeneWise6 Matrix calculation: [   51000] Cells 98%
GeneWise6 Matrix calculation: [   10000] Cells 93%
convert result to gff3 format
Annotation finished
2020-03-16 11:27:11
rm -rf *.nhr *.nin *.nsq formatdb.log *.tblastn.shell *.length *.blast   
*.blast.filter *.shell *.blast.solar *.blast.solar.filter   
*.blast.solar.filter.table *.blast.solar.filter.table.nonredundance   
*.blast.solar.filter.nr *.genewise *.solar.genewise.gff   
*.solar.genewise.gff.cds

2020-03-16 11:27:11
sort -k3   
Nem4findmitoscaf_Test.hmmtblout.besthit.sim.fa.solar.genewise.gff.cds.position.cds.taxa | uniq   
>Nem4findmitoscaf_Test.hmmtblout.besthit.sim.fa.solar.genewise.gff.cds.position.cds.taxa.sorted.uniq   

taxa_selected: Arthropoda
result_seq:   {'C428855', 'C384975'}
2020-03-16 11:27:11
/home/lgries/miniconda3/envs/mitozEnv/bin/python3   
/home/lgries/softwares/release_MitoZ_v2.4-alpha/bin/findmitoscaf/filter_hmm-besthit-sim.py Nem4findmitoscaf_Test.hmmtblout.besthit.sim.filtered.fa Nem4findmitoscaf_Test.hmmtblout.besthit.sim   
Nem4findmitoscaf_Test.hmmtblout.besthit.sim.filtered

2020-03-16 11:27:11
/home/lgries/miniconda3/envs/mitozEnv/bin/python3   
/home/lgries/softwares/release_MitoZ_v2.4-alpha/bin/assemble/filter_by_abundance.py 10   Nem4findmitoscaf_Test.hmmtblout.besthit.sim.filtered    
/home/lgries/softwares/release_MitoZ_v2.4-alpha/Nem4Test.tmp/Nem4Test.assembly/work51.scafSeq

All sequences are low abundance (<10X)
2020-03-16 11:27:18
cp    
/home/lgries/softwares/release_MitoZ_v2.4-alpha/Nem4findmitoscaf_Test.result

cp: missing destination file operand after   
'/home/lgries/softwares/release_MitoZ_v2.4-alpha/Nem4findmitoscaf_Test.result'
Try 'cp --help' for more information.
Error occured when running command:
cp    
/home/lgries/softwares/release_MitoZ_v2.4-alpha/Nem4findmitoscaf_Test.result

**Comment by linzhi2013** [comment]
Dear Spieler2999,

Two key things in the log:

1.  the potential sequence
`
result_seq: {'C428855', 'C384975'}
`

2. abundance is to low.
`All sequences are low abundance (<10X)
`

This means that `-K 51` did not generate good results. You might check the sequence length of `C428855', 'C384975'`, and blast them against NCBI nucleotide database and see if they are mitochondrial sequences.

You might: (1) use more data (2) use a lower Kmer size, say `-K 33`.
