### ISSUE TITLE
Error when running Annotation module alone

### ISSUE THREAD

**Issue by ClemSc** [linzhi2013/MitoZ#58]
Hello,

I want to annotate some arthropod mitogenome using MitoZ; however this results in errors.
I tried running MitoZ with conda, and also from the Singularity container, and get the same kind of error. Tried with 2.3 and 2.4.

The sequence name in the fasta file is like this:
>Contig1;topology=circular

The program is called with the following command:
nohup python3 /home/cschneider/git/MitoZ/version_2.3/release_MitoZ_v2.3/MitoZ.py annotate --genetic_code 5 --clade Arthropoda --outprefix MITOZ_Annotation --thread_number 16 --fastafile P1_1__GO.fasta &

And the errors are in the attached file.

[nohup.txt](https://github.com/linzhi2013/MitoZ/files/4323541/nohup.txt)

It seems that a bunch of database files cannot be read  or generated. Any ideas on what is going on ?
Best.
Clem

**Comment by linzhi2013** [comment]
> Hello,
> 
> I want to annotate some arthropod mitogenome using MitoZ; however this results in errors.
> I tried running MitoZ with conda, and also from the Singularity container, and get the same kind of error. Tried with 2.3 and 2.4.
> 
> The sequence name in the fasta file is like this:
> 
> > Contig1;topology=circular
> 
> The program is called with the following command:
> nohup python3 /home/cschneider/git/MitoZ/version_2.3/release_MitoZ_v2.3/MitoZ.py annotate --genetic_code 5 --clade Arthropoda --outprefix MITOZ_Annotation --thread_number 16 --fastafile P1_1__GO.fasta &
> 
> And the errors are in the attached file.
> 
> [nohup.txt](https://github.com/linzhi2013/MitoZ/files/4323541/nohup.txt)
> 
> It seems that a bunch of database files cannot be read or generated. Any ideas on what is going on ?
> Best.
> Clem

Hi Clem,

Below is from your provided file.
`export WISECONFIGDIR=/home/cschneider/git/MitoZ/version_2.3/release_MitoZ_v2.3/bin/annotate/wisecfg
perl /home/cschneider/git/MitoZ/version_2.3/release_MitoZ_v2.3/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl -i MITOZ_Annotation_mitoscaf.fa -d /home/cschneider/git/MitoZ/version_2.3/release_MitoZ_v2.3/bin/profiles/MT_database/Arthropoda_CDS_protein.fa -o ./ -g 5 -cpu 16`

Can you please check if this file exists? `/home/cschneider/git/MitoZ/version_2.3/release_MitoZ_v2.3/bin/profiles/MT_database/Arthropoda_CDS_protein.fa`. For this step, only this database file will be read.

**Comment by linzhi2013** [comment]
> Hello,
> 
> I want to annotate some arthropod mitogenome using MitoZ; however this results in errors.
> I tried running MitoZ with conda, and also from the Singularity container, and get the same kind of error. Tried with 2.3 and 2.4.
> 
> The sequence name in the fasta file is like this:
> 
> > Contig1;topology=circular
> 
> The program is called with the following command:
> nohup python3 /home/cschneider/git/MitoZ/version_2.3/release_MitoZ_v2.3/MitoZ.py annotate --genetic_code 5 --clade Arthropoda --outprefix MITOZ_Annotation --thread_number 16 --fastafile P1_1__GO.fasta &
> 
> And the errors are in the attached file.
> 
> [nohup.txt](https://github.com/linzhi2013/MitoZ/files/4323541/nohup.txt)
> 
> It seems that a bunch of database files cannot be read or generated. Any ideas on what is going on ?
> Best.
> Clem

Hi Clem,

Below is from your provided file.
`export WISECONFIGDIR=/home/cschneider/git/MitoZ/version_2.3/release_MitoZ_v2.3/bin/annotate/wisecfg
perl /home/cschneider/git/MitoZ/version_2.3/release_MitoZ_v2.3/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl -i MITOZ_Annotation_mitoscaf.fa -d /home/cschneider/git/MitoZ/version_2.3/release_MitoZ_v2.3/bin/profiles/MT_database/Arthropoda_CDS_protein.fa -o ./ -g 5 -cpu 16`

Can you please check if this file exists? `/home/cschneider/git/MitoZ/version_2.3/release_MitoZ_v2.3/bin/profiles/MT_database/Arthropoda_CDS_protein.fa`. For this step, only this database file will be read.

**Comment by ClemSc** [comment]
Yes, the file is present at this exact same path `/home/cschneider/git/MitoZ/version_2.3/release_MitoZ_v2.3/bin/profiles/MT_database/Arthropoda_CDS_protein.fa`

**Comment by linzhi2013** [comment]
That's weird.

could you please run the command by yourself and see what would happpen?
`
export WISECONFIGDIR=/home/cschneider/git/MitoZ/version_2.3/release_MitoZ_v2.3/bin/annotate/wisecfg perl /home/cschneider/git/MitoZ/version_2.3/release_MitoZ_v2.3/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl -i MITOZ_Annotation_mitoscaf.fa -d /home/cschneider/git/MitoZ/version_2.3/release_MitoZ_v2.3/bin/profiles/MT_database/Arthropoda_CDS_protein.fa -o ./ -g 5 -cpu 16`

**Comment by ClemSc** [comment]
Same output it seems: [nohup2.txt](https://github.com/linzhi2013/MitoZ/files/4324308/nohup2.txt). This time a bunch of files was generated in the tmp directory:
`MITOZ_Annotation_mitoscaf.fa                        MITOZ_Annotation_mitoscaf.fa.blast.solar.filter.table                MITOZ_Annotation_mitoscaf.fa.nsq
MITOZ_Annotation_mitoscaf.fa.blast                  MITOZ_Annotation_mitoscaf.fa.blast.solar.filter.table.nonredundance  MITOZ_Annotation_mitoscaf.fa.solar.genewise
MITOZ_Annotation_mitoscaf.fa.blast.filter           MITOZ_Annotation_mitoscaf.fa.genewise                                MITOZ_Annotation_mitoscaf.fa.solar.shell
MITOZ_Annotation_mitoscaf.fa.blast.solar            MITOZ_Annotation_mitoscaf.fa.genewise.shell                          MITOZ_Annotation_mitoscaf.fa.tblastn.shell
MITOZ_Annotation_mitoscaf.fa.blast.solar.filter     MITOZ_Annotation_mitoscaf.fa.nhr
MITOZ_Annotation_mitoscaf.fa.blast.solar.filter.nr  MITOZ_Annotation_mitoscaf.fa.nin`

With the Mitoz python script, only MITOZ_Annotation_mitoscaf.fa got created.

**Comment by linzhi2013** [comment]
Hi ClemSc,

Maybe you can send me the input fasta file and I will give a try. You can send it to me email linzhi2012<>gmail<>com, if it is not good for you to post it on github.

**Comment by linzhi2013** [comment]
Dear Clem,
 
Thanks for the file.
 
I located the issue.
 
After I renamed your seqid to `>Contig1 topology=circular`, it worked. The old seqid is: `>Contig1;topology=circular`

Cheers

**Comment by ClemSc** [comment]
Whoa, so simple. Thank you very much !
Clem

Le jeu. 12 mars 2020 à 16:17, Guanliang MENG <notifications@github.com> a
écrit :
