### ISSUE TITLE
Is it possible to condense multiple sequences into a single reference sequence?

### ISSUE THREAD

**Issue by br390** [linzhi2013/MitoZ#59]
I have assembled multiple mitogenomes from a single population and would like to use the assemblies (currently in fasta format) to produce a single reference mitogenome for the population; is this possible in MitoZ?

**Comment by linzhi2013** [comment]
> I have assembled multiple mitogenomes from a single population and would like to use the assemblies (currently in fasta format) to produce a single reference mitogenome for the population; is this possible in MitoZ?

Hi br390,

MitoZ does not use references to assemble mitogenomes, instead, it performs *de novo* assembly.

To assemble mitogenomes with MitoZ, you just need to provide Fastq files.

Cheers

**Comment by br390** [comment]
Hi there,

I have assembled my mitogenomes in MitoZ using the de novo assembly 
pipeline. I was wondering if it was then possible to condense all my 
assembled sequences into a single sequence to act as a reference 
sequence for the population.

Many thanks

**Comment by linzhi2013** [comment]
Hi br390,

MitoZ does not have this function. but this might be what you want: https://www.bioinformatics.nl/cgi-bin/emboss/cons  and https://www.bioinformatics.nl/cgi-bin/emboss/help/cons.

Cheers
