### ISSUE TITLE
tRNA get well annotated but not CDS's

### ISSUE THREAD

**Issue by csmiguel** [linzhi2013/MitoZ#61]
I used the annotate module to annotate a [mitogenome from elephant](https://www.ncbi.nlm.nih.gov/nuccore/DQ316069.1) downloaded from GenBank, so as to test the performance of this module.
```
docker run -v $PWD:/project  --rm guanliangmeng/mitoz:2.4-alpha \
  python3 /app/release_MitoZ_v2.4-alpha/MitoZ.py annotate \
  --genetic_code 2 --clade Chordata \
  --outprefix elephant --thread_number 2 \
  --fastafile DQ31606.fasta
```
tRNAs, rRNA and ATP6 are successfully annotated, but none of the other protein-coding genes.
I get suspicious warnings of this kind which I am not sure how interpret:
```
name gi_NC_KM273123_COX3_Drepane_punctata_261_aa is not uniq at /app/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 36059.
name gi_NC_KP164983_COX3_Drepane_longimana_261_aa is not uniq at /app/release_MitoZ_v2.4-alpha/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl line 240, <IN> line 40505.
```
Other mitogenomes (e.g. from *Rattus norvegicus*) get successful annotations for all features following the commands in chunk 1.

What's going on? Can I manually expand the `release_MitoZ_v2.4-alpha/bin/profiles/MT_database/Animal_CDS_protein.fa` reference to include elephant aa sequences? Can I relax the parameters for annotating from more distance taxa?

Thanks!

**Comment by linzhi2013** [comment]
> What's going on? Can I manually expand the `release_MitoZ_v2.4-alpha/bin/profiles/MT_database/Animal_CDS_protein.fa` reference to include elephant aa sequences? Can I relax the parameters for annotating from more distance taxa?

Hi csmiguel ,

sorry for my late reply.

Yes, you can add your own sequences.

Please add the aa sequences to a special clade, e.g. for chordata is `release_MitoZ_v2.4-alpha/bin/profiles/MT_database/Chordata_CDS_protein.fa`.    for arthropod is `release_MitoZ_v2.4-alpha/bin/profiles/MT_database/Arthropoda_CDS_protein.fa`.  

The file `release_MitoZ_v2.4-alpha/bin/profiles/MT_database/Animal_CDS_protein.fa` is for filtering contamination for the `findmitoscaf` sub-command.

**Comment by zskysafe** [comment]
![图片](https://user-images.githubusercontent.com/51896128/92373902-95f87100-f131-11ea-829b-2c80a0c7c98c.png)
I add the aa sequences to Arthropoda_CDS_protein.fa. As shown in the figure, except for ID, they are written in the format.
The following error occurred
can not find taxid for dispersus
can not find taxid for ['dispersus'], maybe it's a misspelling.
....
KeyError: 'Aleurodicus'
Error occured when running command:
/usr/lib/anaconda3/envs/mitozEnv/bin/python3 /apps/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/bin/annotate/cds_ft_v2.py XJ3-1_L2_142142.cds.position.sorted.revised.filtered 5 XJ3-1_L2_142142_mitoscaf.fa.cds.ft
Where else do I need to add changes？ 
I would be very grateful if you could give me more tips to help me complete annotation of some species.
[log.txt](https://github.com/linzhi2013/MitoZ/files/5182415/log.txt)
