### ISSUE TITLE
Absurdly huge contig outputs

### ISSUE THREAD

**Issue by Prunoideae** [linzhi2013/MitoZ#62]
In recent tests I found a quite strange case:
![image](https://user-images.githubusercontent.com/24620047/79838076-0bfb7600-83e5-11ea-834d-196642364787.png)

The reported sample (SRR1298377) is supplied from the supplymentary data of the paper, but it produced a contig for over 0.7Mbps, which is cleanly almost impossible for animals' mitochondrion genome sequences.
![image](https://user-images.githubusercontent.com/24620047/79837922-c5a61700-83e4-11ea-8061-61b75b0285c5.png)

![image](https://user-images.githubusercontent.com/24620047/79838151-26355400-83e5-11ea-9084-22fe1ad2f9a9.png)

This is manifested through both the output genome file and SVG visualization file, the Circos failed to generate PNG since the file is oversized.

I noticed that the mitoAssemble is a _de novo_ assemble tool adapted from the SOAPdenovo-Trans, maybe could this be a cause for outputting sequences this huge, since the assembler doesn't know that the target mitogenome is relatively small?

**Comment by linzhi2013** [comment]
Hi,

I noticed that this sequence id has a tag `_FivePCGs`. This is not a bug in MitoZ.

mitoAssembler is a denovo assembler.

The reason for output such `_FivePCGs` sequences is to let the users justify what they are (described in the MitoZ paper).  For example, such sequences can be NUMTs, sometimes the researchers might want to get them.


cheers

**Comment by Prunoideae** [comment]
Dear Meng,
Then I guess this could be distinguished from the suspected mitogenome sequences, even though such a sequence can be NUMTs and contains some useful information, it is not a valid mitogenome sequence. So merging this sequence into the mitogenome sequence can output a quite confusing result in the run, and it's a bit redundant if a second run of annotation and visualization is needed.

Also, this huge sequence consumes plenty of the system resource in the latter process as the report shown - 14460s for annotating the sequence, almost twice of the time to finish the pipeline before.

Though it's not a bug, I think this could be improved to make the pipeline more dedicated in assembling mitogenome sequences while retaining the sequences which may have other usage.

Cheers
