### ISSUE TITLE
Failed to create mitozEnv use conda

### ISSUE THREAD

**Issue by XuenaXie** [linzhi2013/MitoZ#64]
Hey, may i ask the following error during installation ,how can i solve it ?
(base) root@lab-System-Product-Name:/data/software/MitoZ/MitoZ-master# conda create  -n mitozEnv libgd=2.2.4 python=3.6.0 biopython=1.69 ete3=3.0.0b35 perl-list-moreutils perl-params-validate perl-clone circos=0.69 perl-bioperl blast=2.2.31  hmmer=3.1b2  bwa=0.7.12 samtools=1.3.1 infernal=1.1.1 tbl2asn openjdk
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: | 
Found conflicts! Looking for incompatible packages.

nsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libtiff conflicts for:
libgd=2.2.4 -> libtiff=4.0
libgd=2.2.4 -> libwebp=0.5 -> libtiff
openjdk -> lcms2[version='>=2.9,<3.0a0'] -> libtiff[version='>=4.0.10,<5.0a0|>=4.1.0,<5.0a0']

Package perl-uri conflicts for:
blast=2.2.31 -> entrez-direct -> perl-uri
perl-bioperl -> perl-bio-featureio -> perl-uri

Package libgcc-ng conflicts for:
perl-clone -> perl[version='>=5.26.2,<5.26.3.0a0'] -> libgcc-ng[version='>=7.2.0']
openjdk -> libgcc-ng[version='>=7.3.0']
blast=2.2.31 -> libgcc-ng[version='>=7.3.0']
perl-list-moreutils -> perl[version='>=5.26.2,<5.27.0a0'] -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.2.0']
tbl2asn -> libidn11 -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.2.0']
samtools=1.3.1 -> zlib[version='>=1.2.11,<1.3.0a0'] -> libgcc-ng[version='>=4.9|>=7.2.0']
perl-clone -> libgcc-ng[version='>=4.9|>=7.3.0']
perl-params-validate -> libgcc-ng[version='>=4.9|>=7.3.0']
biopython=1.69 -> numpy=1.12 -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.2.0']
perl-params-validate -> perl[version='>=5.26.2,<5.26.3.0a0'] -> libgcc-ng[version='>=7.2.0']
python=3.6.0 -> openssl=1.0 -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.2.0']
ete3=3.0.0b35 -> libgcc -> libgcc-ng[version='>=4.9|>=7.2.0|>=7.3.0']
samtools=1.3.1 -> libgcc-ng[version='>=7.3.0']
libgd=2.2.4 -> expat -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.2.0']
openjdk -> alsa-lib[version='>=1.1.5,<1.1.6.0a0'] -> libgcc-ng[version='>=4.9|>=7.2.0']
circos=0.69 -> perl -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.2.0']
perl-bioperl -> perl[version='>=5.26.2,<5.26.3.0a0'] -> libgcc-ng[version='>=4.9|>=7.3.0|>=7.2.0']
blast=2.2.31 -> perl[version='>=5.26.2,<5.26.3.0a0'] -> libgcc-ng[version='>=4.9|>=7.2.0']

Package perl-list-moreutils conflicts for:
blast=2.2.31 -> perl-list-moreutils
perl-bioperl -> perl-bioperl-core==1.007002 -> perl-list-moreutils
perl-list-moreutils
circos=0.69 -> perl-list-moreutils

Package sqlite conflicts for:
biopython=1.69 -> python=3.6 -> sqlite[version='3.13.*|3.20.*|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0|>=3.29.0,<4.0a0|>=3.23.1,<4.0a0|>=3.22.0,<4.0a0|>=3.20.1,<4.0a0|3.9.*|>=3.30.0,<4.0a0|>=3.27.2,<4.0a0']
python=3.6.0 -> sqlite=3.13
ete3=3.0.0b35 -> python=3.6 -> sqlite[version='3.13.*|3.20.*|>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.28.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0|>=3.29.0,<4.0a0|>=3.23.1,<4.0a0|>=3.22.0,<4.0a0|>=3.20.1,<4.0a0|3.9.*|>=3.30.0,<4.0a0|>=3.27.2,<4.0a0']

Package perl-threaded conflicts for:
perl-clone -> perl-threaded
circos=0.69 -> perl-gd -> perl-threaded[version='>=5.22.0']
blast=2.2.31 -> entrez-direct -> perl-threaded
perl-list-moreutils -> perl-threaded
perl-params-validate -> perl-threaded
perl-bioperl -> perl-threaded
circos=0.69 -> perl-threaded

Package perl-xsloader conflicts for:
perl-list-moreutils -> perl-list-moreutils-xs -> perl-xsloader
perl-params-validate -> perl-xsloader
circos=0.69 -> perl-params-validate -> perl-xsloader

Package perl-gd conflicts for:
perl-bioperl -> perl-bioperl-core==1.007002 -> perl-gd
circos=0.69 -> perl-gd

Package perl-carp conflicts for:
circos=0.69 -> perl-params-validate -> perl-carp
perl-bioperl -> perl-bio-asn1-entrezgene -> perl-carp
perl-params-validate -> perl-carp

Package zlib conflicts for:
blast=2.2.31 -> boost=1.60 -> zlib=1.2
samtools=1.3.1 -> curl -> zlib[version='1.2.*|1.2.11']
libgd=2.2.4 -> zlib=1.2
samtools=1.3.1 -> zlib[version='>=1.2.11,<1.3.0a0']
biopython=1.69 -> python=3.6 -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|1.2.8|1.2.11.*']
tbl2asn -> zlib[version='1.2.11.*|1.2.8.*']
libgd=2.2.4 -> freetype[version='2.7|2.7.*'] -> zlib[version='1.2.11|>=1.2.11,<1.3.0a0|1.2.8']
perl-bioperl -> perl-bio-samtools -> zlib[version='>=1.2.11,<1.3.0a0']
python=3.6.0 -> zlib=1.2
circos=0.69 -> perl-gd -> zlib[version='>=1.2.11,<1.3.0a0']
openjdk -> zlib[version='>=1.2.11,<1.3.0a0']
blast=2.2.31 -> zlib[version='>=1.2.11,<1.3.0a0']
ete3=3.0.0b35 -> python=3.6 -> zlib[version='1.2.*|1.2.11|>=1.2.11,<1.3.0a0|1.2.8|1.2.11.*']

Package _openmp_mutex conflicts for:
samtools=1.3.1 -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']
blast=2.2.31 -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']
perl-params-validate -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']
perl-clone -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']
openjdk -> libgcc-ng[version='>=7.3.0'] -> _openmp_mutex[version='>=4.5']

Package perl-exporter conflicts for:
perl-params-validate -> perl-exporter
perl-clone -> perl-exporter
circos=0.69 -> perl-clone -> perl-exporter

Package perl-params-validate conflicts for:
perl-params-validate
circos=0.69 -> perl-params-validate

Package icu conflicts for:
libgd=2.2.4 -> fontconfig=2.12 -> icu[version='>=58.2,<59.0a0']
blast=2.2.31 -> boost=1.60 -> icu=56
openjdk -> fontconfig[version='>=2.13.1,<3.0a0'] -> icu[version='>=58.2,<59.0a0|>=64.2,<65.0a0']
libgd=2.2.4 -> icu=58

Package setuptools conflicts for:
python=3.6.0 -> pip -> setuptools
ete3=3.0.0b35 -> setuptools

Package libpng conflicts for:
openjdk -> libpng[version='>=1.6.37,<1.7.0a0']
openjdk -> fontconfig[version='>=2.13.1,<3.0a0'] -> libpng[version='>=1.6.34,<1.7.0a0|>=1.6.35,<1.7.0a0']

Package perl-pathtools conflicts for:
circos=0.69 -> perl-config-general -> perl-pathtools
blast=2.2.31 -> perl-archive-tar -> perl-pathtools

Package libgcc conflicts for:
perl-params-validate -> libgcc
openjdk -> alsa-lib[version='>=1.1.5,<1.1.6.0a0'] -> libgcc
circos=0.69 -> perl-gd -> libgcc
samtools=1.3.1 -> libgcc
ete3=3.0.0b35 -> libgcc
perl-bioperl -> libgcc
perl-list-moreutils -> perl-app-cpanminus -> libgcc

Package libstdcxx-ng conflicts for:
perl-bioperl -> libgcc -> libstdcxx-ng[version='>=7.2.0']
samtools=1.3.1 -> curl -> libstdcxx-ng[version='>=4.9|>=7.2.0|>=7.3.0']
perl-params-validate -> libgcc -> libstdcxx-ng[version='>=7.2.0']
circos=0.69 -> perl-gd -> libstdcxx-ng[version='>=4.9|>=7.3.0']
blast=2.2.31 -> boost -> libstdcxx-ng[version='>=4.9']
openjdk -> libstdcxx-ng[version='>=7.3.0']
libgd=2.2.4 -> expat -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.2.0']
ete3=3.0.0b35 -> libgcc -> libstdcxx-ng[version='>=4.9|>=7.2.0|>=7.3.0']
biopython=1.69 -> numpy=1.12 -> libstdcxx-ng[version='>=4.9|>=7.3.0|>=7.2.0']
blast=2.2.31 -> libstdcxx-ng[version='>=7.3.0']

Package libgd conflicts for:
circos=0.69 -> perl-gd -> libgd[version='>=2.2.3|>=2.2.4|>=2.2.5,<2.3.0a0']
libgd=2.2.4

Package freetype conflicts for:
openjdk -> freetype[version='>=2.9.1,<3.0a0']
libgd=2.2.4 -> fontconfig=2.12 -> freetype[version='2.6.*|2.7|2.8.1|>=2.8,<2.9.0a0']
biopython=1.69 -> reportlab -> freetype[version='2.7|2.7.*|>=2.8.1,<2.9.0a0|>=2.9.1,<3.0a0']
libgd=2.2.4 -> freetype[version='2.7|2.7.*']

Package perl-list-moreutils-xs conflicts for:
blast=2.2.31 -> perl-list-moreutils -> perl-list-moreutils-xs
perl-list-moreutils -> perl-list-moreutils-xs
circos=0.69 -> perl-list-moreutils -> perl-list-moreutils-xs

Package libiconv conflicts for:
libgd=2.2.4 -> fontconfig=2.12 -> libiconv==1.15
libgd=2.2.4 -> libiconv
tbl2asn -> libidn11 -> libiconv[version='>=1.15,<1.16.0a0']

Package mpc conflicts for:
perl-bioperl -> libgcc -> mpc[version='>=0.8.0']
perl-params-validate -> libgcc -> mpc[version='>=0.8.0']
samtools=1.3.1 -> libgcc -> mpc[version='>=0.8.0']
ete3=3.0.0b35 -> libgcc -> mpc[version='>=0.8.0']

Package numpy conflicts for:
ete3=3.0.0b35 -> scipy -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.11|>=1.11.3,<2.0a0|>=1.14.6,<2.0a0|>=1.18.1,<2.0a0|>=1.9.3,<2.0a0|>=1.9|>=1.15.1,<2.0a0']
ete3=3.0.0b35 -> numpy

Package xorg-libx11 conflicts for:
openjdk -> xorg-libxext -> xorg-libx11=1.6
openjdk -> xorg-libx11

Package libxml2 conflicts for:
ete3=3.0.0b35 -> lxml -> libxml2[version='2.9.*|>=2.9.10,<2.10.0a0|>=2.9.9,<2.10.0a0|>=2.9.8,<2.10.0a0|2.9.3|>=2.9.7,<2.10.0a0|>=2.9.4,<2.10.0a0']
libgd=2.2.4 -> fontconfig=2.12 -> libxml2[version='2.9.*|>=2.9.7,<2.10.0a0|>=2.9.4,<2.10.0a0']
openjdk -> fontconfig[version='>=2.13.1,<3.0a0'] -> libxml2[version='>=2.9.8,<2.10.0a0|>=2.9.9,<2.10.0a0']

Package bzip2 conflicts for:
ete3=3.0.0b35 -> python=3.6 -> bzip2[version='>=1.0.6,<2.0a0']
biopython=1.69 -> python=3.6 -> bzip2[version='>=1.0.6,<2.0a0']
blast=2.2.31 -> bzip2[version='>=1.0.8,<2.0a0']
blast=2.2.31 -> boost -> bzip2=1.0

Package python conflicts for:
biopython=1.69 -> python[version='2.7.*|3.5.*|3.6.*']
biopython=1.69 -> mmtf-python -> python[version='3.4.*|>=3.6,<3.7.0a0|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0']
ete3=3.0.0b35 -> python[version='2.7.*|3.4.*|3.5.*|3.6.*']
python=3.6.0
blast=2.2.31 -> boost=1.60 -> python[version='2.7.*|3.4.*|3.5.*|>=3.8,<3.9.0a0|>=3.6,<3.7.0a0|>=2.7,<2.8.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0|3.6.*']
ete3=3.0.0b35 -> lxml -> python[version='>=2.7,<2.8.0a0|>=3.6,<3.7.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.5,<3.6.0a0']

Package xz conflicts for:
libgd=2.2.4 -> libtiff=4.0 -> xz[version='5.0.*|5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
biopython=1.69 -> python=3.6 -> xz[version='5.0.*|5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
ete3=3.0.0b35 -> python=3.6 -> xz[version='5.0.*|5.2.*|>=5.2.3,<5.3.0a0|>=5.2.4,<5.3.0a0|>=5.2.4,<6.0a0|>=5.2.3,<6.0a0']
python=3.6.0 -> xz=5.2

Package openssl conflicts for:
ete3=3.0.0b35 -> python=3.6 -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a|>=1.1.1b,<1.1.2a']
biopython=1.69 -> python=3.6 -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.1.1a,<1.1.2a|>=1.1.1d,<1.1.2a|>=1.1.1f,<1.1.2a|>=1.1.1e,<1.1.2a|>=1.1.1c,<1.1.2a|>=1.0.2n,<1.0.3a|>=1.0.2m,<1.0.3a|>=1.0.2l,<1.0.3a|>=1.1.1b,<1.1.2a']
python=3.6.0 -> openssl=1.0
samtools=1.3.1 -> curl -> openssl[version='1.0.*|>=1.0.2o,<1.0.3a|>=1.0.2p,<1.0.3a|>=1.0.2m,<1.0.3a']

Package perl conflicts for:
perl-list-moreutils -> perl-exporter-tiny -> perl[version='>=5.26.2,<5.26.3.0a0']
perl-list-moreutils -> perl[version='5.22.0.*|>=5.26.2,<5.27.0a0']

Package perl-clone conflicts for:
perl-bioperl -> perl-bioperl-core==1.007002 -> perl-clone
circos=0.69 -> perl-clone
perl-clone

Package perl-autoloader conflicts for:
perl-clone -> perl-autoloader
circos=0.69 -> perl-clone -> perl-autoloader

Package xorg-libxext conflicts for:
openjdk -> xorg-libxi -> xorg-libxext=1.3
openjdk -> xorg-libxext

Package libssh2 conflicts for:
blast=2.2.31 -> curl[version='>=7.64.1,<8.0a0'] -> libssh2[version='>=1.8.2,<1.9.0a0|>=1.9.0,<2.0a0|>=1.8.2,<2.0a0']
samtools=1.3.1 -> curl[version='>=7.64.1,<8.0a0'] -> libssh2[version='1.*|1.8.*|>=1.8.0,<1.9.0a0|>=1.8.2,<1.9.0a0|>=1.9.0,<2.0a0|>=1.8.2,<2.0a0|>=1.8.0,<2.0a0']

Package pypy3.6 conflicts for:
biopython=1.69 -> python=3.6 -> pypy3.6[version='7.3.0.*|7.3.1.*']
ete3=3.0.0b35 -> python=3.6 -> pypy3.6[version='7.3.0.*|7.3.1.*|>=7.3.1']

Package xorg-libxrender conflicts for:
ete3=3.0.0b35 -> xorg-libxrender
openjdk -> xorg-libxrenderThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/linux-64::__cuda==9.0=0
  - feature:|@/linux-64::__cuda==9.0=0

Your installed CUDA driver is: 9.0
(base) root@lab-System-Product-Name:/data/software/MitoZ/MitoZ-master# conda update -c bioconda tbl2asn ete3
Collecting package metadata (current_repodata.json): done
Solving environment: done
(base) root@lab-System-Product-Name:/data/software/MitoZ/MitoZ-master# source activate mitozEnv
Could not find conda environment: mitozEnv
You can list all discoverable environments with `conda info --envs`.

(base) root@lab-System-Product-Name:/data/software/MitoZ/MitoZ-master# conda info --envs
# conda environments:
#
base                  *  /root/miniconda3

**Comment by linzhi2013** [comment]
Hi,

please refer to https://github.com/linzhi2013/MitoZ/issues/47#issuecomment-581938066.
