### ISSUE TITLE
Error occured when  using soaptrans.lib 

### ISSUE THREAD

**Issue by ycuenot** [linzhi2013/MitoZ#65]
Hello,

I am trying to use Mitoz to compare with NovoPlasty. I am not an expert in bioinformatic so I am trying to use the function assemble with the mitoz_annotate_configfile.txt that I found in example of the v2.4-alpha. I get this error 
**Error occured when running command:
/app/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 8**
Do you have an idea of the problem?
Thanks in advance,
Yves

**Comment by linzhi2013** [comment]
> Hello,
> 
> I am trying to use Mitoz to compare with NovoPlasty. I am not an expert in bioinformatic so I am trying to use the function assemble with the mitoz_annotate_configfile.txt that I found in example of the v2.4-alpha. I get this error
> **Error occured when running command: /app/release_MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 8**
> Do you have an idea of the problem?
> Thanks in advance,
> Yves

Hi Yves,

could you please provide the stderr and stdout files? thanks.

**Comment by ycuenot** [comment]
Hi,

I do not have stderr and stdout files. Where can I find them?
My computer has 83.47 GB of storage and 8Gb of memory. 
Thanks,
Yves

**Comment by linzhi2013** [comment]
> My computer has 83.47 GB of storage and 8Gb of memory.

Hi, 

8Gb of memory is not enough for MitoZ. it requires about 50 to 60 G mem. Please check the `README.md` file for more details.

**Comment by ycuenot** [comment]
Excuse me. So it is the assemble module that need it. When I am using the annotate module, it is working well. 
Thank you,
Yves

**Comment by linzhi2013** [comment]
> Excuse me. So it is the assemble module that need it. When I am using the annotate module, it is working well.
> Thank you,
> Yves

You're right. Only the DBG-based assembly takes high mem, as the 'annotate' command in MitoZ. but other commands such as annotate, visualize only need a small amount of mem.

**Comment by ycuenot** [comment]
Hi,

I come back with more questions, excuse me. I get enough memory to try it now. But I have a problem with soaptrans:
Error occured when running command:
/usr/local/bioinfo/src/MitoZ/MitoZ_v2.4-alpha/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 8
slurmstepd: error: Detected 3 oom-kill event(s) in step 16408080.batch cgroup.

Can you help me?
Thank you, 
Yves

**Comment by linzhi2013** [comment]
Hi Yves,

It seems that you still do not have enough memory forMitoZ. See https://support.nesi.org.nz/hc/en-gb/articles/360000532595-What-does-oom-kill-mean-

>indicates that your job attempted to use more memory (RAM) than Slurm reserved for it.

**Comment by ycuenot** [comment]
Thank you for your response,

When I am running the test that you give, it is working. Do you have an explanation?
Thank you again,
Yves

**Comment by linzhi2013** [comment]
Hi Yves,

The test data is very small, almost every read is mitochondrial reads.

You may check the **2.3 Memory** seciton on https://github.com/linzhi2013/MitoZ

Cheers
