### ISSUE TITLE
Hello Two issues. 

### ISSUE THREAD

**Issue by tania-k** [linzhi2013/MitoZ#68]
Hi there two issues here.
I am trying to download release_MitoZ_v2.4-alpha.tar.bz2 but it's saving it as an html file. I've tried both wget -c and just downloading it from the webpage. How can I obtain this file?

Second I am getting a BUS ERROR in python3 when I try to run INSTALL.md step 3.5. I was able to download the tar.gz file, but the error occurs at the last step NCBITaxa(taxdump_file='/path/to/taxdump.tar.gz') yes I do change the path/to to my path. Is this a space error?

Thank you!

**Comment by linzhi2013** [comment]
Hi Tania Kurbessoian,

Thanks for the issue, I've updated the `INSTALL.md` file, and you can download the package from https://raw.githubusercontent.com/linzhi2013/MitoZ/master/version_2.4-alpha/release_MitoZ_v2.4-alpha.tar.bz2 or  https://raw.githubusercontent.com/linzhi2013/MitoZ/master/version_2.3/release_MitoZ_v2.3.tar.bz2

`a BUS ERROR` probably means that your HOME directory was running out of space. You might refer to https://github.com/linzhi2013/taxonomy_ranks/blob/master/README.md.

Cheers

**Comment by linzhi2013** [comment]
Feel free to raise new issues.
