### ISSUE TITLE
Annotation of circular sequence

### ISSUE THREAD

**Issue by pecosus** [linzhi2013/MitoZ#75]
Hi Guanliang,

I am having some issues to annotate a circular sequence of 15077bp, particular on the end-start sequence of the circular genome. For instance, I've already know that CYTB gene spans from 14120bp to 197bp. Instead, MitoZ annotation module just annotates a partial sequence for this gene (~14120 - 15070bp) and it seems that it can't cross from the end to the start of the genome to complete the annotation, and finally reports that this gene has no stop codon.

Even in the publication of MitoZ, it can be seen in the circos plot that there is no annotation at all in the first ~200bp of the genome.

I don't know if this is a truly issue or simply a miss configuration problem.

Cheers.

**Comment by linzhi2013** [comment]
> Hi Guanliang,
> 
> I am having some issues to annotate a circular sequence of 15077bp, particular on the end-start sequence of the circular genome. For instance, I've already know that CYTB gene spans from 14120bp to 197bp. Instead, MitoZ annotation module just annotates a partial sequence for this gene (~14120 - 15070bp) and it seems that it can't cross from the end to the start of the genome to complete the annotation, and finally reports that this gene has no stop codon.
> 
> Even in the publication of MitoZ, it can be seen in the circos plot that there is no annotation at all in the first ~200bp of the genome.
> 
> I don't know if this is a truly issue or simply a miss configuration problem.
> 
> Cheers.

Hi percosus,

Because the second fragment is only 197bp in length, it could be difficult for MitoZ to know that it's part of the CYTB gene.

Solution:
Since you already know that your sequence is circular, please break the mitogenome on other sites without gene annotations (PCG, rRNA, tRNA), then re-annotate the sequence again.

Cheers
Guanliang

**Comment by pecosus** [comment]
Thank you very much for the feedback!
