### ISSUE TITLE
problem about 1.adapter.list.gz

### ISSUE THREAD

**Issue by zhongxing123** [linzhi2013/MitoZ#76]
hi，
 I am a novice in using Mitoz. I don’t know what the format of  1.adapter.list.gz is when I want to filter the adapter.
could you give me some suggestions about this？
thanks
zhongxing

**Comment by linzhi2013** [comment]
> hi，
> I am a novice in using Mitoz. I don’t know what the format of 1.adapter.list.gz is when I want to filter the adapter.
> could you give me some suggestions about this？
> thanks
> zhongxing

Hi zhongxing,

the  1.adapter.list.gz  files actually are files generated by BGI. But I don't know if they still generate such a file now. If you don't have such a file, just ignore this parameter ---- this assumes that your data are free from adapter-contaminations. And if your data is from sequencing companies, the data normally is "clean" data, which means that you don't need to use the "all" command, just use the "all2" command in MitoZ.

Cheers
Guanliang
