### ISSUE TITLE
I don't want parts of fq.gz

### ISSUE THREAD

**Issue by zskysafe** [linzhi2013/MitoZ#77]
all2 and  assemble module both have .partial_fastq .
my data is not large, so I not want to use part of fastq to assemble mitogenome.

**Comment by linzhi2013** [comment]
> all2 and assemble module both have .partial_fastq .
> my data is not large, so I not want to use part of fastq to assemble mitogenome.

Hi zskysafe,

To meet your end, please use version 2.3.

**Comment by zskysafe** [comment]
> 
> 
> > all2 and assemble module both have .partial_fastq .
> > my data is not large, so I not want to use part of fastq to assemble mitogenome.
> 
> Hi zskysafe,
> 
> To meet your end, please use version 2.3.

Thanks for your help. I  hope that mitoz can not extract some data in assemble mode

**Comment by linzhi2013** [comment]
Sure, MitoZ will support this in the next release.
