### ISSUE TITLE
A lot of missing genes in the annotation, whereas they are all found during the assembly

### ISSUE THREAD

**Issue by HeloiseMuller** [linzhi2013/MitoZ#80]
Hi,

I am trying to use the all module to assemble and search for an arthropode mitogenome. 
It seems to work fine, I don't get any error messages but I am surprised that it finds only two protein coding genes. MitoZ assembled a complete circular mitogenome of 15,330bp. The summary.txt file tells me that the missing genes might be found in the *.high_abundance and *.low_abundance files. Indeed, I can find the 13 protein coding genes in the file work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted. They are located on the scaffold corresponding to the mitogenome. In addition, if I map by tblastn the protein coding genes of the mtDNA of a closely related species, I am also able to find all the protein coding genes on this scaffold. Thus, I am wondering how come the 13 coding genes are not kept in the final annotation  ? 

This is the command I used:
`python $path_MitoZ/MitoZ.py all --genetic_code 5 --clade Arthropoda --outprefix SEN1 
       --thread_number 16 
       --fastq1 $raw1 
       --fastq2 $raw2 
       --fastq_read_length 150 
       --run_mode 2 
       --filter_taxa_method 1 
       --requiring_taxa 'Arthropoda'`

This is the nohup:
[run_mitoz_quick.zip](https://github.com/linzhi2013/MitoZ/files/5196023/run_mitoz_quick.zip)

This is the summarry.txt file:
[summary.zip](https://github.com/linzhi2013/MitoZ/files/5196070/summary.zip)

And the work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted file:
[work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted.zip](https://github.com/linzhi2013/MitoZ/files/5196029/work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted.zip)

I also tried the muti k-mer mode with the all2 module, hoping it could find the other protein coding genes, but I got an error message. 

This is the command I used:
`python $path_MitoZ/MitoZ.py all2 --genetic_code 5 --clade Arthropoda --outprefix SEN1 
        --thread_number 16 
        --fastq1 $out_quick/tmp/SEN1.cleandata/clean.1.fq.gz --fastq2 $out_quick/tmp/SEN1.cleandata/clean.2.fq.gz 
        --fastq_read_length 150 
        --run_mode 3 
        --filter_taxa_method 1 
        --requiring_taxa 'Arthropoda' 
        --quick_mode_seq_file $out_quick/SEN1.result/SEN1.fasta
        --quick_mode_fa_genes_file $out_quick/SEN1.result/quick_mode_fa_genes.txt  
        --missing_PCGs ND2 COX1 COX2 COX3 ND3 ND5 ND4 ND4L ND6 CYTB ND1 
        --quick_mode_score_file $out_quick/tmp/SEN1.assembly/work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted   
        --quick_mode_prior_seq_file $out_quick/tmp/SEN1.assembly/work71.hmmtblout.besthit.sim.filtered.fa`

Where my quick_mode_fa_genes.txt is simply:
scaffold191011 ATP6 ATP8

Here is the nohup:
[run_mitoZ_bis.zip](https://github.com/linzhi2013/MitoZ/files/5196033/run_mitoZ_bis.zip)

Finally, I read that too much data could lead to bad results so I used the script extracfq on my clean reads to extract 3Gbp. I ran again the quick mode with the all2 module but the results are worst: the mitogenome is not circular anymore and although it finds 3 protein coding genes, one rRNA genes is missing. 

Do you know why 11 out of the 13 coding genes are not kept in the final annotation? And do you no why the multi k-mer mode did not work? 

Best,

Héloïse

**Comment by linzhi2013** [comment]
Hi Heloise,

Thanks for reporting the problem.

It's indeed weird, since I can see 13 PCGs already present in the `work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted.zip` file:
```
>scaffold191011 Locus_1308343_0 63.0 LINEAR length=15348 score=1103.773
ND2     529     1543    9       920     +       4
COX1    1724    3270    8       1532    +       4
COX2    3333    4017    2       668     +       4
ATP8    4157    4318    2       124     +       4
ATP6    4312    4989    1       661     +       4
COX3    4989    5777    9       785     +       4
ND3     5842    6198    11      353     +       4
ND5     6651    8369    15      1674    -       4
ND4     8457    9792    1       1287    -       4
ND4L    9833    10120   20      278     -       4
ND6     10304   10808   52      422     +       4
CYTB    10845   11983   14      1129    +       4
ND1     12064   12994   8       913     -       4
```

Therefore, `scaffold191011` is the selected circular mitogenome, which was parsed to gene annotation. Do you mind sending this sequences to my email linzhi2012<MitoZ>gmail<MitoZ>com so I can try to annotate it alone? Please do not post the mitogenome sequence to Github if it should be treated confidentially.

Cheers
Guanliang

**Comment by linzhi2013** [comment]
For the record, below was from Heloise

> Hi Guanliang,
> 
> I used the version 2.3 too. But I installed it with anaconda. 
> 
> So I ran MitoZ with the module annotate, with the exact same command as yours, and with the modification on the header of the fasta file. It found only 6 CPGs. I ran it again, with only 1 thread this time, and it worked, it found the 13 CPGs. 
> 
> I am sorry it was just about that (and the header of the fasta too I suppose), but I was sure I would get an error message if there was an issue with the memory (which I did not).
> 
> Thank you very much for your help.
