### ISSUE TITLE
Error in assembly process

### ISSUE THREAD

**Issue by zskysafe** [linzhi2013/MitoZ#82]
``
python3 $DIR_mitoz/MitoZ.py all2 --genetic_code 5 --clade Arthropoda --outprefix $name \
--thread_number 8 \
--fastq1 $fq1 \
--fastq2 $fq2 \
--fastq_read_length 150 \
--insert_size 250 \
--run_mode 2 \
--filter_taxa_method 1 \
--requiring_taxa 'Arthropoda' >> mitoz.log 2>&1
``

My settings for mitoz are shown above.
I didn't make any changes to the files of mitoz. The environment of mitozenv follows the installation instructions.
About 6G of data was used.
There is a Error with the operation of the following section.
··
run the genewise shell file
running genewise
convert result to gff3 format
cat: './work71.hmmtblout.besthit.sim.fa.genewise/*/*.genewise': No such file or directory
Sorry, the annotation finished with no result!
··
work71.ScafSeq is not empty 
![图片](https://user-images.githubusercontent.com/51896128/92982710-11f80d80-f4d2-11ea-98de-62c773503e47.png)
[mitozSPHD.log](https://github.com/linzhi2013/MitoZ/files/5211949/mitozSPHD.log)

**Comment by Prunoideae** [comment]
Could you please execute this command in the corresponding conda environment and send the console output to me?

```bash
makeblastdb -in [some nucleotide fasta file] -dbtype nucl
```

In the log I found something unusual elsewhere, maybe that will be the real cause of your issue.

**Comment by zskysafe** [comment]
``
animal1@animalia:~$ source activate mitozEnv
(mitozEnv) animal1@animalia:~$ makeblastdb -in [some nucleotide fasta file] -dbtype nucl
makeblastdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
```
Is this how it works?

**Comment by Prunoideae** [comment]
I guess your `blast` have not found a correct `libssl.so` to load, so even a wrong filename is given, the program refused to start and print some error message.

You may export the `libssl.so`'s file path to environment variable `LD_LIBRARY_PATH` or make a symbiotic link for program to find a valid file to load. Since this step is very based on the `tblastn`, it's clear that the program will be dysfunctional if a blast search cannot be applied.

**Comment by zskysafe** [comment]
It may be a digression, but I have to ask for help.
```
@animalia:~$ makeblastdb -in [some nucleotide fasta file] -dbtype nucl
USAGE
  makeblastdb [-h] [-help] [-in input_file] [-input_type type]
    -dbtype molecule_type [-title database_title] [-parse_seqids]
    [-hash_index] [-mask_data mask_data_files] [-mask_id mask_algo_ids]
    [-mask_desc mask_algo_descriptions] [-gi_mask]
    [-gi_mask_name gi_based_mask_names] [-out database_name]
    [-max_file_sz number_of_bytes] [-logfile File_Name] [-taxid TaxID]
    [-taxid_map TaxIDMapFile] [-version]

DESCRIPTION
   Application to create BLAST databases, version 2.5.0+

Use '-help' to print detailed descriptions of command line arguments
========================================================================

Error: Too many positional arguments (1), the offending value: nucleotide
Error:  (CArgException::eSynopsis) Too many positional arguments (1), the offending value: nucleotide

@animalia:~$ source activate mitozEnv

(mitozEnv) @animalia:~$ makeblastdb -in [some nucleotide fasta file] -dbtype nucl
makeblastdb: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

animal1@animalia:~$ echo $PATH
/snap/core18/1885/usr/lib/x86_64-linux-gnu:/apps/bbmap:/usr/lib/anaconda3/bin:/usr/lib/anaconda3/envs/mitozEnv/bin:_/usr/lib/anaconda3/condabin:/snap/core18/1885/usr/lib/x86_64-linux-gnu_:/apps/bbmap:/usr/lib/anaconda3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```
As shown in the first command, I have added the missing path and can run it.
But when I entered mitozenv, it still couldn't find the file.
However, the output path clearly has this path.
I think maybe we need to add this path to the environment path of mitozenv?
But still, I don't know Which file should be selected to enter  `/ usr / lib / anaconda3 / envs / mitozenv` .

**Comment by Prunoideae** [comment]
What about your `LD_LIBRARY_PATH` ? This environment variable also sets the path for program to look for a valid library file. Also, it's maybe required to export path after the activation of environment, since `conda activate` changes many of the variable to fit into the environment.

**Comment by zskysafe** [comment]
> 
> 
> What about your `LD_LIBRARY_PATH` ? This environment variable also sets the path for program to look for a valid library file. Also, it's maybe required to export path after the activation of environment, since `conda activate` changes many of the variable to fit into the environment.

I use  MitoZ/version_2.4-alpha/mitozEnv.yaml  solved the problem.
I'm closing this issue

**Comment by linzhi2013** [comment]
Thanks @Prunoideae  for helping figure it out.

I'm still not sure what caused the problem, but it is the kind of environment dependency problem, which is very upsetting to everyone and will waste much time for both users and developers, and that's why I provided the Docker image of MitoZ.

I think this was not caused by the MitoZ version, both version 2.3 and version-2.4-alpha share the same environment dependencies if you set up the mitozEnv environment uses the following instructions (in the INSTALL.md file):

> 3.3 Install dependency with conda command
> Thanks to @mptrsen (see https://github.com/linzhi2013/MitoZ/issues/47#issuecomment-581938066), the quickest way to create a mitozEnv environment is:
> 
> \# find the mitozEnv.yaml file after you download the source codes, see section 3.6 below
> $ conda env create -n mitozEnv -f mitozEnv.yaml
