### ISSUE TITLE
Please install the mitozEnv environment with the Python version (3.6) specified in INSTALL.md file

### ISSUE THREAD

**Issue by ponchorox** [linzhi2013/MitoZ#86]
Hello, I tried running on a server with the latest python version and shows this error:

ERROR: Unable to locate a modulefile for 'python/3'
2020-09-16 19:57:06
/LUSTRE/Genetica/cquintero/anaconda3/envs/mitozEnv/bin/python3 /LUSTRE/Genetica/cquintero/Amanita/Programs/release_MitoZ_v2.4-alpha/bin/common/extractfq.py -fq1 /LUSTRE/Genetica/cquintero/Amanita/RH-9_S64_L002_R1_001.fastq.gz -fq2 /LUSTRE/Genetica/cquintero/Amanita/RH-9_S64_L002_R2_001.fastq.gz -outfq1 /LUSTRE/Genetica/cquintero/Amanita/Programs/release_MitoZ_v2.4-alpha/Prueba.tmp/Prueba.partial_fastq/partial.1.fq.gz -outfq2 /LUSTRE/Genetica/cquintero/Amanita/Programs/release_MitoZ_v2.4-alpha/Prueba.tmp/Prueba.partial_fastq/partial.2.fq.gz -size_required 5 -gz  -cache_num 1500000 

Base required: 5,000,000,000
Base got: 3,415,680,098
Traceback (most recent call last):
  File "MitoZ.py", line 2004, in <module>
    program_begin_clock = time.clock()
AttributeError: module 'time' has no attribute 'clock'

Looking this up shows that the module time has been deprecated in ver 3.8, do you recommend downgrading (sadly this is impossible for me) or is there another solution at the moment?

**Comment by linzhi2013** [comment]
Please reinstall the environment with the instruction in the INSTALL.md file.


3.3 Install dependency with conda command
**Thanks to @mptrsen (see https://github.com/linzhi2013/MitoZ/issues/47#issuecomment-581938066), the quickest way to create a mitozEnv environment is:**

# find the mitozEnv.yaml file after you download the source codes, see section 3.6 below
```$ conda env create -n mitozEnv -f mitozEnv.yaml```
If this method works, you can jump to section 3.4 directly.

**Comment by linzhi2013** [comment]
I don't know why you install the environment with Python 3.8, since the instructions only use Python 3.6, even if you follow **3.3.1 Set up channels** and **3.3.2 Set up an isolated enviroment for MitoZ**.

**Comment by linzhi2013** [comment]
You may also try to use the Docker version, which is the fastest way to use MitoZ.

Please feel free to raise other kinds of issues.

Cheers
