### ISSUE TITLE
There seems to be a little problem in the summary document

### ISSUE THREAD

**Issue by zskysafe** [linzhi2013/MitoZ#87]
![图片](https://user-images.githubusercontent.com/51896128/95654917-139b0c80-0b36-11eb-994d-6e7a8d711f1c.png)
I found that the summery.txt in the results of the mitoz assembly does not match the termination position of the genome in .fa.gbf. 
The two documents in the terminated position are one place apart.
It doesn't seem to be an accident

**Comment by linzhi2013** [comment]
yes, it's a bug here.

thanks for pointing it out!

**Comment by cgjosephlee** [comment]
Hi Guanliang, 
Will this be fixed? The issue is closed.
If not, I might be able to help fixing this. How do I contribute to this project? since you didn't use version control for your codes.
