### ISSUE TITLE
-run_mode 3 command syntax

### ISSUE THREAD

**Issue by dougwyu** [linzhi2013/MitoZ#9]
Hello,

I would like to use -run_mode 3, but i'm not clear about which files to use.  You provide this as your example:

> python3 MitoZ.py all2 --genetic_code 5 --clade Arthropoda --outprefix test \
> --thread_number 12 --fastq1 clean.1.fq.gz --fastq2 clean.2.fq.gz \
> --fastq_read_length 150 --insert_size 250 \
> --run_mode 3 \
> --filter_taxa_method 1 \
> --requiring_taxa 'Arthropoda' \
> --quick_mode_seq_file quickMode.fa \
> --quick_mode_fa_genes_file quick_mode_fa_genes.txt  \
> --missing_PCGs ND4L ND6 ND2 \
> --quick_mode_score_file work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted  \
> --quick_mode_prior_seq_file work71.hmmtblout.besthit.sim.filtered.fa

But I don't know how to write the command with these output files:

> IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus.cds
> IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus.fasta
> IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus.misc_feature
> IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus.rrna
> IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus.trna
> IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus_mitoscaf.fa.gbf
> IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus_mitoscaf.fa.sqn
> IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus_mitoscaf.fa.tbl
> IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus_mitoscaf.fa.val
> README.txt
> circos.png
> circos.svg
> errorsummary.val
> summary.txt
> work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted.Not-picked
> work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted.Not-picked.fa
> work71.hmmtblout.besthit.sim.filtered.low_abundance
> work71.hmmtblout.besthit.sim.filtered.low_abundance.fasta
> work71.mitogenome.fa
> work71.most_related_species.txt

- which mitogenome fasta file to use?  
- which work71.hmmtblout.besthit.sim.filtered files to use?
- there are no clean.{1,2}.fq.gz files. Should I use `python3 MitoZ.py all` instead?

This is my attempt:

> python3 MitoZ.py all2 --genetic_code 5 --clade Arthropoda --outprefix test \
> --thread_number 12 --fastq1 clean.1.fq.gz --fastq2 clean.2.fq.gz \
> --fastq_read_length 150 --insert_size 250 \
> --run_mode 3 \
> --filter_taxa_method 1 \
> --requiring_taxa 'Arthropoda' \
> --quick_mode_seq_file work71.mitogenome.fa \
> --quick_mode_fa_genes_file work71.mitogenome_genes.txt  \
> --missing_PCGs ATP6 ATP8 COX3 ND2 ND3 ND4 ND4L ND5 \
> --quick_mode_score_file work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted.Not-picked  \
> --quick_mode_prior_seq_file work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted.Not-picked.fa

Where `work71.mitogenome_genes.txt ` contains the following text:

> scaffold41 ND1 CYTB ND6
> C5251 COX2 COX1

_____________

This is from the summary.txt

> #Seq_id        Length(bp)     Circularity    Closely_related_species
> scaffold41     2499           no             Diadegma semiclausum
> C5251          2608           no             Diadegma semiclausum
> 
> 
> #Seq_id        Start  End    Length(bp) Direction  Type   Gene_name  Gene_prodcut                      Total_freq_occurred
> --------------------------------------------------------------------------------------------------------------------------
> scaffold41     21     930    910        +          CDS    ND1        NADH dehydrogenase subunit 1      1              
> scaffold41     933    1000   68         -          tRNA   trnS(uga)  tRNA-Ser                          1              
> scaffold41     1032   2191   1160       -          CDS    CYTB       cytochrome b                      1              
> scaffold41     2183   2486   304        -          CDS    ND6        NADH dehydrogenase subunit 6      1              
> C5251          92     156    65         -          tRNA   trnD(guc)  tRNA-Asp                          1              
> C5251          155    227    73         -          tRNA   trnK(cuu)  tRNA-Lys                          1              
> C5251          227    903    677        -          CDS    COX2       cytochrome c oxidase subunit II   1              
> C5251          962    2501   1540       -          CDS    COX1       cytochrome c oxidase subunit I    1              
> 
> 
> Protein coding genes totally found:  5
> tRNA genes totally found:            3
> rRNA genes totally found:            0
> --------------------------------------
> Genes totally found:                 8
> 
> 
> Potential missing genes:
> #Gene             total_missing_number
> --------------------------------------
> ATP6                                 1
> ATP8                                 1
> COX3                                 1
> ND2                                  1
> ND3                                  1
> ND4                                  1
> ND4L                                 1
> ND5                                  1
> l-rRNA                               1
> s-rRNA                               1
> tRNA-Ala                             1
> tRNA-Arg                             1
> tRNA-Asn                             1
> tRNA-Cys                             1
> tRNA-Gln                             1
> tRNA-Glu                             1
> tRNA-Gly                             1
> tRNA-His                             1
> tRNA-Ile                             1
> tRNA-Leu                             2
> tRNA-Met                             1
> tRNA-Phe                             1
> tRNA-Pro                             1
> tRNA-Ser                             1
> tRNA-Thr                             1
> tRNA-Trp                             1
> tRNA-Tyr                             1
> tRNA-Val                             1
> 
> The missing genes might be foud from the
> '*.high_abundance*' and '*.low_abundance*' files!
>

**Comment by linzhi2013** [comment]
> Hello,
> 
> I would like to use -run_mode 3, but i'm not clear about which files to use. You provide this as your example:
> 
> > python3 MitoZ.py all2 --genetic_code 5 --clade Arthropoda --outprefix test 
> > --thread_number 12 --fastq1 clean.1.fq.gz --fastq2 clean.2.fq.gz 
> > --fastq_read_length 150 --insert_size 250 
> > --run_mode 3 
> > --filter_taxa_method 1 
> > --requiring_taxa 'Arthropoda' 
> > --quick_mode_seq_file quickMode.fa 
> > --quick_mode_fa_genes_file quick_mode_fa_genes.txt  
> > --missing_PCGs ND4L ND6 ND2 
> > --quick_mode_score_file work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted  
> > --quick_mode_prior_seq_file work71.hmmtblout.besthit.sim.filtered.fa
> 
> But I don't know how to write the command with these output files:
> 
> > IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus.cds
> > IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus.fasta
> > IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus.misc_feature
> > IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus.rrna
> > IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus.trna
> > IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus_mitoscaf.fa.gbf
> > IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus_mitoscaf.fa.sqn
> > IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus_mitoscaf.fa.tbl
> > IC11_AAH1795_Hymenoptera_Ichneumonidae_Campodorus_ultimus_mitoscaf.fa.val
> > README.txt
> > circos.png
> > circos.svg
> > errorsummary.val
> > summary.txt
> > work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted.Not-picked
> > work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted.Not-picked.fa
> > work71.hmmtblout.besthit.sim.filtered.low_abundance
> > work71.hmmtblout.besthit.sim.filtered.low_abundance.fasta
> > work71.mitogenome.fa
> > work71.most_related_species.txt
> 
> * which mitogenome fasta file to use?
> * which work71.hmmtblout.besthit.sim.filtered files to use?
> * there are no clean.{1,2}.fq.gz files. Should I use `python3 MitoZ.py all` instead?
> 
> This is my attempt:
> 
> > python3 MitoZ.py all2 --genetic_code 5 --clade Arthropoda --outprefix test 
> > --thread_number 12 --fastq1 clean.1.fq.gz --fastq2 clean.2.fq.gz 
> > --fastq_read_length 150 --insert_size 250 
> > --run_mode 3 
> > --filter_taxa_method 1 
> > --requiring_taxa 'Arthropoda' 
> > --quick_mode_seq_file work71.mitogenome.fa 
> > --quick_mode_fa_genes_file work71.mitogenome_genes.txt  
> > --missing_PCGs ATP6 ATP8 COX3 ND2 ND3 ND4 ND4L ND5 
> > --quick_mode_score_file work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted.Not-picked  
> > --quick_mode_prior_seq_file work71.hmmtblout.besthit.sim.filtered.high_abundance_10.0X.reformat.sorted.Not-picked.fa
> 
> Where `work71.mitogenome_genes.txt ` contains the following text:
> 
> > scaffold41 ND1 CYTB ND6
> > C5251 COX2 COX1
> 
> This is from the summary.txt
> 
> > #Seq_id        Length(bp)     Circularity    Closely_related_species
> > scaffold41     2499           no             Diadegma semiclausum
> > C5251          2608           no             Diadegma semiclausum
> > ## #Seq_id        Start  End    Length(bp) Direction  Type   Gene_name  Gene_prodcut                      Total_freq_occurred
> > scaffold41     21     930    910        +          CDS    ND1        NADH dehydrogenase subunit 1      1
> > scaffold41     933    1000   68         -          tRNA   trnS(uga)  tRNA-Ser                          1
> > scaffold41     1032   2191   1160       -          CDS    CYTB       cytochrome b                      1
> > scaffold41     2183   2486   304        -          CDS    ND6        NADH dehydrogenase subunit 6      1
> > C5251          92     156    65         -          tRNA   trnD(guc)  tRNA-Asp                          1
> > C5251          155    227    73         -          tRNA   trnK(cuu)  tRNA-Lys                          1
> > C5251          227    903    677        -          CDS    COX2       cytochrome c oxidase subunit II   1
> > C5251          962    2501   1540       -          CDS    COX1       cytochrome c oxidase subunit I    1
> > ## Protein coding genes totally found:  5
> > tRNA genes totally found:            3
> > rRNA genes totally found:            0
> > Genes totally found:                 8
> > ## Potential missing genes:
> > #Gene             total_missing_number
> > ATP6                                 1
> > ATP8                                 1
> > COX3                                 1
> > ND2                                  1
> > ND3                                  1
> > ND4                                  1
> > ND4L                                 1
> > ND5                                  1
> > l-rRNA                               1
> > s-rRNA                               1
> > tRNA-Ala                             1
> > tRNA-Arg                             1
> > tRNA-Asn                             1
> > tRNA-Cys                             1
> > tRNA-Gln                             1
> > tRNA-Glu                             1
> > tRNA-Gly                             1
> > tRNA-His                             1
> > tRNA-Ile                             1
> > tRNA-Leu                             2
> > tRNA-Met                             1
> > tRNA-Phe                             1
> > tRNA-Pro                             1
> > tRNA-Ser                             1
> > tRNA-Thr                             1
> > tRNA-Trp                             1
> > tRNA-Tyr                             1
> > tRNA-Val                             1
> > The missing genes might be foud from the
> > '_.high_abundance_' and '_.low_abundance_' files!

Hi Doug, 

Sorry for the confusion.
In short, you can look for the files required by `-run_mode 3` in your quick-mode-run `tmp` directory. 

>which mitogenome fasta file to use?

you can use the the file `work71.mitogenome.fa`. this is a file that should only contain correct mitochondrial sequences.

This file is also in  `tmp/ZZZ.assembly` 

>which work71.hmmtblout.besthit.sim.filtered files to use?

In the `tmp/ZZZ.assembly` directory.

>there are no clean.{1,2}.fq.gz files. Should I use python3 MitoZ.py all instead?

Generally, before NGS assembly, we have to filter our raw reads (provided by sequencing companies) and then use the clean reads to perform assembly.

1. Suppose now you have the raw reads, then you can run MitoZ with the `all` subcommand and with quick mode. In this case, MitoZ has output the clean reads and assembly under the `tmp/ZZZ.cleandata` directory, 

 
2. If you already have your own 'clean' fastq files, you can just provide them to MitoZ for any run mode.


When you finish, you may also found some good results in `work31.mitogenome.fa` and `work91.mitogenome.fa` (in the result directory and/or  `tmp/ZZZ.assembly2` ) if you are lucky.


Please just ask if you still get into troubles.

guanliang
