### ISSUE TITLE
Killed Error occured when running command (mitoAssemble all)

### ISSUE THREAD

**Issue by charlesfoster** [linzhi2013/MitoZ#90]
Hi,

Thanks for the useful software. I've run MitoZ with no issues in the past, but I'm running into an error with a new sample. I get the following: 

>Killed
Error occured when running command:
/app/release_MitoZ_v2.3/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 8

I use the following command

`sudo docker run -v $PWD:/project --rm guanliangmeng/mitoz:2.3 /app/release_MitoZ_v2.3/MitoZ.py \
all --genetic_code 5 --clade Arthropoda --outprefix S3 \
--thread_number 8 \
--fastq1 reads.R1.fq.gz \
--fastq2 reads.R2.fq.gz \
--fastq_read_length 150 \
--insert_size 250  \
--run_mode 2 \
--filter_taxa_method 1 \
--requiring_taxa 'Arthropoda'`

I believe it's related to the same issue as issue #65.  However, I shouldn't run out of RAM because (1) I'm using a laptop with 64 GB of RAM, and (2) I've pre-processed the reads to only theoretically retain mitochondrial reads. Briefly, I map raw reads (from shotgun sequening) to a database of related mitochondrial genomes, and then extract mapped reads into new fastq.gz files. The resulting files are relatively small (~30 Mb), but I've had success with similarly sized files in the past. I have to use this pre-processing approach to avoid running out of memory since I haven't yet been able to get MitoZ to work on the cluster I have access to.

Do you know how I might further troubleshoot what's going wrong? I'm not sure what files or output might be useful to provide - there does not appear to be some kind of error file produced.

Thanks,
Charles

**Comment by linzhi2013** [comment]
Hi Charles,

If your input fq files only have size ~30 Mb, and you have a RAM of 64 GB, then it shouldn't be an out of memory problem.

You can:

1. Shell into the docker container with the command:
```
 sudo docker run -v $PWD:$PWD -w $PWD  -it --rm guanliangmeng/mitoz:2.3
```
2. then run the command inside the container:
```
/app/release_MitoZ_v2.3/bin/assemble/mitoAssemble all -K 71 -o work71 -s work71.soaptrans.lib -p 8  1>assm.log 2>assm.err
```
And then check what will happen. It should be very fast to finish, since your input fq files are very small in size.

Then post the `assm.log ` and `assm.err` files.


Cheers
Guanliang

**Comment by charlesfoster** [comment]
Thanks- files attached. From what I can tell, there isn't much extra info in the files.

[assm.log](https://github.com/linzhi2013/MitoZ/files/5471875/assm.log)
[assm.err.txt](https://github.com/linzhi2013/MitoZ/files/5471876/assm.err.txt)

**Comment by linzhi2013** [comment]
Why did you still use the "all" command? Perhaps "all2" is what you should use.

Please check the content of `work71.soaptrans.lib`, confirm the input Fastq files in this file. Hope the Fastq files are not empty.

If you still can't figure it out, you can send the Fastq files to me via email, I'll check it tomorrow.

**Comment by charlesfoster** [comment]
I used `all` for two reasons. 

Initially, it was an accidental carry-over from when I tried assembling with the full reads files. Then, when I tried using `all2` instead, the analysis died with the same error this issue is about: 
>"Killed Error occured when running command: /app/release_MitoZ_v2.3/bin/assemble/mitoAssemble all  -K 71 -o work71 -s work71.soaptrans.lib -p 8". 

However, if I run the same command with `all` instead, the analysis progresses to assembly and either works (good reads) or fails with "All sequences are low abundance (<10X) CDS_found_lengths_list:  [0] quick mode got no result!" (if reads input files are bad).

For some reason, with one pair of fastq files the analysis throws the "killed" error above no matter what. I can confirm that `work71.soaptrans.lib` contains the correct paths to the input fastq files, that the fastq files aren't empty, and that the STDERR and STDOUT files don't give any clues.

Thanks for the offer to look over the fastq files. Which email address is best to send the files to you? I couldn't find an address on this GitHub.

Charles

**Comment by linzhi2013** [comment]
Hi Charles,

Sorry for my late reply.

If you still have the problem, please send data the fastq files to linzhi2012<MitoZ>gmail<MitoZ>com, replace '<MitoZ>' with '@' or '.'.

Cheers

Guanliang

**Comment by linzhi2013** [comment]
`mitoz_test.all2.sh` command:
```
# make sure your fq1 and fq2 files are in $PWD directory!
fq1=S3_mito_R1.fq.gz
fq2=S3_mito_R2.fq.gz
outprefix=charles
/home/gmeng/soft/udocker/udocker run --rm --volume=$PWD --workdir=$PWD guanliangmeng/mitoz:2.3 \
python3 /app/release_MitoZ_v2.3/MitoZ.py all2 \
--genetic_code 5 \
--clade Arthropoda \
--insert_size 250 \
--thread_number 4 \
--fastq1 $fq1 \
--fastq2 $fq2 \
--outprefix $outprefix \
--fastq_read_length 150 \
1>m.log 2>m.err
```
![image](https://user-images.githubusercontent.com/6203542/98345897-9029e980-2015-11eb-8f6a-c4e46dfc1361.png)

`mitoz_test.all.sh` command:
```
# make sure your fq1 and fq2 files are in $PWD directory!
fq1=S3_mito_R1.fq.gz
fq2=S3_mito_R2.fq.gz
outprefix=charles
/home/gmeng/soft/udocker/udocker run --rm --volume=$PWD --workdir=$PWD guanliangmeng/mitoz:2.3 \
python3 /app/release_MitoZ_v2.3/MitoZ.py all \
--genetic_code 5 \
--clade Arthropoda \
--insert_size 250 \
--thread_number 4 \
--fastq1 $fq1 \
--fastq2 $fq2 \
--outprefix $outprefix \
--fastq_read_length 150 \
1>m.log 2>m.err
```
Result
![image](https://user-images.githubusercontent.com/6203542/98347609-e6982780-2017-11eb-8009-8b08c4c0814d.png)

The m.err file content:
![image](https://user-images.githubusercontent.com/6203542/98347975-7047f500-2018-11eb-802d-02bf463550d6.png)
