### ISSUE TITLE
Issue with Chordate assembly

### ISSUE THREAD

**Issue by KWest20** [linzhi2013/MitoZ#91]
Hi,

I'm running MitoZ v2.3 to build mitogenomes for both arthropods and chordates. The arthropod processing has been successful so far, however once I change the settings to --clade Chordata and --requiring_taxa ‘Chordata’ I seem to get the following error: 

Traceback (most recent call last):
  File "/app/release_MitoZ_v2.3/MitoZ.py", line 1946, in <module>
    check_requiring_taxa(args.requiring_taxa)
  File "/app/release_MitoZ_v2.3/MitoZ.py", line 1890, in check_requiring_taxa
    name_dict = ncbi.get_name_translator([taxa_name])
  File "/app/anaconda/lib/python3.6/site-packages/ete3/ncbi_taxonomy/ncbiquery.py", line 286, in get_name_translator
    result = self.db.execute('select spname, taxid from species where spname IN (%s)' %query)
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 52-54: surrogates not allowed

Any idea what the problem is? Should I remove the requiring taxa parameter?

Cheers,
Katrina

**Comment by Prunoideae** [comment]
You don't need to quote the required taxonomy name, and if specified, it will cause some problem for ete3 to lookup data in the database, so change --requiring_taxa ‘Chordata’  to --requiring_taxa Chordata should solve the problem.

**Comment by KWest20** [comment]
That worked! Thanks a lot!
