### ISSUE TITLE
Can not download release_MitoZ_v2.4-alpha.tar.bz2

### ISSUE THREAD

**Issue by liugang9988** [linzhi2013/MitoZ#92]
Hi Dr Meng,

I am now using your developed tool to assembly mt genome from illumina paired end reads. However, it reported "The site cann't be reached", when I tried to download release_MitoZ_v2.4-alpha.tar.bz2. I suspect this site is not available to China. Could you help to share it to my email 545350593@qq.com?

Thank you very much.

Best,

Gang

https://github.com/linzhi2013/MitoZ/blob/master/version_2.4-alpha/release_MitoZ_v2.4-alpha.tar.bz2

**Comment by linzhi2013** [comment]
Hi Gang,

You can download it from BaiDu cloud.

链接: https://pan.baidu.com/s/1YIULJ9H3BeWKcIZdMZpcuw  密码: 7r9d

I would suggest you just use the Docker, Udocker, or singularity versions of MitoZ if possible.


Cheers

**Comment by liugang9988** [comment]
Thank you very much for your suggestions. I will try to use singularity. Hopefully it works.
