### ISSUE TITLE
Plant mitochondrial genome assembly

### ISSUE THREAD

**Issue by bioramg** [linzhi2013/MitoZ#93]
Hello, 
I would like to assemble the plant mitochondrial genome. Is it possible to assemble using this software?

**Comment by linzhi2013** [comment]
Yes, you can try. 

Theoretically it can assemble plant mt. But it might Fail to pick the plant mt out because the difference between animal mt and plant mt genomes is very large (e. (.g. genes and gene number)

Cheers
