### ISSUE TITLE
MitoZ: error: unrecognized arguments: Chordata

### ISSUE THREAD

**Issue by zzzygolden** [linzhi2013/MitoZ#94]
Hi,
I installed MitoZ (version 2.4alpha) via conda and I am in the mitozEnv. The test succeeded but the error occured when I used my own fastq data:

>$ python3 "/usr/section/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/MitoZ.py" all --genetic_code=auto --clade=Chordata --outprefix=BH-1 \
 --thread_number=16 \
 --fastq_read_length=150 \
 --fq_size=5 \
 --fastq1="/usr/section/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/fastqdata/BH-1/BH-1_1.fq.gz" \
 --fastq2="/usr/section/MitoZ/version_2.4-alpha/release_MitoZ_v2.4-alpha/fastqdata/BH-1/BH-1_2.fq.gz" \
 --insert_size=250 \
 --run_mode 2 \
 --filter_taxa_method 1 \
 --requiring_taxa = Chordata
usage: MitoZ [-h]
             {all,all2,filter,assemble,findmitoscaf,annotate,visualize} ...
MitoZ: error: unrecognized arguments: Chordata

maybe there is a problem with my NCBI database, so I downloaded the file `taxdump.tar.gz` from [https://github.com/linzhi2013/MitoZ/issues/72](url) , but it still not worked and the same error appeared.

What's the cause of this? Could you help me out?

**Comment by Prunoideae** [comment]
Normal argument style in python programs is `--<argname> argvalue`, without `=` or other characters, so instead of `--requiring_taxa = Chordata`, you should specify the parameter like `--requiring_taxa Chordata`.

**Comment by zzzygolden** [comment]
> Normal argument style in python programs is `--<argname> argvalue`, without `=` or other characters, so instead of `--requiring_taxa = Chordata`, you should specify the parameter like `--requiring_taxa Chordata`.

Thanks for pointing out my error. I am a novice in python and learning how to use mitoz at present.

**Comment by linzhi2013** [comment]
Thanks @Prunoideae .
