### ISSUE TITLE
hi, I got an error...

### ISSUE THREAD

**Issue by paul-bio-hh** [linzhi2013/MitoZ#97]
My interest taxa is Mollusca. So I changed script as you mentioned. 
_**And the code below is how I used for an analysis.**_

$python /path/to/MitoZ.py all2 --genetic_code 5 --clade Mollusca --outprefix O-1_quickmode --thread_number 32 --fastq1 trimmed_1.fq --fastq2 trimmed_2.fq --fastq_read_length 101 --insert_size 200 --run_mode 2 --filter_taxa_method 1 --requiring_taxa Mollusca

_**everything seems good so far, but I got an error as below.**_

convert result to gff3 format
cat: './work71.hmmtblout.besthit.sim.fa.genewise/*/*.genewise': No such file or directory
Sorry, the annotation finished with no result!
2021-01-04 14:58:59
rm -rf *.nhr *.nin *.nsq formatdb.log *.tblastn.shell *.length *.blast *.blast.filter *.shell *.blast.solar *.blast.solar.filter *.blast.solar.filter.table *.blast.solar.filter.table.nonredundance *.blast.solar.filter.nr *.genewise *.solar.genewise.gff *.solar.genewise.gff.cds

Traceback (most recent call last):
  File "/NFS/users/creo9447/software/MitoZ-2/release_MitoZ_v2.3/bin/findmitoscaf/filter_taxonomy_by_CDS_annotation.py", line 335, in <module>
    filter_taxa(annt_fa=args.fa, cdspos=cdsposcds_file, outf=args.outf,
  File "/NFS/users/creo9447/software/MitoZ-2/release_MitoZ_v2.3/bin/findmitoscaf/filter_taxonomy_by_CDS_annotation.py", line 198, in filter_taxa
    with open(cdspos, 'r') as fh, open(cdspos_taxa_log, 'w') as fh_taxalog:
FileNotFoundError: [Errno 2] No such file or directory: 'work71.hmmtblout.besthit.sim.fa.solar.genewise.gff.cds.position.cds'
Error occured when running command:
/home/creo9447/miniconda3/envs/mitozEnv/bin/python /NFS/users/creo9447/software/MitoZ-2/release_MitoZ_v2.3/bin/findmitoscaf/filter_taxonomy_by_CDS_annotation.py -fa work71.hmmtblout.besthit.sim.fa -MTsoft /NFS/users/creo9447/software/MitoZ-2/release_MitoZ_v2.3/bin/annotate/MT_annotation_BGI_V1.32/MT_annotation_BGI.pl -db /NFS/users/creo9447/software/MitoZ-2/release_MitoZ_v2.3/bin/profiles/MT_database/Animal_CDS_protein.fa -thread 32 -genetic_code 5 -requiring_taxa 'Mollusca' -relax 0 -WISECONFIGDIR /NFS/users/creo9447/software/MitoZ-2/release_MitoZ_v2.3/bin/annotate/wisecfg -outf work71.hmmtblout.besthit.sim.filtered.fa

I use MitoZ in conda, and MitoZ version is 2.3.
What could be the problem...?

ps. I currently run like this 
$MitoZ/bin/assemble/mitoAssemble all -K 51 -o work51 -s work71.soaptrans.lib -p 32

and I saw this
"Warning: Use too many threads (e.g. > 16) can be problematic" on the git hub. Should this be the problem..?

**Comment by zskysafe** [comment]
![图片](https://user-images.githubusercontent.com/51896128/103534766-7d734a00-4eca-11eb-95f9-29ac5fec2bb3.png)
You can use docker first. This problem has not been solved yet
