### ISSUE TITLE
Problem using the Singularity image to run MitoZ v2.3

### ISSUE THREAD

**Issue by hempelc** [linzhi2013/MitoZ#99]
Hi there,

I downloaded the Singularity image of MitoZ v2.3 following the instructions in the [INSTALL.md of v2.3](https://github.com/linzhi2013/MitoZ/blob/master/version_2.3/INSTALL.md):

```
singularity pull  --name MitoZ.simg shub://linzhi2013/MitoZ:v2.3
```
The download is successful, but when I run the image, I get the following error:
```
$ ./MitoZ.simg --help
/hdd1/chempel/.local/lib/python3.6/site-packages/scipy-1.4.1-py3.6-linux-x86_64.egg/scipy/__init__.py:144: UserWarning: Numpy 1.13.3 or above is required for this version of scipy (detected version 1.12.1)
  UserWarning)
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
package ete3 not found! Please install it!
Then setting up a local copy of the NCBI taxonomy database followging
http://etetoolkit.org/docs/latest/tutorial/tutorial_ncbitaxonomy.html
```

I shelled into the image to check the version of the installed python modules:
```
Singularity> pip freeze
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
asn1crypto==0.24.0
biopython==1.69
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
click==7.1.2
coloredlogs==14.0
colormath==3.0.0
conda==4.6.1
cryptography==2.3.1
cycler==0.10.0
Cython==0.29.14
decorator==4.4.2
dill==0.3.1.1
EMIRGE==0.61.0
ete3==3.0.0b35
future==0.18.2
humanfriendly==8.2
idna==2.8
importlib-metadata==1.7.0
Jinja2==2.11.2
joblib==0.14.1
justblast==2020.0.3
kiwisolver==1.2.0
lxml==4.3.0
lzstring==1.0.4
Markdown==3.2.2
matplotlib==3.2.1
mmtf-python==1.1.2
msgpack==0.6.0
multiqc==1.9
networkx==2.5
numpy==1.12.1
olefile==0.46
panda==0.3.1
pandas==1.0.1
Pillow==4.2.1
plyvel==1.1.0
psutil==5.7.0
pycosat==0.6.3
pycparser==2.19
pyfaidx==0.5.8
pyOpenSSL==18.0.0
pyparsing==2.4.5
PyQt5==5.14.1
PyQt5-sip==12.7.1
PySocks==1.6.8
python-dateutil==2.8.1
python-igraph==0.8.2
python-qt==0.50
pytz==2019.3
PyYAML==5.3.1
QtPy==1.9.0
reportlab==3.4.0
requests==2.21.0
ruamel-yaml==0.15.71
scikit-learn==0.22.1
scipy==1.4.1
six==1.13.0
sklearn==0.0
spectra==0.0.11
termcolor==1.1.0
texttable==1.6.2
tqdm==4.38.0
urllib3==1.24.1
zipp==3.1.0
```
And to check if ete3 is running:
```
Singularity> ete3
/hdd1/chempel/.local/lib/python3.6/site-packages/scipy-1.4.1-py3.6-linux-x86_64.egg/scipy/__init__.py:144: UserWarning: Numpy 1.13.3 or above is required for this version of scipy (detected version 1.12.1)
  UserWarning)
[...]
```
Any idea why there is a conflict between the installed numpy and scipy versions?

Thanks!
Chris

**Comment by linzhi2013** [comment]
Hi Chris,

It seems that when you do `$ ./MitoZ.simg --help`, MitoZ will try to find the Python packages from your HOME directory:
```
/hdd1/chempel/.local/lib/python3.6/site-packages/scipy-1.4.1-py3.6-linux-x86_64.egg/scipy/__init__.py:144: UserWarning: Numpy 1.13.3 or above is required for this version of scipy (detected version 1.12.1)
  UserWarning)
```
I didn't notice this way of running Singularity image can cause this problem. But now I understand that it's due to Singularity will "mount" the user's HOME directory into the container automatically, so this causes the problem.

If you shell into the container, then do 
```
/app/anaconda/bin/python3 /app/release_MitoZ_v2.3/MitoZ.py -h
```
this should work.


However, the Singularity MitoZ image doesn't come with the NCBI Taxonomy database, so when you run MitoZ for the first time, it will try to download and install the NCBI Taxonomy database. 

https://github.com/linzhi2013/MitoZ/blob/master/version_2.3/INSTALL.md (section 4.5)
>For more details, please refer to http://etetoolkit.org/docs/latest/tutorial/tutorial_ncbitaxonomy.html
>
>Notice If you have difficulties in downloading the database from NCBI, please forward to >https://github.com/linzhi2013/MitoZ/issues/72#issuecomment-666215301.
>
>Recently, the NCBI taxonomy database (Sep 2020) seems to have some problems (e.g. sqlite3.IntegrityError: UNIQUE >constraint failed: synonym.spname, synonym.taxid), see https://github.com/linzhi2013/MitoZ/issues/81#issue-699246501 >and https://github.com/linzhi2013/MitoZ/issues/79#issuecomment-689582348. If this happens to you, you should refer to >https://github.com/linzhi2013/MitoZ/issues/72#issuecomment-666215301 first.


the Docker or Udocker image is most complete, they come with the NCBI Taxonomy database, you may try them if the Singularity doesn't work for you.

Cheers

**Comment by hempelc** [comment]
Hey Guanliang, thanks for the quick response!

I followed your recommendation, shelled into the container, and ran
```
/app/anaconda/bin/python3 /app/release_MitoZ_v2.3/MitoZ.py -h
```
But I got the same error:
```
Singularity> /app/anaconda/bin/python3 /app/release_MitoZ_v2.3/MitoZ.py -h
/hdd1/chempel/.local/lib/python3.6/site-packages/scipy-1.4.1-py3.6-linux-x86_64.egg/scipy/__init__.py:144: UserWarning: Numpy 1.13.3 or above is required for this version of scipy (detected version 1.12.1)
  UserWarning)
RuntimeError: module compiled against API version 0xb but this version of numpy is 0xa
package ete3 not found! Please install it!
Then setting up a local copy of the NCBI taxonomy database followging
http://etetoolkit.org/docs/latest/tutorial/tutorial_ncbitaxonomy.html
```
I looked a bit deeper into the Python packages from my HOME directory, since it seems that MitoZ tried to access these.
Turns out I just have python3.8 installed, however, my ~/.local/lib/ directory also contained python3.6/site-packages/, which MitoZ was trying to access. No idea why that python3.6 directory is there to be honest, must be a relict from previous installations and uninstallation. Anyway, I removed the scipy-1.4.1-py3.6-linux-x86_64.egg directory from there, and now
```
$ ./MitoZ.simg --help
```
prints the help!

If I run into another issue, I will try the Docker image, though. Thanks!
